sugarlabs/musicblocks

- css/activity.css
- js/basicblocks.js
- js/block.js
- js/blocks.js
- js/musicnotation.js
- js/palette.js
Added a block to allow selection of do re mi...
> add solfage block type with selection

- documentation/README.md
Hi,
I took a good pass at the README file.
I made some decisions for style, but please let me know what you prefer.
These edits definitely need edits themselves.
Devin
> Hacked on README <--Please edit my edits!

- js/activity.js
- js/logo.js
> Step note fix

- lilypond/README.md
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/4874210291744768/
> Added a guide for exporting to Sheet Music

- js/palette.js
Bug- Palette after drag, a block can be taken from the palette only once.
> This fixes bug #99

- js/basicblocks.js
- js/block.js
- js/logo.js
Added the invert block functionality
> Feature: Invert Block

- js/basicblocks.js
- js/logo.js
- js/matrix.js
A lot of places these symbols cause issues.
(https://github.com/walterbender/musicblocks/pull/97 also needs this)
> Move symbols to use standard HTML

- js/blocks.js
> fixes issue #148

- js/activity.js
- js/samplesviewer.js
* Removed the prefix while displaying it from the server to the list
Report: https://markable.in/file/5b2c9fa0-bf7d-11e5-a6fb-0a41a440e2ed.html
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5958307437084672/?sp-page=1
> Added the prefix 'MusicBlocks_' to the files saved on server

- css/activity.css
- index.html
Fix for https://github.com/walterbender/musicblocks/issues/112
Related GCI Task: https://codein.withgoogle.com/dashboard/task-instances/6214475560517632/?sp-page=1
In continuation of https://github.com/walterbender/musicblocks/pull/117
> Fixed the template loading page

- js/activity.js
* Removed the overlap with turtle
> Fixed the default matrix as per the discussion with pikurasa.

- js/activity.js
- js/logo.js
https://github.com/walterbender/musicblocks/issues/52
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5765217636057088/?sp-page=1
> Fixed the default tempo

- js/activity.js
- js/samplesviewer.js
> fixes issue #156

- documentation/README.md
https://github.com/walterbender/musicblocks/issues/146
> Fix spelling 'solfege'

- header-icons/export-button.svg
- js/matrix.js
On clicking the button the music matrix is shown on a html page.
Should the styling on the cells be present or should I remove it and show just a plain table with the values?
> Add export button to matrix to save it to a html page

- js/logo.js
> Manually running blocks after displacing turtle solved

- js/matrix.js
Set the max and min width of each of the notes so they don't collapse to similar sizes
> Fix issue #178

- js/blocks.js
Length of existing action button were initially compared with 1 instead of 0 for giving name.
> -Fixes issue #203

- guide/README.html
Used a markdown to markup converter. Adjusted styling and added anchors to headings as required, Issue - https://github.com/walterbender/musicblocks/issues/201
> Port README.md to HTML

- js/activity.js
- js/logo.js
One button is created which closes the statistics.
> Display Statistics close button #132

- js/activity.js
- js/palette.js
> palette position preserved

- js/blocks.js
- js/logo.js
> mapping of action and turtle solved

- js/matrix.js
> matix when window resize

- js/blocks.js
--> Here silence block is automatically created and placed inside in note block, if all blocks are removed from note block.
--> If user put some block into note block, then silence block is removed.
> Implements note block Behavior #239

- js/musicutils.js
Added Chromatic Scale (12 tones)
If I got it right I can add others.
(We need a way to bring the ability for user to change/add/remove these defaults to UI)
> Add Chromatic Scale

- CREDITS
Added Richard Hermann to list of names in CREDITS.
How do we want to group the websites? All together?
> Added Richard Hermann to the names in CREDITS

- js/pitchstaircase.js
solves the issue of having multiple stairs.
> multiple copies of stairs sometimes.

- js/rhythmruler.js
The name is containing now the drum name.
> Extended name of chunks created by Rhythm Ruler

- js/pitchslider.js
There is no need of the if condition if that._isKeyPressed is always 1.
> Line 121: Changed that._isKeyPressed to 0

- js/pitchtimematrix.js
Add an array that stores cell.innerHTML to use in _setNoteCell.
> Minor changes to initialization of drumHTML

- js/logo.js
- js/turtle.js
GCI 2016 - eohomegrownapps
I have implemented the ‘turtle blink’ feature as described. It changes
the transparency to 0.5 for 100ms every time a note is played.
> Turtle Blink (Music Blocks)

- index.html
- js/pitchtimematrix.js
> Made matrix buttons always visible (#248) / Removed 'Solfa' label

- js/blocks.js
This PR makes minimum distance relative to blockscale for issue #373
> Fixes #373

- css/activity.css
- js/tempo.js
Fixed #383.
Also added a simple compression animation, though the effect is only obvious on low BPMs.
> Fixed #383

- js/palette.js
Applying ES6 Format for less "X: X" in palette.js for issue #345
> Fixes #345

- js/pitchdrummatrix.js
@walterbender ,this PR fixes issue #380 . The green box under solfa moves along with the box now.
> Fixes #380

- charts/TripletChart.svg
- charts/TupletChart.svg
- guide/matrix1.svg
removed repeated "value" text
fixed alignments of equations
> fixed alignments

- guide/matrix1.svg
I realized that the pitch-time matrix did not have a tuplet rhythm, which I had added. This was removed in this PR.
> fixed guide picture

- js/basicblocks.js
- js/block.js
- js/blocks.js
- js/musicutils.js
- js/palette.js
- js/turtledefs.js
I have added an east indian solfege block.
> Added Eisolfege

- js/clearbox.js
That error seemed to destroy functionality of `delete all` feature.
> Fixed reference error in clearbox.js

- js/block.js
This PR is fixing issue #396 . I have set the condition to (finalPos <(45*scale)) since at (40*scale) it was working perfect for my computer.Since , @walterbender suggested for (60*scale) , I tried to reach a minimal value which can work fine on various computer screens. Review needed for the scaling factor if it doesn't seem well.
> Fixes: #396

- index.html
I have changed the favicon icon on the web browser from a turtle to a rodent as per the favicon.ico icon file.
> FIXED #513: Changed Turtle Favicon to Mouse Favicon

- js/logo.js
This PR fixes issue #516 ; repeat block shows undefined behaviour when it is given a negative number.
Now, MB throws an error when the argument to repeat block is a negative number and the music stops. The error thrown is "Argument cannot be a negative number".
@walterbender , please review :)
> Fixes issue #516; repeat block shows undefined behaviour

- js/analytics.js
- js/basicblocks.js
- js/logo.js
- js/protoblocks.js
- js/status.js
This PR fixes issue #517 , i.e. I have added the "Raised to the power of" block in the Number palette.
@walterbender ,please review :)
> Issue #517; "To the power of" block added

- js/logo.js
This PR serves as a solution for access to mic for the 'loudness' block. I haves used Tone.js to implement the mic access. Now, access to mic permission is asked when loudness block is used in any other block.
@walterbender  please review , there may be some changes needed with the error handling i think.
> Fixes #580

- js/basicblocks.js
This PR changes comment from "A in C Major" to "G in C Major"
> Comment changed

- js/trash.js
Regarding issue #588 
I've decreased the time for removal of an item. Normally it took about 5 seconds. Now it is almost instant. See the gifs.
Older :
Newer :
> Improved trash

- guide-es/transform9.svg
- guide/transform9.svg
SVGs updated as per issue #593
> Fix to #593

- js/basicblocks.js
Fix to #564. Changed the name of the crescendo block to “crescendo +/-“
> Changed name of crescendo block to "crescendo +/-"

- js/rhythmruler.js
This PR fixes #594  which asked for adding hover on the rhythm ruler cell.
I have added the hover along with the values in the cell to appear large and bold when there is a hover on that particular hidden value cell.
> Fixes #594 ;Hover added

- js/logo.js
This PR does fine-tune the input samples.
Earlier the value variable had order of magnitude(oom) higher than the expected value oom.
Now, the oom remains the same for the value variable too.
> Fine-tuning done for loudness block

- js/basicblocks.js
This PR changes the pitch arg in invert block from "note" to "name" as suggested by Devin.
> Invert block : note to name

- js/basicblocks.js
This PR changes the default in pitch number from '9' to '7'
> Default changed for Pitch Number

- css/activity.css
- index.html
- js/palette.js
- js/utils.js
I followed the suggestion given by @pikurasa of adding a permanent color strip on the left side of the screen for the palettes to be placed in and on the right side there would be dynamic color updates.
Here is how it looks:
> Fixes #402 Color Issue

- js/basicblocks.js
This PR changes the default value of hertz block from 440 to 392 hertz.
> Default for hertz block

- css/activity.css
This PR improves the popdown palette which showcases the block palette when the the screens get narrow. This PR fixes this part of #623 .
I am attaching the screenshots to review.
> Popdown palette improved

- js/launch.js
- manifest.json
It is more better and a general version of manifest.json. Still needs some research and  time to make it 100% perfect (like launching).
https://github.com/walterbender/musicblocks/issues/647
> Fixed manifest.json

- js/palette.js
Navigation buttons in the palette are not working
> Issue 650:Palette navigation buttons issue

- js/palette.js
Down Icon cannot be seen in mac, and in windows laptop it's not placed in the bottom properly.
Also when re-sizing the browser, icon is now shown in the correct place.
> fixes #650 -- Navigation buttons visibility

- guide/README.md
Added hover text, fixed some image display issues with save, close erase button and fixed minor typo.
> Resolved issue #665 (For Outreachy 2017) Added hover text to images in guide

- js/basicblocks.js
Name of pitch-drum matrix changed to pitch-drum mapper as discussed.
> pitch-drum matrix name changed

- js/basicblocks.js
>Changed default for box to 4 from 100.
>Print block now has a default text box with "Music Blocks"
> Minorbug fixes

- js/activity.js
alert() is probably not the best way to communicate the error
back, but it seems to be used in a few place (in this same
file).
> Handle bad JSON when loading from a file

- js/basicblocks.js
- js/logo.js
- js/modewidget.js
- js/musicutils.js
- js/pitchdrummatrix.js
- js/pitchslider.js
- js/pitchstaircase.js
- js/pitchtimematrix.js
- js/rhythmruler.js
- js/tempo.js
@walterbender  , Able to create the distortion effect, though one thing I cannot figure out
>In this.performNotes() in musicutils.js , I have passed "A1" to triggerAttackRelease as notes though I should have straightforwardly passed notes as one of the parameters.
Observation : The effect doesnt seem to take place when I used notes . Reason unknown as of now
> Effects for timbre widget

- js/musicutils.js
Added:
* Harmonic major
* Harmonic minor
* Melodic minor
> Make available more modes

- js/activity.js
I used eslint to spot unused vars and went ahead and
removed them. I also found a few loops used to add up
the number of keys in a dictionary; this can be simplified
by using Object.keys().length.
I quickly tested things and it looks fine :)
> Cleanup unused variables & simplified loops

- js/logo.js
The graphics were not repeating but the beats were duplicating/repeating. This fixes it.
> Fixes duplicate block bug

- js/activity.js
https://github.com/walterbender/musicblocks/issues/744
Added drag and drop .tb file to load project. Need a bit more testing.
> Add drag and drop project feature

- js/activity.js
- js/block.js
(1) add error timeout (w/ Hrishi)
(2) fix issue with block scaling
(3) fix issue with sticky run button
> two bugs and an enhancement

- js/logo.js
- js/timbre.js
> Issue #774 fixed

- js/abc.js
- js/lilypond.js
- js/logo.js
- po/si.po
Fixes #803 by enabling notes to be embedded inside other notes and played in parallel. (The difference between this and a chord is that the notes can vary in duration, not just pitch).
Also implements appropriate Lilypond output (although this code could use more testing) and puts in a stub for ABC output.
> Note in note

- index.html
Added a few lines of CSS which centre the loading animation.
> Centre the loading splash in viewport

- js/basicblocks.js
https://github.com/walterbender/musicblocks/issues/839#issuecomment-340865350
> Scalar notes have no modifier (reffered to in #839)

- js/basicblocks.js
I think I found some typos. Please confirm.
> 11 02 2017 edits

- po/README.md
- po/ja.po
I think that I got the hang of editing PO files, however I suspect that the error I made a while ago is still here causing us trouble b/c around line 3700 or so I do not see the pattern of filename, msgid, msgstr that I see above this part of the file.
Also, I see some names that I thought we changed, like "free time"
Whatever we need to get on track, let's do it and I promise never to make _that_ mistake again.
Once this is complete I would like to work with someone else to make sure that my translations make sense. Then, once that translation is verified, I want to create a kana file for kids who are still learning to read.
> Updates to Japanese translation by Devin

- header-icons/upload-planet.svg
eohomegrownapps - GCI
Fixed issue #900
In keeping with the MB icon style, I used the 'down' arrow from paste-button.svg, rotated it and resized the planet icon in upload-planet.svg to fit the 'down' arrow in the bottom right corner.
> Fixed issue #900

- header-icons/open-merge-button.svg
- js/activity.js
eohomegrownapps - GCI
Fixed issue #867
I added support for long and extra long click to the right menu buttons as in the top buttons. I added a merge function when the load button is long-pressed; this skips the sendAllToTrash function when loading a project. I made an icon for long-press of the load button; this is a folder with a merge-ish symbol in the middle.
> Fixed issue 867

- header-icons/download-merge.svg
- js/activity.js
- js/samplesviewer.js
eohomegrownapps - GCI
Fixes issue #919 
I added support for the merge function in Planet - adding a new icon to the thumbnails and adding a merge feature as per pull request #918. I also added merge functionality on extra-long-click (in case a user holds for too long) and for both cases of the `if (_THIS_IS_MUSIC_BLOCKS)` statement.
> Fixes issue 919

- js/logo.js
I tweaked the code slightly (it did not make sense that notes should still be played even when suppressed) and then tried running the code again - the bug disappeared!
> Fixes #922: Playing Music Slow

- css/activity.css
Temporary fix to allow search bar to gain focus when clicked by changing the border colors 
#927
> Focus search bar

- js/basicblocks.js
- js/logo.js
- js/musicutils.js
- js/timbre.js
This issue fixes #911 . I used the tone.js APIs to initialize a noise synthesizer which has the ability to generate white, brown and pink noise (the three types of noises the noise synthesizer in tone.js can produce). The noise block can be found in the Tone section, below the distortion block (as seen in the screenshot).
> Fixes #911: Creating A Noise Block

- js/basicblocks.js
- js/logo.js
- js/macros.js
Fixes #528 
It was suggested that a hidden block be made, though I just modified the existing block as it was easy enough.
> Set master set bpm to take two args

- js/background.js
Added code to allow the extension to work with firefox
> Make extension firefox compatible

- js/activity.js
- js/turtledefs.js
This allows multiple shortcuts being used in a row to chain, allowing music to be created more easily! I also added a "Shortcuts" panel to to tutorial, which can also be used for any future shortcuts. Fixes #119
> Adjust docks when using shortcuts to add notes

- guide-zhCN/README.md
@pipix51 I decided that solfege is best translated into 唱名. Also for note value, my translation is closer "note length" since value is vague. Let me know if you wanted to use a different translation, but it'll make sense regardless. 
Anywho, here's section 2 of the chinese guide; mandarin is my first language but it is not at all like riding a bike.
> Chinese guide section 2

- js/widgets/status.js
Position of output of status widget while running corrected , now the widget stays where the user drags it to.
> Fixed Issue #850

- po/ja.po
I translated the newest strings.
> 2017 12 29 new ja strings

- js/activity.js
Fixes #1025 
It'll still take a while to load, however in this situation the previous project won't continue running.
> Stop music and clear when browser browser is opened

- header-icons/bigger-disable-button.svg
- header-icons/smaller-disable-button.svg
- js/activity.js
- js/utilitybox.js
Increase/Decrease icon grey out indicating that blocks can no longer be increased/decreased.
> Fixed Issue #771 (Increase/Decrease Max)

- js/README.md
based on what i have learnt or done, i tried to add more information that is hopefully relevant and helpful.
some changes i have made included:
> improved formatting + added more information

- js/activity.js
- js/blocks.js
Fixed the functionality of paste button on the first long press .
> Fixed Issue #987

- debug.log
- header-icons/plugins-delete-button.svg
- header-icons/plugins-delete-disabled-button.svg
- js/activity.js
- js/palette.js
- js/turtledefs.js
- js/utilitybox.js
Added the "delete plugin button" on the same panel as the load plugin.
> Fixes Issue #1065

- js/samplesviewer.js
As per the discussion on issue #937 , I have removed the trash can on the current project.
> Fixes Issue #937

- js/activity.js
- js/palette.js
There are few issues while scrolling the screen using mousepad / mousewheel :
1. It should work only when the screen in unlocked.
2. blocksContainer (screen) should not scroll on scrolling the Left most menu of palette buttons.
The above mentioned issues are fixed in this pull request.
> Fixes issues while scrolling the screen using mousepad

- js/widgets/tempo.js
Fix [#1124](https://github.com/walterbender/musicblocks/issues/1124#issuecomment-369571272): Increment/Decrement by 5 changes to 10%.
> Fix #1124: Increment/Decrement by 5 changes to 10%.

- guide/README.md
- guide/note3.svg
Added current, next and previous examples to the guide under 'pitch blocks' section.
> Added current, next and previous examples to guide

- js/logo.js
- js/utils/musicutils.js
As per the discussion on pr #1137, I have changed the behavior of 'current' text block according to the nearest octave schema.
> Behaviour of 'current' text block changed

- po/ja.po
This has some easy changes. Some of the others are more technical, but I wanted to start with low lying fruit.
> 2018 03 06 ja

- css/activity.css
- js/activity.js
- js/widgets/timbre.js
As per the discussion on #1150, I have added the name at the top of the widget. This name is editable and it also changes the argument label to the widget block.
> Fixes #1150 --Added name at the top of timbre widget

- planet/js/GlobalCard.js
- planet/js/LocalCard.js
The URL for sharing should point to https://musicblocks.sugarlabs.org
> update share URL

- js/block.js
- js/blocks.js
Now calculating actual size of text instead of number of characters. limited number of alphabets shown to 5. The font used is sans.
> Fix for issue #1141  --text exceeds action block

- guide/timbre2.svg
- guide/timbre2a.svg
- guide/timbre2b.svg
- guide/timbre2c.svg
- guide/timbre2d.svg
- guide/timbre2e.svg
- guide/timbre2f.svg
- guide/timbre3.svg
- guide/timbre4.svg
- guide/timbre5.svg
- guide/timbre6.svg
- guide/timbre7.svg
Added timbre name to the upper left side of each timbre widget graphics in guide.
> Added name to timbre widget graphics in guide

- js/lilypond.js
- js/turtledefs.js
Now the shortnames are not hardcoded and they are extracted from instrumentName. occupiedShortNames array keeps record of used shortNames so that we don't use them again for a new instrumentName. If the instrumentName is of one alphabet then shortName = instrumentName. If there is no space in the instrumentName (i.e. one word instrumenName) then use alphabets from 0th index and keep adding more alphabets until a unique shortName is found eg. mouse --> mo, mou, mous, mouse. If instrumentName has space in it (more than one word instrumentName) then initially choose one alphabet from word1 and one alphabet from word2, then until a unique name is found keep on adding next alphabet by giving preference to second word eg. gray squirrel --> gs, gsq, grsq, grsqu.
> Fix for #782

- js/widgets/pitchtimematrix.js
Now clicking on STOP or CLOSE, performance ends on that note itself.
Used variable 'a' as flag to make sure for loop inside this.__playNote does not iterate once more after clicking stop or close.
> fix for issue 1173

- js/basicblocks.js
- js/block.js
As per #1225 pie menus have been added to note value expressions.
One menu is used for the numerator, another for the denominator.
Signed off by @pikurasa
> Add pie menu for note values

- README.md
> Corrected URL of contribution guidelines

- README-ja.md
> Added a draft japanese translation of the README

- FAQ/README.md
This is just a draft.
@walterbender when you have time please just tell me if this is on the right track (in the right folder, right layout, etc). I will add more to it later.
> Created a draft of a comprehensive FAQ, based on real questions

- po/ja.po
This has some more major changes. The rest I will leave to the editors at Gakken.
> made changes based on issues I found working on ja-kana

- po/ja-kana.po
This is a work in progress
I wanted to signal to everyone that I am in the middle of working on this.
Working on this has brought up important questions that I detail in the commit notes
> Just make kana

- po/ja-kana.po
- po/ja.po
@walterbender Please pull this before working on https://github.com/sugarlabs/musicblocks/issues/1334
@ukkari Please let me know if I have made any changes that you would like to reverse, but overall it should be an improvement
> 2018 09 05 japanese edits and additions

- po/ja.po
You can either 1) pull now (and I can make kana version in new branch) or 2) wait for my parallel kana version, then pull.
@walterbender Please let me know what you would like to do. Taking break now...
> 2018 09 05 more japanese edits and additions

- js/palette.js
I tried hover and I like hover
:p
...and more importantly, now I know how to put it in there!
:p :p
I also made click an option as well for "just in case".
> 2018 09 24 ui sketches

- js/activity.js
I was looking to work on some other stuff when I found what I am pretty sure is a typo
> Fixed Typo | truee -->> true

- js/SaveInterface.js
- js/activity.js
Rewrote code to call planet and check if the user is offline or not. Depending on this, the ability to 'save as PDF' will be available.  
Edit: I realised the [issue](https://github.com/sugarlabs/musicblocks/issues/1211) wasn't properly embedded
> Fixes #1211

- js/languagebox.js
- po/ja-kana.po
- po/ja.po
Added spaces to kana version for readability; made kana.po up-to-date with ja.po; fixed some errors and typos in ja.po
> 2018 09 27 kana needs spaces

- guide/README.md
- guide/temperament1.svg
- guide/temperament2.svg
- guide/temperament3.svg
- guide/temperament4.svg
- guide/temperament5.svg
- guide/temperament6.svg
- guide/temperament7.svg
This PR is with reference to Temperament Widget Documentation. It has been developed as a part of GSoC'18 program.
> Documentation of Temperament Widget

- js/SaveInterface.js
The code is needed to run MB with Electron as prompt() is not supported by Electron.
> not using promot() when it runs with Electron

- js/turtledefs.js
"Do Mi Sol"  is what is asked for in https://github.com/sugarlabs/musicblocks/issues/1437
> "Do Mi Sol", not "Do Re Mi" | This creates an C maj arpeggio

- js/palette.js
> Search bar autocollapse (Fixes #1450)

- js/activity.js
- js/widgets/help.js
About page was not showing due to new additions in the help menu.
Perhaps a more robust solution is needed?
> Fixed about page not showing when clicking logo 

- js/utils/synthutils.js
All of the instruments' sounding pitches should now be exact.
> Flute adjusted down a TT; cello and tuba up an octave

- js/activity.js
Fixes Pallette Bar hiding on search, satisfies gci task https://codein.withgoogle.com/tasks/4750769602428928/?sp-organization=5730203977383936&sp-categories=1&sp-is_beginner=False
> Fixes Pallette Bar hiding on search

- index.html
- js/activity.js
- js/toolbar.js
Migrated some init code from index.html to toolbar.js. 
Fixed 'centralisation' of blocks when the home button is clicked (with aux toolbar open).
Standardised tooltip delay times and moved them to toolbar.js.
Changed save button action to hard stop.
> Fixed #1532, Fixed #1534 + made some small toolbar code improvements

- index.html
- js/activity.js
- js/languagebox.js
- js/toolbar.js
Made Language selection as a pull-down list
> Prevent Settings toolbar from disappearing on 'Select Language' button click

- fonts/material-icons.css
- index.html
> Localised Material Icons (Fixed #1548)

- js/activity.js
Removed some legacy code that was causing help to open on resize.
Help widget now renders on startup.
> Fixed #1538

- index.html
- Formatted activity.js.
- Reordered toolbar code to after the widgets.
Should resolve https://github.com/sugarlabs/musicblocks/issues/1541
Please test.
> Moved toolbar code after widgets (Fixes #1541)

- po/ja.po
TODO:
1) Review
2) Some word collisions, which Devin will post on GitHub
3) Some questions, which Devin will also post to GitHub
...after review...
4) Begin ja-kana.po
> Input of local.ini and Sheet 4 and 1 from Gakken to ja.po

- js/logo.js
Music Blocks has little internal documentation. To help the developer, this change to `js/logo.js` will add JS docstrings to the eighty-nine (89) functions/methods nested singly in the function `Logo()`.
_PR-ed as dxa_kly for Google Code-in 2018_
> Provides docstrings for logo.js

- po/ja-kana.po
- po/ja.po
This has an initial up-to-date kana.
I say "initial" because I am certain it needs review. Please merge so that JA team may review it.
> 2018 11 29 kana

- js/block.js
Added pie menu for set heading block.
> Pie Menu For "Set Heading" block

- js/block.js
- js/utils/platformstyle.js
The instances where the colors are being defined directly have been replaced with references to platformColor. Some new entries have been defined in the platformColor dictionary.
> Consistent Style

- js/activity.js
onblur event was bound to doStopButton -> it is now bound to doHardStopButton(true)
I also cleaned up some typos which were causing window dimensions to come up  undefined
> Activity cleanup

- js/turtledefs.js
- po/ja-kana.po
- po/ja.po
C = 0 for pitch number, not 1
1 would be scale degree
> Updates to JA -- getting close | Also changed pitch number help

- po/ja-kana.po
As requested in https://github.com/sugarlabs/musicblocks/issues/1571#issuecomment-445464955
> Added Cartesian/Polar translation to Kana

- po/ja.po
Please look carefully through these. 
This is my first time editing po files so it's a learning experience :) (please let me know if/where I went wrong).
> Added JA strings for localise save.

- planet/js/StringHelper.js
- planet/js/helper.js
I changed and enabled tags for translation.
I **think** that generating the PO files and accompanying translations is all that is required.
Please test - I am not sure at all if this has fixed the issue (currently the tags are still in English which, as I understand, is due to the strings themselves not having translations in the po files).
For future contributions, how would I go about generating the PO files myself? (in order to test similar translation patches more thoroughly)
> "Show more tags" / "Show fewer tags" in Planet

- planet/js/GlobalPlanet.js
This PR implements infinite scrolling for the planet. See screenshot below:
Fixes #1650
> Added scroll event to planet for infinite scrolling Fixes #1650

- js/turtle.js
The icons at the top right corner did not showed the encircling effect on
hover.
Now the icons show the encircling effect by making changes in the file
turtle.js.
Fixes https://github.com/sugarlabs/musicblocks/issues/1683
> Encircling effect on top icons

- js/README.md
- js/guide_addingblocks.md
Corrected spelling mistakes in readme and guide_addingblocks.
> Spelling error in readme

- index.html
Corrected the inverted comma error in some input tags in index.html
> Corrected typos in index.html

- po/ja-kana.po
- po/ja.po
> 2019 01 18 ja updates

- js/playback.js
- js/widgets/help.js
- js/widgets/modewidget.js
- js/widgets/musickeyboard.js
- js/widgets/pitchdrummatrix.js
- js/widgets/pitchslider.js
- js/widgets/pitchstaircase.js
- js/widgets/pitchtimematrix.js
- js/widgets/rhythmruler.js
- js/widgets/status.js
- js/widgets/temperament.js
- js/widgets/tempo.js
Fixed the remaining drag icons issue.
> drag icons fix

- po/pt.po
Update pt.po file Brazilian Portuguese translation
> Update pt.po file Brazilian Portuguese translation

- css/activity.css
- css/style.css
fixed the search bar type text that wasnt showing on firefox
> fixed the search bar type text that wasnt showing on firefox

- po/pt.po
Fix Brazilian Portuguese translation
> Fix Brazilian Portuguese translation

- documentation-pt/README.md
Brazilian Portuguese README.md  pt_BR
> Brazilian Portuguese README.md  pt_BR

- js/activity.js
- js/toolbar.js
Horizontal Scrolling button was not working. Clicking on it does not do anything. This PR fixes that.
> Horizontal scrolling fix

- js/block.js
- js/blocks.js
- js/utils/musicutils.js
This fixes the label issue in Temperament widget as described in #1717
> label not shown in temperament widget: fixed #1717

- js/widgets/timbre.js
There was a issue with timber widget as shown in the images. The blocks were not loading or loading improperly.
Block does not load when clicked for the first time
Block loads but not properly
> Fixed timber widget synthesizer issue

- planet/js/Publisher.js
Setting cursor to wait while publishing a project in planet as described in #1185
> Wait cursor when publishing a project - #1185

- js/widgets/modewidget.js
- js/widgets/musickeyboard.js
- js/widgets/pitchdrummatrix.js
- js/widgets/pitchstaircase.js
- js/widgets/pitchtimematrix.js
- js/widgets/rhythmruler.js
- js/widgets/temperament.js
- js/widgets/tempo.js
- js/widgets/timbre.js
for it to be easily asscessed on smaller screens
> changed the postion of the "x" icon on the widget

- index.html
- js/logo.js
- js/utils/platformstyle.js
- js/widgets/pitchtimematrix.js
Added the pie-menu open close functionality along with divide note function(currently only table is changing not the blocks).
Facing a little problem with text in pie-menu.
> Added the pie menu and basic of divide note function

- css/activities.css
- index.html
- js/activity.js
Replaced canvas text box with HTML div and added close icon
>  Fixes #1726 Clearing print text more obvious

- js/utils/musicutils.js
- js/utils/platformstyle.js
- js/widgets/pitchtimematrix.js
Added a button to add notes(pitch, hertz, drum) from inside the phrase maker
> added add note function

- js/utils/musicutils.js
- js/widgets/pitchtimematrix.js
Replaced block names by labels for solving translation problem stated in #1808
> block name replaced by block label for translation

- images/TamTamMini.svg
- js/utils/musicutils.js
- js/widgets/pitchtimematrix.js
Changed label to icons as per #1806
> Add note labels

- js/widgets/musickeyboard.js
Edit Pitch and Hertz value from table inside musical keyboard.
Also contains fix for two small bugs - 
One because of which hertz value was not store correctly
Second, a small check added for exit condition.
> Edit pitch value function for musical keyboard

- js/widgets/musickeyboard.js
Fix of bug that was not registering a click on key on top corner
> Keyboard key top corner click fix

- js/widgets/musickeyboard.js
Now the duration does not disappear if no note is played during that time. In export blocks and play function silence block and silence(no note played) is added.
> Silence duration and block added

- js/widgets/musickeyboard.js
Include bug fix for black keys and clear button along with advanced mode.
> Advanced mode and other bug fix for Musical Keyboard

- js/widgets/musickeyboard.js
> use object notation instead of array #1862

- planet/js/GlobalTag.js
> Add TRANS messages to Planet strings

- js/turtledefs.js
> Improve 'Run block' docs

- js/widgets/musickeyboard.js
- po/MusicBlocks.pot
Changes for just the music keyboard widget.
@walterbender I eagerly await your feedback.
> Show alert when a new action is generated for the music keyboard

- js/activity.js
- js/languagebox.js
#1892 
makes the prompt that appears after changing language/beginner or advanced mode a clickable button that refreshes the browser when clicked
> add refresh buttons

- js/README.md
> typo in readme

- js/activity.js
- planet/js/ProjectStorage.js
Fixes #1896, but I couldn't mimic the issues in #1897 so I implemented a little failsafe to catch errors anyway.
> Catch error when localStorage runs out

- css/activities.css
- dist/css/windows.css
- index.html
- js/activity.js
- js/widgets/rhythmruler.js
- js/widgets/widgetWindows.js
Same deal as before. Hopefully this PR is a little simpler to test as it makes use of the same windowing boilerplate laid out in the previous PR.
> Convert Rhythm Ruler to use widget windows

- css/activities.css
- dist/css/windows.css
- index.html
- js/widgets/pitchslider.js
Title says it all. Next one in the stream of commits.
> Port pitch slider to widget windows

- dist/css/windows.css
- js/activity.js
- js/widgets/pitchstaircase.js
- js/widgets/widgetWindows.js
Same deal as the others. I think everything should be working as previously.
> Port pitch staircase to widget windows

- dist/css/windows.css
- js/widgets/tempo.js
- js/widgets/widgetWindows.js
Same deal as usual. Switched to widget windows and removed dependency on IDs.
> Refactor tempo widget to use widget windows

- js/block.js
A sound preview should be heard when the user clicks on hertz block's pie menu. Let me know what you think!
> Sound Preview for Hertz Block's Pie Menu

- js/block.js
Like the Solfege pitch block, the scale degree pie menu should automatically increase the octave value when passing from Do to Ti and decrease it when passing from Ti to Do. This should address issue #1902
> Modify Octave Value For Scale Degree Pie Menu

- js/widgets/pitchtimematrix.js
1. changed word "add" to "duplicate"
2. changed menu wheel size to accommodate the word "duplicate"
> fixes #1933

- js/block.js
- js/blocks.js
Pitch Slider's widget window can now re-initialize when user changes label and/or blocks:
> Re-init Pitch Slider Widget Window

- js/block.js
- js/blocks.js
Pitch Staircase should now be able to re-init:
> Re-init Pitch Staircase Widget Windows

- js/basicblocks.js
Changes note counter to sum note values in `js/basicblocks.js` line 1526.
> fixes #1891 

- js/widgets/pitchdrummatrix.js
- js/widgets/pitchstaircase.js
- js/widgets/temperament.js
> #fixes 2018 Alert message added to remaining of the widgets

- index.html
> Fixes Issue #1735

- css/activities.css
- js/block.js
- js/blocks.js
- js/widgets/musickeyboard.js
- js/widgets/widgetWindows.js
Music Keyboard should now adhere to widget windows design:
Re-init functionality is also added.
> Refactor Music Keyboard + Re-init Functionality

- js/block.js
- js/blocks.js
- js/widgets/meterwidget.js
Meter WIdget should now be refactored to the widget windows design:
> Refactor Meter Widget to widget windows + Reinit Functionality

- js/README.md
> typos/nitpicks in js/README.md about internal block format

- js/activity.js
> Musicblocks doesn't go into infinite loading animation on dropping files

- documentation/README.md
I tried to remove broken links and updated them with  correct links.
> Fixes 2072 updated broken links in documentation/README.md

- js/activity.js
> Fix Make Block From Search Regression

- js/blocks/ActionBlocks.js
- js/blocks/BooleanBlocks.js
- js/blocks/BoxesBlocks.js
- js/blocks/DrumBlocks.js
- js/blocks/EnsembleBlocks.js
- js/blocks/ExtrasBlocks.js
- js/blocks/FlowBlocks.js
- js/blocks/GraphicsBlocks.js
- js/blocks/HeapBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/MediaBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/NumberBlocks.js
- js/blocks/OrnamentBlocks.js
- js/blocks/PenBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/RhythmBlocks.js
- js/blocks/SensorsBlocks.js
- js/blocks/ToneBlocks.js
- js/blocks/VolumeBlocks.js
- js/blocks/WidgetBlocks.js
- js/protoblocks.js
- js/turtledefs.js
One type error I am getting here.
> added field to block form for beginner mode

- index.html
- js/toolbar.js
@walterbender Please see this PR . I have added 'save-html' and 'save-png' in beginner mode .
> fixes #1948 attempt to save artwork in beginner mode

- dist/css/windows.css
> #fixes 2099 title issue resolved

- js/artwork.js
> Hover animation is working correctly

- js/widgets/help.js
> Fixed help modal position

- css/keyboard.css
- css/style.css
Some files in the **css** directory were lacking proper indentation. Through this Pull Request i have added the required indentation.
Please review this :)
> added identation in code

- js/block.js
> Error message displaying on decreasing note value below 0

- js/widgets/help.js
Fixed a minor typo in comments
> fixed typo

- js/mxml.js
@walterbender @AndreaGon This is an attempt to fix #2119 .Please review this PR .
>  fix  #2119 double barline at end of each voice

- js/widgets/help.js
- js/widgets/widgetWindows.js
> Hardwired position parameters for help div

- js/lilypond.js
> improve readability

- plugins/README.md
> fix official app repository link in plugin readme

- js/turtle.js
Made a global canvas that stores (or "remembers") previously written canvas,graphics  .the size of global canvas is limited --(3*canvas.height x 3 *canvas.width)
> scroll-xy limited_canvas_implementation

- js/widgets/pitchdrummatrix.js
@walterbender  In this PR, I have tried to solve issue #2160 .
I  removed two lines which are causing error.
> removed error causing lines

- guide/README.md
> user manual updated

- js/widgets/help.js
> BGcolor extended

- js/turtle.js
#2143  
changed doforward function :
walks every stepUnit(10) and analyses new position ..
> wrap canvas for (forward & back)

- images/gray.svg
- js/block.js
I've removed the trailing slightly visible rectangle background.
Also, the close button of the wheel was represented by "X". I've replaced all such occurrences by "×" (times) symbol.
> Improve appearance of Wheel Menu

- js/widgets/pitchtimematrix.js
> Fix re-sorting issue

- planet/js/GlobalCard.js
> Conditional rendering of like button tooltip in planet

- js/widgets/musickeyboard.js
> fixed grid for Music blocks

- js/activity.js
#2174 close all wheelnavs and labels when scrolling
> fix issue #2174 

- index.html
Music blocks still uses var where let should be used, made change to one file (/index.html), would like to expand if acceptable.
> minor refactor, var to let in index.html

- js/artwork.js
- js/turtledefs.js
- Add a help entry for the newly added wrap button.
> Add wrap button help entry

- js/logo.js
- js/widgets/pitchtimematrix.js
I've converted the `_blockMap` array into a dictionary structure, where the keys are block IDs of the respective phrase maker "matrix" blocks.
Fixes #2202.
> Convert block map into dictionary structure

- js/blocks/FlowBlocks.js
Fixes #2214. A little variable scope mistake.
> Fix broken duplicate block issue

- js/blocks/SensorsBlocks.js
Fixes #2200. It is a very simple fix. The `hasKeyboard` class was being removed from `textLabel` (line: 60) rather than `labelDiv`. Took me an hour to find that though :p.
> Fix issue of broken keyboard after input block

- js/widgets/widgetWindows.js
This is an attempt to close #2126
> Added scroll Feature to widgetWindows

- js/blocks/PitchBlocks.js
> fix set pitch number offset block argument type

- js/utils/synthutils.js
- js/utils/utils.js
synthutils and utils both files are done in this PR.
> let in utils 1

- js/utils/synthutils.js
Queued changes mentioned in #2226.
> Changed let to const in synthutils

- js/utils/synthutils.js
this issue was restricted to built_in synths - sawtooth ,sine .. ,because their synth had one of the properties wrong 
refer -
https://tonejs.github.io/docs/13.8.25/Envelope
> attempt to fix #1973

- js/blocks/DrumBlocks.js
- js/blocks/EnsembleBlocks.js
- js/blocks/ExtrasBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/SensorsBlocks.js
With these changes, all `var` within `js/blocks` are ported.
@aviral243 @vaibhavdaren could you review these? There's a portion in `DrumBlocks.js` that I've commented out because the calculated variable isn't used.
> Complete var to let refactor in js/blocks

- js/widgets/help.js
- js/widgets/meterwidget.js
- js/widgets/modewidget.js
> let instead of var for widgets

- js/blocks/PitchBlocks.js
Yet another `var` `let` issue.
> Fix broken _playPitch

- js/blocks.js
#1873 
adds last octave value and note name when removed
> Add default note and octave blocks

- js/turtle.js
changed doforward to use incremental increase method only when needed.
> doForward for small steps

- js/blocks/PitchBlocks.js
> Define a macro for pitch offset block

- js/blocks/BoxesBlocks.js
> Add store in box to beginner mode

- js/activity.js
- js/turtle.js
Bug caused by `deltaY` named as `deltaYfunction`
> Fix function name

- js/widgets/musickeyboard.js
adds set instrument blocks when saved in musickeyboard .
wraps around groups of notes with same voice .
#1860
> add instrument compatibility

- js/activity.js
- js/logo.js
- js/turtle.js
- js/utils/utils.js
I've rearranged the functions to maintain read consistency, renamed a few. Also, added comments and documentation.
I also moved the `_makeTurtleBitmap` from `Turtles` to `Turtle`.
> Rearrangement and refactor in turtle.js

- js/blocks/ActionBlocks.js
#2254 
"temperament1" block was not setup.
> setup Temperament1Block

- js/turtle.js
- js/turtles.js
- js/utils/utils.js
> Port Turtle component to MVC

- js/block.js
- js/blocks/EnsembleBlocks.js
- js/turtle.js
- js/turtles.js
- Moved variables appropriately to `model` or `view`
- Added `setters` and `getters` for `inter class` access
Clear after #2313.
> Turtle variable access reworked

- guide/README.md
- guide/index.html
- js/blocks.js
- js/blocks/BoxesBlocks.js
#2310 
I wasn't sure how to change .po files , can I do a simple search and replace ?
> removed space from "box 1" and "box 2"

- js/logo.js
Fixes #2323.
My bad. I'd deleted a line by mistake.
> Fix regression in backward

- js/blocks/SensorsBlocks.js
- js/turtles.js
new Sensor Blocks : MouseUp, MouseDown , MouseOut and MouseOver
> Add new Sensor Blocks

- js/block.js
- js/blocks/NumberBlocks.js
- js/blocks/PitchBlocks.js
- `nthmodalpitch : `  Round float arguments to the nearest integer. 
Implemented the same behavior for the pie-menu i.e. navigate to nearest integer if since it'll crash if the value is non-integer.
- `int : ` Round float arguments in the same behavior.
- #2319
> Floor argument of certain blocks

- js/blocks/SensorsBlocks.js
- js/turtles.js
change blockNames and eventnames
sorry for previous PRs(#2331 ) , I keep forgetting to change branches .
> change sensorNames : mouse => cursor

- js/block.js
- js/blocks/RhythmBlocks.js
#2347 
that.pause() function isn't defined inside block.js , which seemingly never gets called inside the createCache loop . I Have changed it to the delay Promise from utils.js
> Temperament fix 

- js/blocks/FlowBlocks.js
> repeat 0 -> skip

- js/SaveInterface.js
- js/abc.js
- js/activity.js
- js/blocks/ActionBlocks.js
- js/blocks/ExtrasBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/OrnamentBlocks.js
- js/blocks/RhythmBlocks.js
- js/blocks/ToneBlocks.js
- js/blocks/VolumeBlocks.js
- js/lilypond.js
- js/logo.js
- js/mxml.js
- js/notation.js
- js/note.js
- js/widgets/meterwidget.js
- js/widgets/musickeyboard.js
- js/widgets/pitchdrummatrix.js
- js/widgets/pitchtimematrix.js
- js/widgets/rhythmruler.js
.. touches quite a few files :p
Created a new class called `Notation` in a new file `notation.js`. Instantiated it from within `Logo`, then used that `object` to address all members (which were previously in `Logo`).
Broke the `updateNotation` method into two parts: one remains in `Logo`, the rest of it have been moved to `doUpdateNotation` inside `Notation`.
> Port out notation related members to another file (with Notation class)

- js/blocks.js
Accidentally committed this development code used for generating SVG. Reverting back.
> Warning on removing last start block

- js/blocks/NumberBlocks.js
- js/utils/mathutils.js
- Fixed regression bug due to `_doMinus`
- Ported mathematical behavior of `abs`, `int`, and `neg` blocks to `MathUtility`
> Fix regression due to _doMinus

- js/block.js
- js/blocks.js
#2373 
new block type for -- "notecounter" , "measureintervalscalar" , "measureintervalsemitones" ;
> Attempt to fix #2373

- js/activity.js
- js/blocks/MediaBlocks.js
- js/logo.js
- js/turtle-painter.js
- js/turtle.js
- js/turtles.js
- rename `SCALEFACTOR` constant
- break `add` method (`turtles.js`)
- new `setters`/`getters` syntax
There are a few things overlapping with `Logo` which I'll visit later.
> More refactor of Turtles to MVC and ES6

- js/block.js
- js/protoblocks.js
fix for issue mentioned in https://github.com/sugarlabs/musicblocks/pull/2377#issuecomment-650201910
> noteCounter Fix

- js/blocks.js
- js/blocks/MeterBlocks.js
- js/logo.js
using setInterval to dispatch actions in a companion turtle. 
-new turtle (if not made already ) gets initialized when first run ... (for the action block corner Case).
-currently only works for 4:4 time , but that shouldn't be a problem .
-----
> Every Beat 

- js/activity.js
- js/block.js
- js/blocks.js
- js/blocks/PitchBlocks.js
- js/logo.js
- js/note.js
- js/utils/musicutils.js
- js/utils/synthutils.js
- js/widgets/pitchtimematrix.js
- js/widgets/temperament.js
this should solve the bugs in #2350 and #2349
> Temperament enhancements

- js/blocks/IntervalsBlocks.js
> Remove verbose interval macros

- js/README.md
- js/activity.js
- js/block.js
- js/blocks/ActionBlocks.js
- js/blocks/DrumBlocks.js
- js/blocks/EnsembleBlocks.js
- js/blocks/ExtrasBlocks.js
- js/blocks/FlowBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/OrnamentBlocks.js
- js/blocks/PenBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/RhythmBlocks.js
- js/blocks/SensorsBlocks.js
- js/blocks/ToneBlocks.js
- js/blocks/VolumeBlocks.js
- js/blocks/WidgetBlocks.js
- js/logo.js
- js/note.js
- js/turtles.js
Some more refactoring w.r.t. `logo.js`.
> Rework Logo

- js/blocks/NumberBlocks.js
- js/blocks/PitchBlocks.js
- js/utils/mathutils.js
> Re-designed working of random with solfege

- js/block.js
- js/blocks/BoxesBlocks.js
- js/blocks/DrumBlocks.js
- js/blocks/EnsembleBlocks.js
- js/blocks/ExtrasBlocks.js
- js/blocks/GraphicsBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/MediaBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/NumberBlocks.js
- js/blocks/OrnamentBlocks.js
- js/blocks/PenBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/RhythmBlocks.js
- js/blocks/ToneBlocks.js
- js/logo.js
- js/turtle-singer.js
- js/turtles.js
- js/widgets/meterwidget.js
- js/widgets/pitchdrummatrix.js
- js/widgets/pitchtimematrix.js
- js/widgets/rhythmruler.js
- js/widgets/status.js
- js/widgets/temperament.js
- js/widgets/timbre.js
- `scalarTransposition`
- `scalarTranspositionValues`
- `transposition`
- `transpositionValues`
- `masterBPM`
- `defaultBPMFactor`
- `register`
- `beatFactor`
- `dotCount`
- `noteBeat`
- `noteValue`
- `noteDrums`
- `notePitches`
- `noteOctaves`
- `noteCents`
- `noteHertz`
- `noteBeatValues`
- `embeddedGraphics`
- `lastNotePlayed`
- `lastPitchPlayed`
- `previousNotePlayed`
- `noteStatus`
- `noteDirection`
- `pitchNumberOffset`
- `currentOctave`
- `currentCalculatedOctave`
- `inHarmonic`
- `partials`
- `inNeighbor`
- `neighborStepPitch`
- `neighborNoteValue`
- `inDefineMode`
- `defineMode`
- `notesPlayed`
- `whichNoteToCount`
- `moveable`
- `dispatchFactor`
> Port music state variables

- js/activity.js
currently we cant open new html files from planet.
> Fix "Open file" button in planet

- js/SaveInterface.js
- js/blocks/ActionBlocks.js
- js/blocks/DrumBlocks.js
- js/blocks/EnsembleBlocks.js
- js/blocks/ExtrasBlocks.js
- js/blocks/FlowBlocks.js
- js/blocks/GraphicsBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/MediaBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/OrnamentBlocks.js
- js/blocks/PenBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/RhythmBlocks.js
- js/blocks/ToneBlocks.js
- js/blocks/VolumeBlocks.js
- js/blocks/WidgetBlocks.js
- js/logo.js
- js/turtle-painter.js
- js/turtle-singer.js
- js/turtle.js
- js/widgets/timbre.js
- `vibratoIntensity`
- `vibratoRate`
- `distortionAmount`
- `tremoloFrequency`
- `tremoloDepth`
- `rate`
- `octaves`
- `baseFrequency`
- `chorusRate`
- `delayTime`
- `chorusDepth`
- `neighborArgNote1`
- `neighborArgNote2`
- `neighborArgBeat`
- `neighborArgCurrentBeat`
- `justCounting`
- `justMeasuring`
- `firstPitch`
- `lastPitch`
- `suppressOutput`
- `cp1x`
- `cp1y`
- `cp2x`
- `cp2y`
- `parentFlowQueue`
- `unhighlightQueue`
- `parameterQueue`
- `endOfClampSignals`
- `butNotThese`
- `delayTimeout`
- `delayParameters`
- `bpm`
- `previousTurtleTime`
- `turtleTime`
- `pushedNote`
- `tie`
- `tieNotePitches`
- `tieNoteExtras`
- `tieCarryOver`
- `tieFirstDrums`
- `synthVolume`
- `drift`
- `drumStyle`
- `voices`
- `backward`
> Transport measuring and effects related variables to Singer

- js/block.js
- js/blocks/DrumBlocks.js
- js/blocks/FlowBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/OrnamentBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/RhythmBlocks.js
- js/blocks/ToneBlocks.js
- js/blocks/VolumeBlocks.js
- js/logo.js
- js/notation.js
- js/turtle-singer.js
- js/widgets/pitchtimematrix.js
- `duplicateFactor`
- `inDuplicate`
- `skipFactor`
- `skipIndex`
- `instrumentNames`
- `inCrescendo`
- `crescendoDelta`
- `crescendoInitialVolume`
- `intervals`
- `semitoneIntervals`
- `staccato`
- `glide`
- `glideOverride`
- `swing`
- `swingTarget`
- `swingCarryOver`
> Transport Remaining music state variables to Singer

- js/abc.js
- js/blocks/DrumBlocks.js
- js/blocks/EnsembleBlocks.js
- js/blocks/ExtrasBlocks.js
- js/blocks/FlowBlocks.js
- js/blocks/GraphicsBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/MediaBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/PenBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/RhythmBlocks.js
- js/blocks/SensorsBlocks.js
- js/blocks/ToneBlocks.js
- js/logo.js
- js/notation.js
- js/turtle-singer.js
- js/turtle.js
- js/widgets/modewidget.js
- js/widgets/musickeyboard.js
- js/widgets/pitchdrummatrix.js
- js/widgets/pitchstaircase.js
- js/widgets/pitchtimematrix.js
- js/widgets/status.js
- `embeddedGraphicsFinished`
- `inNoteBlock`
- `multipleVoices`
- `invertList`
- `beatList`
- `factorList`
- `keySignature`
- `inSetTimbre`
- `pitchDrumTable`
- `defaultStrongBeats`
- `pickup`
- `beatsPerMeasure`
- `noteValuePerBeat`
- `currentBeat`
- `currentMeasure`
> Transport remaining Turtle/Music state variables to Turtle/Singer

- js/block.js
- js/palette.js
- js/utils/utils.js
this feature was mistakenly removed in a fix related to #1984.
> right click save stack

- js/blocks/PitchBlocks.js
> Move scale degree logic to its arg func.

- po/ja-kana.po
- po/ja.po
Requested updates to Japanese.
> Updates to JA po files

- js/blocks/ToneBlocks.js
- js/blocks/VolumeBlocks.js
- js/turtle-singer.js
- js/utils/synthutils.js
#1454
used .linearRampToValueAtTime signal to increase volume
for more info : developer.mozilla.org/en-US/docs/Web/API/AudioParam/linearRampToValueAtTime
older pr: #2413
> Crescendo "within a note"

- js/activity.js
#1463 
I tested with
android + chrome
win10 + chrome/Firefox and
ubuntu + chrome/Firefox
> normalize scroll speed across browsers

- js/blocks/VolumeBlocks.js
- js/turtle-singer.js
panning for each turtle.singer in range (-100(left) to +100(right))
:: #604
> PanningBlock

- js/activity.js
- js/block.js
- js/blocks.js
#855
Drag to edge of screen should scroll page.
> scroll when block "dragged to edges"

- js/activity.js
- js/blocks/WidgetBlocks.js
- js/widgets/oscilloscope.js
- js/widgets/widgetWindows.js
#2444
you need to choose the turtle from the top left dropdown menu ... default set to to turtle 0 ;
image
then play particular start block in background.
4 buttons :
up/down - vertical offset changes.
zoom in zoom out - horizontal scaling.
> oscilloscope widget

- js/activity.js
- js/block.js
pie menu for pan block => [ -100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100]
> Pie menu for panBlock

- package-lock.json
- package.json
The Package.json file previously did not contain fields such as "name" and "version" required from the npm documentation
> Update package.json  to have fields required from the npm docs

- js/blocks/MeterBlocks.js
- js/turtle-singer.js
#1891 
(notecounterblock2) : counts notes
(notecounterblock) : counts  notevalues
we would have to change documentation for these blocks.
>  new Note counter block

- js/activity.js
- js/blocks/OrnamentBlocks.js
- js/turtleactions/OrnamentActions.js
- js/turtles.js
- `staccato`
- `slur`
- `neighbor`
> Ornament actions port

- js/activity.js
- js/blocks/VolumeBlocks.js
- js/turtle-singer.js
- js/turtleactions/VolumeActions.js
- js/turtles.js
- `crescendo`
- `decrescendo`
- `set relative volume`
- `set master volume`
- `set panning`
- `set synth volume`
- `synth volume`
- `master volume`
> Volume actions port

- js/activity.js
- js/blocks/DrumBlocks.js
- js/turtleactions/DrumActions.js
- js/turtles.js
- `playDrum`
- `setDrum`
- `map pitch to drum`
- `play noise`
> Drum actions port

- js/activity.js
- js/blocks/ToneBlocks.js
- js/turtleactions/ToneActions.js
- js/turtles.js
- `set instrument`
- `vibrato`
- `chorus`
- `phaser`
- `tremolo`
- `distortion`
- `harmonic`
- `FMSynth`
- `AMSynth`
- `DuoSynth`
> Tone actions port

- css/activities.css
- index.html
- js/block.js
> Attempt at pitch preview bug fixes

- js/logo.js
#2474
Auto-open oscilloscope on play(same as status).
> AutoOpen Oscilloscope 

- js/blocks.js
- js/blocks/ExtrasBlocks.js
use print block for grids #2494
> use printblock for Grids

- js/activity.js
- js/blocks/IntervalsBlocks.js
- js/turtle-singer.js
- js/turtleactions/IntervalsActions.js
- js/turtles.js
- `set key`
- `get current key`
- `get current mode`
- `get mode length`
- `moveable do`
- `define mode`
- `scalar interval`
- `semitone interval`
- `set temperament`
**skipped:**
- `scalar interval measure`
- `semitone interval measure`
- `doubly`
> Intervals actions port

- js/js-export/export.js
- js/js-export/sample.js
- js/turtle-singer.js
- js/widgets/jseditor.js
- fixed bug: multiple mice don't run properly
- fixed bug: extra turtles generated stay on screen after program is over
> Fix multiple mouse in JS Editor

- js/block.js
- js/blocks/PitchBlocks.js
> Octave calc. fix for scale degree

- css/activities.css
- js/activity.js
- js/palette.js
https://github.com/sugarlabs/musicblocks/issues/2420#issuecomment-670501118
@pikurasa  please test this 
we can also format the search options (font style /size)
> use images in search

- js/palette.js
#2527 
added extra space for grabbing in palette and toggle cursor to "grabbing" when scrolling
> extra space in palette

- js/activity.js
- js/blocks/MeterBlocks.js
- js/js-export/MeterBlocksAPI.js
- js/js-export/ToneBlocksAPI.js
- js/js-export/export.js
- js/turtleactions/MeterActions.js
- js/turtles.js
- `set meter`
- `pickup`
- `set BPM`
- `set master BPM`
- `on every note do`
- `on every beat do`
- `on strong beat do`
- `on weak beat do`
- `no clock`
- `notes played`
- `whole notes played`
- `beat count`
- `measure count`
- `BPM`
- `beat factor`
- `current meter`
> Meter actions port

- js/SaveInterface.js
https://github.com/sugarlabs/musicblocks/issues/1118#issuecomment-371971282
> add Message when recording

- index.html
- js/activity.js
- js/block.js
- js/utils/musicutils.js
- Fixes #2481 ( Primarily bugs related G# and C# major and any other auto-selection issue that might have gone unnoticed)
> Reworked process of accidental selection

- js/utils/musicutils.js
#2499 Cb now works in the _buildScale, and the error doesn't show anymore.
> Fix Cb scale in _buildScale

- js/blocks/PitchBlocks.js
- js/blocks/WidgetBlocks.js
- js/turtle-singer.js
#2533 (fix to 3 decimal places) and
Action Block support for Phrase Maker #2483
> Phrase Matrix Bugs

- js/blocks/NumberBlocks.js
- js/blocks/PitchBlocks.js
- Plus block combinations work with scale degree. 
- Goes beyond range(1-7) and adjusts octave accordingly. ( Behaviour similar to nthmodalpitch)
- #2396 for more details.
> Plus block with SD

- README.md
- js/blocks/ActionBlocks.js
- js/logo.js
fixes #2549.
careless loop implementation. my bad
fixed names in README :p
> Fix backward block playing action block twice

- po/ja-kana.po
- po/ja.po
Please let me know if there is anything I missed.
> Updates to Japanese

- css/activities.css
- dist/css/windows.css
- js/widgets/musickeyboard.js
- js/widgets/widgetWindows.js
The "The grid does not fill the available space." issue described in #2568
> fixes issues of #2568 

- documentation/README.md
> Fixes the readme discrepancy.

- po/ja-kana.po
- po/ja.po
> Updates to JA files (Dictionary and other new)

- js/activity.js
- planet/js/ProjectViewer.js
An attempt to fix the issue #2584 , 
Upon testing the code with and without the code I have added in this commit the `open in music blocks button` generates erratic behavior(_I think it's an issue with my PC_) as follows; however, i think, the commit in this PR will fix the issue.
Looking forward to hearing from you @walterbender
> Fix for showing project title, when project loaded from planet.

- android_chrome_manifest.json
- index.html
- manifest.json
Fixes #2607 
1. Edited icons array in _manifest.json_ and _android_chrome_manifest.json_
2. Added following line in index.html to add apple device support
`<link rel="apple-touch-icon" href="/activity/activity-icon-color-512.png">`
> Making app pwa ready

- js/widgets/oscilloscope.js
> Oscilloscope running even after stop fix

- planet/css/style.css
- planet/index.html
- planet/js/GlobalCard.js
- planet/js/ProjectViewer.js
- planet/js/StringHelper.js
Fixes #2617 
Tasks:
Reviewers:
@walterbender 
@pikurasa
> Adding merge and open button in global card

- js/widgets/timbre.js
> Timbre UI fix

- planet/css/style.css
- planet/index.html
before
.
.
Please review this sir, @walterbender #2616
> Global card css fix

- js/block.js
@meganindya Sir,I have changed callbacks,settimeout and some that to this where required.Should I change event listener functions also  .Please guide sir.
> callbacks->arrowfunction block.js

- README.md
> Update README.md with new contributing guidelines

- planet/js/GlobalCard.js
> callbacks -> arrow function "planet/js/GlobalCard.js"

- planet/js/GlobalPlanet.js
> Callbacks  -> arrow function "planet/js/globalplanet.js"

- planet/js/GlobalTag.js
> Callbacks -> arrow function "planet/js/GlobalTag.js"

- js/block.js
> drumlabels error fix

- js/blocks/IntervalsBlocks.js
- js/blocks/WidgetBlocks.js
- js/logo.js
- js/piemenus.js
- js/widgets/meterwidget.js
- js/widgets/modewidget.js
- js/widgets/musickeyboard.js
- js/widgets/pitchdrummatrix.js
- js/widgets/temperament.js
- js/widgets/timbre.js
part of issue #2629 , also part of #2594 ,solves for `modeWidget`
@meganindya
> widgets/modewidget - port to es6 and removes redundant logo/turtles

- js/palette.js
> Improve palette styling

- documentation/oscilloscope_block.svg
part of issue :- #2711 
Oscilloscope help widget new behavior:-
> Help widget erratic behavior fix

- documentation/notecounter2_block.svg
> Help widget note counter

- .eslintrc.json
- js/activity.js
- js/blocks/DrumBlocks.js
- js/blocks/GraphicsBlocks.js
- js/blocks/PenBlocks.js
- js/blocks/PitchBlocks.js
- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/WidgetBlocks.js
- js/logo.js
- js/turtle-singer.js
- js/turtleactions/PitchActions.js
- js/turtleactions/ToneActions.js
- js/utils/utils.js
- js/widgets/phrasemaker.js
Part of issue #2629  and #2594
> widgets/phrasemaker - port to es6 and removes redundant logo/turtles

- js/activity.js
> Fixed the search row to hide search button when clicked again

- js/widgets/widgetWindows.js
> Add class to widgets/widgetWindows.js

- js/blocks/WidgetBlocks.js
- js/widgets/oscilloscope.js
> Add class to oscilloscope.js

- planet/js/LocalCard.js
Fixes #2729 - Share button from projects under planet local removed
> planet/local - remove share

- planet/css/style.css
> planet global share box css fix

- js/widgets/musickeyboard.js
> Music keyboard - A# missing fix

- js/blocks/WidgetBlocks.js
- js/widgets/meterwidget.js
> adding ES6 classes to widgets/meterwidget.js

- js/widgets/pitchdrummatrix.js
@meganindya please review this. 
Fixex a part of #2629
> added class to js/widgets/pitchdrummatrix.js

- js/widgets/status.js
@meganindya  Please review this.Changed widgets/status.js to ES6 format.
> adding classes to widgets/status.js

- js/blocks/WidgetBlocks.js
- js/widgets/tempo.js
@meganindya  the work on this pr is also completed. So please review this also.With reference to issue #2629
> adding ES6 classes to widgets/tempo.js

- js/activity.js
- js/boundary.js
- js/trash.js
Issue reference:- #2629
files changed:- `js/trash.js`,`js/boundary.js`,`js/activity.js`
**The behavior after porting:-**
https://user-images.githubusercontent.com/50985033/104813805-7d137100-5831-11eb-8c1c-a818150d4119.mp4
**console output:-**
I didn't encounter any error while testing it post port, if I have missed something and there is an error produced because of this, please do share feedback, thanks.
> Trash.js port to Class

- js/widgets/oscilloscope.js
Issue Reference #2609, #2630, #2767
**The behavior after porting:-**
https://user-images.githubusercontent.com/50985033/105626590-85cdfd80-5e56-11eb-889a-56960d99bffd.mp4
> Oscilloscope lint-pretify and jsdoc

- js/widgets/pitchstaircase.js
> Refactor: widgets/pitchstaircase.js - lint, prettify and documentation

- js/widgets/timbre.js
> widgets/timbre.js JSDoc style comments 

- js/trash.js
Issue reference:- #2609 
Final finishing touches that were due for `trash.js` file have been made in this PR.
> Trash.js file JSDoc, Lint and Prettify 

- README.md
Corrected spelling errors in README.md files
> Corrected spelling errors and checked grammar of README.md

- js/blockfactory.js
Issue reference:- #2630 and #2609
> js/blockfactory.js JSDoc and ESLint

- documentation/wrap_block.svg
- js/blocks/GraphicsBlocks.js
- js/macros.js
> Help artwork for wrap block

- js/toolbar.js
Issue Reference: #2767, #2630, #2609
> toolbar.js: Prettify, Linting and JSDoc documentation

- js/logo.js
> refractor:js/logo.js

- js/basicblocks.js
Please review @meganindya, 
Thanks.
> basicblocks.js: Pretiffy,linting and JSDoc Documentation

- js/widgets/statistics.js
> widgets/statistics.js: Add JSDoc Documentation

- js/utils/mathutils.js
> refractor:utils/mathutils.js:linting

- js/blocks/DictBlocks.js
- js/turtleactions/DictActions.js
> turtleactions/DictActions.js: Linting and Prettify

- js/blockfactory.js
> blockfactory.js: Add global locations and constructor JSDoc

- js/lilypond.js
- po/ja-kana.po
Fixes part of #2842 
https://user-images.githubusercontent.com/39027928/107891540-4a01f180-6f45-11eb-9e61-8bfbd9085907.mov
Sometimes wrong lillypond code was getting exported by MusicBlocks. This issue did not present itself consistently and sometimes went away after refreshing the page a couple of times, the reason for the issue probably being the order in which things were defined and being loaded. This issue should have been present all along but only got noticed recently.
https://user-images.githubusercontent.com/39027928/107891571-859cbb80-6f45-11eb-8074-b4304e17e203.mov
> Fixing regression in lillypond

- js/utils/utils.js
Reference: #2850 
https://user-images.githubusercontent.com/39027928/108610624-20d9d900-73fd-11eb-8380-c014bd33f5b4.mov
@walterbender
> Fix: palletes for plugins not loading

- js/widgets/temperament.js
Reference #2867 
https://user-images.githubusercontent.com/39027928/110518184-cf865500-8131-11eb-8b7e-4b844e0860dc.mov
Please share feedback and suggestions.
@walterbender @pikurasa
> fixing cents wrt C only for higher frequencies in temperament stack with custom octave ratio

- js/piemenus.js
- js/utils/musicutils.js
- js/utils/synthutils.js
- js/widgets/temperament.js
Reference #2865 
https://user-images.githubusercontent.com/39027928/110400687-13c81580-809e-11eb-9115-3995e2961cf4.mov
Both pitch preview in piemenu and playback working as expected with the custom pitch names.
@walterbender
> Define temperament - custom pitch names

- js/widgets/oscilloscope.js
Ref #2808 
In the oscilloscope widget the graph takes up only a small portion of the screen in fullscreen mode and the extra space is not utilised in a meaningful manner. Even on zooming in, the graph zooms up over only the small portion of the screen taken up by the graph. Ideally, the graph should take up the total area available to the widget window in fullscreen mode. This would help us see the minute details in the graph easily.
Here is how it looks,
https://user-images.githubusercontent.com/39027928/111055942-f7aee480-84a0-11eb-841e-b78fc1a6e593.mov
https://user-images.githubusercontent.com/39027928/111055977-45c3e800-84a1-11eb-8f67-2e338cdd54e1.mov
Please share feedback and suggestions.
> Oscilloscope Widget: Enhancements to fullscreen mode

- README.md
I have added license and contribution shield images in readme file as suggested.
> Update in ReadMe file

- js/blocks.js
- js/blocks/ActionBlocks.js
Ref #2928 
Just like an action block is meaningless without the name of the action, A define temperament block is meaningless without the name of the temperament. 
https://user-images.githubusercontent.com/39027928/116192509-95a5f800-a74b-11eb-8854-a36753c9aa27.mov
> Persistent text block for define temperament

- js/turtleactions/ToneActions.js
- js/widgets/sampler.js
The sampler widget now has an oscilloscope for the reference tone and the sample.
> Add oscilloscope visualizer to sampler widget

- examples/README_1.md
I have added a file README_1.md to musicblocks/examples/ containing a table of statistics for some of the example songs. This is in coordination with pmccabe5's pull request [#2904](https://github.com/sugarlabs/musicblocks/pull/2904) as we are working on this issue together with our team.
> Added an example classification README_1.md to musicblocks/examples/

- js/blocks/NumberBlocks.js
Fixes #2939 
https://user-images.githubusercontent.com/60084414/118302928-773d4c00-b502-11eb-9d03-d7485e0f3d9c.mp4
Please review this and share your feedback. @walterbender @pikurasa 
Thanks.
> Fix: Concat text string inside a Note

- js/widgets/pitchdrummatrix.js
Attempted implementing an enhancement for the pitchdrum widget for full screen functionality.
Code changes made to the display, alignment, and flex direction in order to fix the scaling to full-screen.
Added code that changed the styles of the widget and the attributes within the scale function.
Feb 4 ticket #2808
> pitchdrum widget for full screen functionality

- guide/README.md
Add link from Music Blocks documentation to Turtle Blocks / Turtle Art documentation 
#2968
Please Take a Review and ping me if any recommendation.
Thanks
> Adding Link from Music Blocks documentation to Turtle Blocks

- dist/css/windows.css
- js/turtledefs.js
Fixes: #3008 
Changes, as mentioned in the issue, have been done as shown below.
> Fixes #3008 : Enhancing "take a tour" and "usage-guide" modal

- po/ja-kana.po
I've found some messages are not translated into Japanese, so send PR.
> Add Japanese messages in po/ja-kana.po

- index.html
**Chrome :-** 
**Firefox :-**
Closed #3049
> Cross origin errors removed 

- guide/README.md
Temporary Fix 
Changes yet to be done:-
1. reference link in svg not in guide folder
2. do same changes in other documentations
> Fixed errors

- guide-es/README.md
- js/README.md
changed svg link guide-es readme
> Other docx img link fix

- guide-ja/README.md
Fixed image links of guide-ja readme.md
> guide-ja img link readme file fixed

- documentation-es/README.md
- documentation/README.md
- guide-zhCN/README.md
**Fixed all the image link in readme files.**
**closes #3061**
> Camo img link in docx

- js/logo.js
The arg values need to be calculated inside the timeout.
> fixes #3082

- js/logo.js
> forgot print and show

- js/blocks/RhythmBlocks.js
- js/logo.js
- js/turtle-singer.js
- js/utils/synthutils.js
Notes inside of notes are played in the "future".
> fixes #3101

- README.md
> Anchor links of readme are fixed #3103

- js/blocks.js
- js/blocks/WidgetBlocks.js
- js/piemenus.js
- js/turtledefs.js
- js/utils/musicutils.js
- js/widgets/arpeggio.js
The i18n logic for chord names was failing. This work-around should be more robust in light of such failures.
> I18n chords

- js/piemenus.js
> fixes #2867

- documentation/intervalnumber_block.svg
- js/blocks/IntervalsBlocks.js
- js/rubrics.js
- js/turtleactions/IntervalsActions.js
issue https://github.com/sugarlabs/musicblocks/issues/2209#issue-596131323
Added a new interval number block
> Add a interval number block

- js/utils/musicutils.js
- js/utils/synthutils.js
- js/utils/utils.js
Changed existing function syntax to match ES6 arrow function syntax.
New to open source, apologies if I haven't followed all the guidelines.
> Fixes /js/utils in #2198

- js/utils/musicutils.js
There was a regression in #2537 where the double sharp Fx and double flat Bbb were not calculated properly.
> fix regression in double sharps/double flats

- js/piemenus.js
- js/utils/musicutils.js
- localization.ini
- po/es.po
Devin has provided definitions for some scalar chords.
> New chords

- js/widgets/arpeggio.js
- js/widgets/modewidget.js
- js/widgets/pitchdrummatrix.js
> Fixed #2198  modified some js/widgets/  files

- js/blocks/ActionBlocks.js
- js/blocks/FlowBlocks.js
- js/blocks/IntervalsBlocks.js
- js/blocks/MeterBlocks.js
- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/WidgetBlocks.js
Changed existing anonymous function syntax to match ES6 arrow function syntax
> Fixes js/blocks mentioned in #2198

- js/turtledefs.js
- js/widgets/help.js
> Left Arrow functionality corrected

- js/piemenus.js
- js/utils/musicutils.js
- js/widgets/temperament.js
* Fixes 2867 -- the pitch letters will wrap if the octave spacing > 2:1
* piemenu for custom notes no longer tries to cram multiple temperaments into one wheel for improved legibilty
* frequencyToNote doesn't round when calculating pitch letter -- leave that to the cents.
> 2867 octave space

- js/widgets/temperament.js
As per @Tallkite's suggestion, I moved the ^^ and vv to before the letter name.
> fixes #2859

- js/blocks/IntervalsBlocks.js
- localization.ini
- po/es.po
- po/ja-kana.po
- po/ja.po
> add help string for Interval Name block

- js/turtledefs.js
- js/widgets/help.js
* revert decision re help arrows (if the arrow is there, it should be active)
*  fix typo in version number changes -- malformed string
> fix regressions in help cards

- js/piemenus.js
- js/turtledefs.js
- js/widgets/help.js
The selector was placing the display text value in the block value, which was breaking lots of things. Not sure how this could have ever worked.
> Piemenu regression ja

- planet/js/LocalCard.js
Closes https://github.com/sugarlabs/musicblocks/issues/3171
This happened due to data binding issue on input event for name.  Fixed by providing the correct value from the event.
> Fixed card name lost when switching to detail view

- guide/README.md
- js/activity.js
- js/artwork.js
- js/basicblocks.js
- js/block.js
- js/blocks/PitchBlocks.js
- js/lilypond.js
- js/macros.js
- js/palette.js
- js/protoblocks.js
- js/rubrics.js
- js/turtledefs.js
- js/utils/musicutils.js
- localization.ini
- po/es.po
- po/ja-kana.po
- po/ja.po
We have a letter class but not way to convert to letter with accidental...
> letter with accidental

- js/blocks/PitchBlocks.js
- js/utils/musicutils.js
We support passing a pitch number in the pitch block but not a pitch number with an accidental.
> Add support for pitch expressed as a number with an accidental

- planet/index.html
> Fix Dropdown overlap issue #3166

- js/activity.js
I notice the search widget  is  generating behind the palette so I fixed it
> fixed the searchWidget generating behind the palette

- js/macros.js
- js/palette.js
Marcos were jumping away from the mouse.
> more corner cases for positioning blocks created from palette

- planet/css/style.css
- planet/js/GlobalPlanet.js
- planet/js/GlobalTag.js
- planet/js/helper.js
RATIONALE: 
- First two commits contain the changes that are confined to the realm of upgradation. The code in the files was quite verbose. Now it has been upgraded to the ES6 syntax. 
- The Last commit contains the changes that enhance the UI of the global tag container. 
In both smaller and larger viewports, the container that envelops the global tags wasn't styled which consequentially caused the tags to appear cluttered.  So to make the container more appealing, some styles were added. 
BEFORE: 
AFTER: 
@walterbender  
Thanks in advance.
> Enhancement: Enrich the UI of the Global Tag-Container

- js/activity.js
fixed the regression with screen size 
issue #3225
https://github.com/sugarlabs/musicblocks/issues/3225
@walterbender kindly check this out
> fixed issue - regression with screen size #3225

- js/activity.js
- js/palette.js
@walterbender updated search bar with a horizontal blue line.
It now looks like : 
**Please review it.**
> enhanced search box

- css/activities.css
- js/widgets/help.js
in Firefox as well as chrome it is working properly,  #3229
> Responsiveness for the Take a tour column  ( Issue #3229)

- planet/js/GlobalPlanet.js
- planet/js/Planet.js
RATIONALE : 
- The Constructor Functions are now written in the Class format which is easy to comprehend 
- Individual commit encompasses the changes made in individual files (and thus individual constructor functions). 
@walterbender  Thanks :)
> Enhancement: Upgrade the files from Constructor function to ES6 class syntax 

- planet/js/GlobalCard.js
- planet/js/GlobalTag.js
- planet/js/LocalCard.js
- planet/js/LocalPlanet.js
- planet/js/ProjectViewer.js
- planet/js/Publisher.js
RATIONALE :
- The Constructor Functions are now written in the Class format which is easy to comprehend
- Individual commit encompasses the changes made in individual files (and thus individual constructor functions)
- The files changed are :  
ProjectViewer.js, GlobalCard.js, GlobalTag.js, LocalPlanet.js, Publisher.js, and LocalCard.js
> Enhancement: Upgrade constructor function to ES6 class syntax. 

- js/piemenus.js
For issue https://github.com/sugarlabs/musicblocks/issues/3294
It solves the console issues but I'm not sure if the desired output is correct.
on pressing the set preview button, now a sound will come
@pikurasa please test this branch
> solving console errors

- js/blocks/IntervalsBlocks.js
> Making scalarInterval into beginner mode

- js/blocks.js
- js/blocks/EnsembleBlocks.js
For issue #3301 After deleting the start block,  turtle list is reduced by 1
https://github.com/sugarlabs/musicblocks/assets/81846020/46e9471e-41cd-4294-87a1-fae43570c2b4
> Mouse count

- js/piemenus.js
> Making responsive pie menu for different screen sizes

- js/blocks/ExtrasBlocks.js
- js/trash.js
For #3331 
I also removed a function in the trash file. It was not necessary.
> Adding ExtraBlocks.js

- po/ar.po
**im a native Arabic speaker**, after testing the web app i have noticed that there are many missing Arabic words, this could make it difficult for children who only know their language.
Therefore, I made a few changes just for testing purposes, if these changes are accepted, i will be happy to translate the entire .po file ^^
> made a few translations in arabic

- js/activity.js
For Issue  #3289 
use white space for scrolling !!
> Making Scrolling of Canvas by using two fingers

- js/widgets/widgetWindows.js
Fixes #3345
Changes:
- Added some more condition checking
- Changes `this.close();` to `this.destroy();`
Closes: #3345
> Fixed Close Info Window

- css/activities.css
- js/toolbar.js
issue: #3362
when the hamburger icon is not clicked 
when the hamburger icon is clicked
> placed search bar at correct place

- README.md
Here is the correct fixed it should be purposes instead of purpoes or purpose
> fixed readme typo error 

- dist/css/windows.css
issue: #3364 
I have added the space between the two buttons
> added space between buttons in pphrase maker

- css/activities.css
issue: #3371 
I have already raised a PR for this but unfortunately, my repo got deleted due to an updation sorry for it
so, again I am raising a new PR
> Added_hovering_effect_on_pallet

- index.html
issue: #3388 
when we press the fullscreen mode button and then press the ESC button the fullscreen mode button again changes to the original form
> fullscreen_error_toggle_esc_button

- js/turtle-painter.js
- fixes #3352
https://github.com/sugarlabs/musicblocks/assets/77796540/9c6b641c-fc99-4699-b85d-63095e4188e6
> Defaults mice color to pink after cleanup

- po/te.po
@walterbender This will be useful for translation of languages and I have added all meaning full words 
I have translated all English words into Telugu 
Thank you
> complete-telugu-tramslation

- js/piemenus.js
issue: #3245
The words were coinciding now they are not @walterbender
Thank you
> pitch_preview_words

- js/turtledefs.js
issue : #3421 
I have added the extract, copy, delete, to the tour @walterbender 
Thank you
> Added-tour

- css/activities.css
here is attached correction issue #3423 
before
after
> fixes alignment of checkbox for pie menu

- planet/index.html
Fixed  hidden error of  incorrect use of label
> fix incorrect use of label

- js/utils/mathutils.js
Despite implementing a loop, the outcome remains unchanged.
> Fixes #3399 For loop does not change the outcome

- dist/css/windows.css
Fixes #3441
this PR fixes the inappropriate bottom corners of all the floating windows, javascript editor and widgets.
please review @walterbender sir
> fixes corners of floating windows

- css/activities.css
- js/blocks/EnsembleBlocks.js
- js/blocks/ToneBlocks.js
- js/widgets/help.js
issue: #3446 
I have added the images and removed the circular rotation on the tour so the user will not get confused as in code the tour is dived into parts with HELPCONTENT and blocks 
Thank you
> tour_changed

- js/widgets/jseditor.js
Fixes: #3450
This PR adds the tooltips for the icons in javascript editor, making it more accessible and UI friendly.
Uploading 2023-12-19 01-53-50.mp4…
Please review this PR @walterbender sir
> Feature: tooltips in jseditor

- planet/js/GlobalCard.js
> Fixed inconsistencies in Gloabl Card height

- js/blocks/IntervalsBlocks.js
- js/blocks/VolumeBlocks.js
There was a regression introduced in https://github.com/sugarlabs/musicblocks/commit/740fa7ae98519f1eeb3363e4850b8e4872ffe595 that causes some class definitions to be deleted. They are restored in this MR.
Also, there was a typo introduced in VolumeBlocks.js that is fixed.
> Fix interval blocks

- examples/README.md
add missing games; consolidate tables
> Update Examples README.md

- js/utils/synthutils.js
issue https://github.com/sugarlabs/musicblocks/issues/3484
> fix buffer not loading

- js/widgets/musickeyboard.js
> Action block into size of50 issue#3127

- js/widgets/phrasemaker.js
Fixes: #3291
This PR fixes the the issue of getting duplicate pitches in Phrase maker.
G Major
C Major
please review this PR @pikurasa sir , @walterbender sir
> Fix duplicate pitches in phrase maker

- js/activity.js
related to Issue:https://github.com/sugarlabs/musicblocks/issues/3508
being turned to async function even after clicking maximise scale/min scale if it takes 1 min to rescale and in that minute we click home function when resizing will be done it will be reflected in the page tested  this using delay function in async calls.
> async_function_conversion

- js/languagebox.js
- po/ar.po
- po/ayc.po
- po/es.po
- po/gug.po
- po/he.po
- po/hi.po
- po/ibo.po
- po/ja.po
- po/ko.po
- po/pt.po
- po/quz.po
- po/te.po
- po/th.po
- po/zh_CN.po
This Pr fixes #3514 
When User Clicks on enUK
PopUp Comes on the screen
> Warn user when language will not change

- lib/materialize-iso.css
- lib/materialize.min.css
- lib/sugar-web/graphics/css/sugar-200dpi.css
- lib/sugar-web/graphics/css/sugar-96dpi.css
- lib/sugar-web/graphics/css/sugar.less
- planet/fonts/material-icons.css
fixes #3497 
some other modification in use of standard property of css to ensures compatibility across different browsers.
> added standard property of css

- js/widgets/tempo.js
fixes #3528 
@walterbender  sir sorry i actually closed accidentally the previous PR after doing Rebase as i am new to open source.Please review this one
> Fix/Added_maximize button_tempo

- planet/index.html
fixes #3515
@walterbender  plz review it
> Fix:shortened the title of planet

- planet/index.html
Fix https://github.com/sugarlabs/musicblocks/issues/3515
Shortened the title of planet website
> Shortened title of planet

- js/widgets/help.js
This Pull Request aims to address issue #3451 of window size encountered by users after completing the tour in Music Blocks. The changes implemented here ensure that the window displaying block explanations post-tour is appropriate, enhancing the overall user experience.
https://github.com/sugarlabs/musicblocks/assets/88442916/b1974dd0-6291-4f47-83a3-ae4eb79ad572
>  Enhancement/Window size of blocks tour : Issue -  #3451

- script.js
fixes #3570 
The current DOM initialization lacks adequate error handling for `localStorage` usage. This issue aims to improve error handling mechanisms when accessing `localStorage` during the initialization process.
- Implement robust error checks around `localStorage` calls during DOM initialization.
- Provide fallbacks or alternative methods for scenarios where `localStorage` access fails.
- Strengthen the application's resilience by handling `localStorage` errors more effectively.
- Ensure a smoother initialization process, even if `localStorage` is unavailable or encounters errors.
1. Identify critical points where `localStorage` is utilized during DOM initialization.
2. Implement try-catch blocks or error handling mechanisms around `localStorage` calls.
3. Test scenarios involving …
> Enhance Error Handling for localStorage in DOM Initialization

- guide/index.html
Fixes: #3556
This PR updates the HTML file in the guide folder. Also, it fixes the problem of unloaded SVG files.
please review this @walterbender sir
> Update html file with readme file

- js/loader.js
#3581 
@walterbender please review this PR
>  Updated Copyright Year in Comments js/loader.js

- js/block.js
- js/piemenus.js
- fixes #3354
Also, any value outside the range is not allowed from Piemenu.
> limits pitch input value

- css/activities.css
- index.html
logo was missing but popover text was there (as shown in issue video)
this PR solves that
https://github.com/sugarlabs/musicblocks/assets/121949298/45472e63-a67b-4cc4-bba0-ecda98e8269b
Fixes #3591
> Fixes #3591 Musicblock logo was missing in navbar

- js/blocks.js
> update some for loops

- js/widgets/tempo.js
fixes #3597 
I have used isNaN function which checks if the input is a valid number. If it's not a valid number, an error message is displayed, and the function returns early.
> fixes block taking random input

- js/toolbar.js
JS editor is an advanced feature
> hide JS editor in beginner mode

- planet/js/StringHelper.js
fixes: #3546 
I Have added a if statement, if the elem exists then only it will proceed further.
> Resolve: Console Warning - Cannot read properties of Null

- js/activity.js
Fixes: #3607
This PR optimizes the code in `this._setupPaletteMenu` in activity.js by creation a single function to avoid code duplication, thereby optimizing the code for better performance.
please review this PR @walterbender sir
> optimize code using createButton fn in this._setupPaletteMenu

- js/activity.js
Fixes #https://github.com/sugarlabs/musicblocks/issues/3351
I have added '/' for left scrolling and '\' for right scrolling 
https://github.com/sugarlabs/musicblocks/assets/127110636/1790ecba-be84-4c8c-a013-dc6c9184ecca
> Horizontal_scroll_property

- js/logo.js
- js/turtle-painter.js
- Resolves #3392
The video of the provided project after fixes.
https://github.com/sugarlabs/musicblocks/assets/77796540/68294dd0-2fc6-4d16-9f97-d66f9c0a135d
> fixes: Discrepency with lines between with notes and no notes

- js/utils/mathutils.js
Added JSDoc Style Doc to utils/mathutils.js .
> Added JSDoc style doc to utils/mathutils.js

- js/block.js
Fixes: #3626
This PR sets the position of the cursor in text block and number block at the end 
https://github.com/sugarlabs/musicblocks/assets/109718740/7b58adfa-762c-4e66-86c3-a0e8533fd26f
please review this PR @walterbender sir
> Set cursor position to the end

- dist/css/windows.css
- js/widgets/help.js
- js/widgets/widgetWindows.js
This feature provides toggling of - and + icon in help window when we click it 
Earlier : If we minimise help window icon is shown - only but I thought to toggle it to plus when we need to maximise it again which provides aa good UX
Earlier:
https://github.com/sugarlabs/musicblocks/assets/127110636/58fa68ec-f59f-4364-8acb-3e72254ddd34
After feat addition:-
https://github.com/sugarlabs/musicblocks/assets/127110636/7ffc785b-3d4f-4eb2-87f6-e9fd79753a16
> Feature Addition in help window toggling of minimise icon.

- js/utils/mathutils.js
- js/utils/munsell.js
Added JSDoc style doc to utils/munsell.js .
> Added JSDoc style doc to utils/munsell.js

- js/widgets/temperament.js
fixes #3622 
I have used try catch.. The code inside the try block is the code that may potentially throw an exception (an error). If an exception occurs during the execution of the code inside the try block, it will be caught and handled in the catch block.
And also limits the number <999 and user will get error mssg as well .
> Limits no. of divisions and pitchnumber

- js/widgets/widgetWindows.js
Solves issue #3637 .
Video
https://github.com/sugarlabs/musicblocks/assets/105922142/b12a1915-8e81-4ece-8540-0871d6dc4a4c
@walterbender sir please review .
> "Resolvesbugesofwidgetwindow"

- planet/css/style.css
- planet/index.html
- planet/js/GlobalPlanet.js
This PR resolves Issue https://github.com/sugarlabs/musicblocks/issues/3640 as recommended by @walterbender we need two headers for small screen I have made changes according to the same and now everything works alright for small as well as large screen .Below is the video related to it:-
https://github.com/sugarlabs/musicblocks/assets/127110636/1199c5b8-0061-4933-8f2a-282770bac88b
> Two_headers

- js/activity.js
This Closes #3662
Added Shortcut Functionality for Ctrl+MouseWheel Up/Down for ZoomIn/Out Shortcut!
@walterbender Please Review this!
> Update activity.js - Added Ctrl+MouseWheel ZoomIn/Out Functionality

- js/utils/mathutils.js
- js/utils/munsell.js
- js/utils/musicutils.js
Added JSDoc style doc to utils/musicutils.js .
> Added JSDoc style doc to utils/musicutils.js

- planet/css/style.css
- planet/index.html
Addition of a new button functionality, enabling seamless navigation to the top from any point within the infinite scroll. 
Result:
https://github.com/sugarlabs/musicblocks/assets/61118650/bc1c904b-54b1-455d-8ac0-aaffbd5759c0
> Added Back to Top feature in Planet 

- planet/js/StringHelper.js
- planet/js/helper.js
> Fixes:Updated up and down arrow

- dist/css/style.css
- index.html
- js/turtles.js
Resolves Issue https://github.com/sugarlabs/musicblocks/issues/3665
I have added a confirm pop over when clear button is pressed and clear is only implemented once that popover is clicked.
https://github.com/sugarlabs/musicblocks/assets/127110636/8a4bff1f-d3a1-4070-9246-ee9dbcc3eb92
> Confirm_clear

- js/widgets/rhythmruler.js
> Implementing backspace in the dissect number input field in the rhythm block

- js/blocks.js
- js/blocks/ExtrasBlocks.js
> Lets vspace block connect to the switch clamp

- js/widgets/help.js
- localization.ini
Resolves https://github.com/sugarlabs/musicblocks/issues/3708
> Take_a_Tour

- js/widgets/jseditor.js
Fixes: #3706
Added the toggle  console arrow button to the  console in js editor.
[screen-capture.webm](https://github.com/sugarlabs/musicblocks/assets/103755591/6bd13db7-177a-44ee-9af7-d73c239cd75d)
> Feat/added toggle console arrow  button

- js/blocks.js
fixes #3723 
This modification ensures  vspace block to connect another vspace block.
> fixes v-space connection

- js/activity.js
> Fixed enter key behaviour when search box active

- css/activities.css
issue: #3732 
This is a simple alignment issue the button is not aligned correctly at center as you can see in the picture
after alignment
> alignmenttextandbutton

- js/blocks/WidgetBlocks.js
added JSDoc style documentation for WidgetBlocks.js
> Added Documentation

- js/palette.js
- lib/materialize-iso.css
Resolves Issue https://github.com/sugarlabs/musicblocks/issues/3743
> nav-zindex-changes

- css/activities.css
- index.html
Fixes: #3299
> Loading Video is a bit confusing for the first Visitor. It doesn't tell that the screen is loading.
Now : 
https://github.com/sugarlabs/musicblocks/assets/108459152/d720dae2-39a7-456e-a890-b1cbe9bba131
Thanks to @vivekbopaliya
> Loading animation below the video

- dist/css/windows.css
- js/widgets/phrasemaker.js
In reference to the issue #3647 and #3704 pls test this project  before the changes and after as well.
[Converted.files.2.zip](https://github.com/sugarlabs/musicblocks/files/14270650/Converted.files.2.zip)
@walterbender In this pr i tried to solve that issue pls review once.
> fixes pharseMarker regression

- js/activity.js
- js/turtle.js
- js/turtleactions/DictActions.js
Resolves #3755 .
@walterbender Plz review.
https://github.com/sugarlabs/musicblocks/assets/105922142/af473a39-1d0d-4bdd-8df6-d999131c2d1b
> Resolves Bugs of DictBlocks

- planet/css/style.css
> fixes select dropdown

- js/activity.js
- js/turtles.js
Solves #3783 .
@walterbender Plz review.
> "ResolvesMenuBug"

- js/widgets/jseditor.js
> Fixes visibility of line numbers

- planet/index.html
- planet/js/Publisher.js
Resolves #3797 @pikurasa @walterbender Plz review.
https://github.com/sugarlabs/musicblocks/assets/105922142/d810024a-391c-4685-b7ad-2f4dc1dcfb29
Now the user will not be able to type any random tags and can type correct tags (Atmax 5,Which was according to already existing in chip.add function),Also added chip.delete function as when the user clicks on close button the tags array will not be updated.
> "ResolvesTagBug"

- .github/workflows/stale.yml
#3794 
Workflow file added
@walterbender please review this PR
> stale worksflow added

- index.html
A better way to handle with unimplemented functions(enable easier understanding of codebase for the developers than error messages)
> Resolves #3817

- js/blocks.js
> Warn user- when forever loop within a note value block

- js/blocks/PenBlocks.js
Issue Reference - #2630 
Kindly review it.
@walterbender
> Added JsDoc style to js/blocks/PenBlocks.js 

- css/activities.css
> Fixed padding of search bar

- js/turtle-singer.js
fixes #3869 -- dictionary was undefined when stringifying, so the restore failed.
> dictionary is undefined when restoring

- CREDITS.md
- README.md
Some links are broken, but we have at least an urgent need to remove one of these links, which is now forwarding to a bad page.
> Remove links

- README.md
- js/SaveInterface.js
> Removed link to lilybin

- README.md
Made grammatical and wording changes to the READ.me file. Addresses #3439
> Changes to the READ.me file

- .github/workflows/weblate-sync.yaml
> Add weblate synchronization workflow

- js/activity.js
Issue Reference - https://github.com/sugarlabs/musicblocks/issues/2630
Should I do the same for all the JavaScript files?
Kindly review it.
@walterbender
> Added JsDoc style to js/activity.js

- js/activity.js
- js/toolbar.js
Issue Reference - https://github.com/sugarlabs/musicblocks/issues/2630
Kindly review it.
@walterbender
> Added JsDoc style to js/toolbar.js

- js/activity.js
Fixes: #3917 
https://github.com/sugarlabs/musicblocks/assets/109718740/89a62784-53e9-42dc-995b-4bd7ed5e853c
> Fix input boxes

- guide/50cent_block.svg
- guide/50cents_by_ratio.svg
- guide/README.md
- js/blocks/PitchBlocks.js
- js/turtle-singer.js
- js/utils/musicutils.js
Add support for cents through semi-tone transposition.
Fixes #3919
> Add support for cents

- guide/50cent_block.svg
- guide/50cents_by_ratio.svg
- guide/README.md
- js/blocks/PitchBlocks.js
- js/turtle-singer.js
- js/turtleactions/PitchActions.js
- js/utils/musicutils.js
Fixes #3918
By using processPitch for all pitch types, the transformations are applied the same no matter how the pitch is specified.
One caveat: the Scalar and Semitone Step blocks step from the last pitch played; when used inside of any of the transpose blocks, they will step from the previously transposed note, which may produce unexpected results. (This is not a regression, rather it is just more evident.)
> Ratio transpose and Ratio interval

- guide/README.md
- guide/guide.html
Updated the link in both guide.html and README.md files.
> Hyperscore link update (#3939)

- dockerfile
- guide/README.md
Issue #3948 addressed
I have improvised the Dockerfile using multi stage docker build.
> Updated Dockerfile 

- js/activity.js
@walterbender @apsinghdev I have fixed this issue...
https://github.com/user-attachments/assets/3ad19d9f-1d9f-4b31-9a8e-bce6868fa750
> Fixed #3956 Auto increasing and decreasing input block

- js/blocks/RhythmBlockPaletteBlocks.js
With reference to issue #3931 
@walterbender 
what I found here
bpmFactor = TONEBPM / tur.singer.bpm.length > 0 ? last(tur.singer.bpm) : Singer.masterBPM;
and here tur.singer.bpm.length =0 because tur.singer.bpm is an empty array,
which is why bpmFactor is null,
which is making beatValue=0,
I have put a condition for that and hard coded the beatValue.
the issue look fixed, please test and suggest changes what can I do.
> Rhythm block doesn't repeat issue update

- js/block.js
@walterbender Can you please review it ?
> fix: remove redundant code to achieve DRY consistency

- js/blocks/DrumBlocks.js
then ran a simple loop:
`drumConfigs.forEach(config => {
new PlayDrumMacroBlock(...config).setup(activity);
}`
> Update drum block setup by combining everything into a list

- js/activity.js
- js/block.js
- js/blockfactory.js
- js/blocks.js
- js/blocks/DrumBlocks.js
- js/blocks/GraphicsBlocks.js
- js/blocks/PenBlocks.js
- js/lilypond.js
- js/logo.js
- js/macros.js
- js/notation.js
- js/palette.js
- js/piemenus.js
- js/turtle-singer.js
- js/utils/musicutils.js
@walterbender Can you please review it ? Will commit changes made in other files to this PR only.
> refactor: update indexOf () === -1 to ! includes

- js/lilypond.js
everything is now in an iterable list
> used regex to minimize code

- js/activity.js
Fixes: #4019 
https://github.com/user-attachments/assets/ca610572-6254-43f7-8db1-02ce53491a90
> Fixed mouse event malfunctioning

- js/abc.js
This addresses two FIXMEs in the `abc.js` file, implementing support for pickup measures and multi-voice notation.
- Added handling for pickup measures using the K: pickup= field in ABC notation.
- Implemented multi-voice support using V: directives in ABC notation.
These changes are implemented within cases, while keeping the original `i += 1;` condition intact, while everything works like before.
> FIXME: Implement pickup measures and multi-voice support in abc.js

- index.html
- js/toolbar.js
This PR include Changes in confirmation model with more appropriate dailog box 
it include chnages in CSS of New project modelm have included minimal changes by adding inline CSS 
fixes : #4044
> Improve Confirmation Modal Design

- js/activity.js
change in this.drawSelectionArea() function .
https://github.com/user-attachments/assets/11348f91-3563-4cd0-8973-44fa5678fbbc
> Fixes: #4056 correcting highlight problem near nav-bar

- js/turtledefs.js
- Fixes #4105 .
- The title string was inserting in the else condition caused the issue.
- on the turtledefs.js , made sure the string isn't too long.
- Preview:
- Probably add the line in the metadata rather than title, to keep relevance in the search engine.
Checklist:
> Title String Changed

- js/piemenus.js
Resolve issue #4177 
Now the last grid option is also working. 
https://github.com/user-attachments/assets/1ba9c3cc-c77b-4f59-8971-a8bc8f13274b
> Making last grid option enebled

- js/block.js
@walterbender Can you please review it.
> fix: pitch octave limit to a valid range

- js/palette.js
Modified event handling in the palette block creation to prevent duplicate blocks on iOS/iPadOS devices.
https://github.com/user-attachments/assets/a68e6c36-a17f-406a-a46f-9d656ba16e93
> Fixes #4189 2 blocks getting added

- js/piemenus.js
> optimising the number selector in the note block octave

- js/turtleactions/DictActions.js
- js/turtleactions/OrnamentActions.js
- js/turtleactions/__tests__/DictActions.test.js
- js/turtleactions/__tests__/OrnamentActions.test.js
@walterbender I had started preparing tests for the /js/turtleactions please review this 
here i had added 
1. DictActions.test.js 
2. OrnamentActions.test.js
> Adding test for the Turtleactions

- po/README.md
> readme update

- js/turtleactions/DrumActions.js
- js/turtleactions/MeterActions.js
- js/turtleactions/PitchActions.js
- js/turtleactions/ToneActions.js
- js/turtleactions/VolumeActions.js
- js/turtleactions/__tests__/DrumActions.test.js
- js/turtleactions/__tests__/MeterActions.test.js
- js/turtleactions/__tests__/PitchActions.test.js
- js/turtleactions/__tests__/ToneActions.test.js
- js/turtleactions/__tests__/VolumeActions.test.js
This pull request adds the following test files in turtleactions:
1. DrumActions.js
2. MeterActions.js
3. PitchActions.js
4. ToneActions.js
5. VolumeActions.js
The test file for the above mentioned files have been added through this pull request. It addresses all the functions present in the those file.
> Tests added for turtleactions

- js/widgets/phrasemaker.js
Now the pie menu is able to remember the last selected value of index of the graphics blocks in the phrasemaker 
@walterbender review this 
https://github.com/user-attachments/assets/d234ca09-98b9-4882-a908-18dc64123f3a
> Pie menu is remembering the last selected index in phrasemaker

- js/turtledefs.js
> bumping version number

- js/palette.js
- js/piemenus.js
- js/widgets/aiwidget.js
- js/widgets/arpeggio.js
- js/widgets/meterwidget.js
- js/widgets/modewidget.js
- js/widgets/musickeyboard.js
- js/widgets/phrasemaker.js
- js/widgets/pitchdrummatrix.js
- js/widgets/pitchslider.js
- js/widgets/pitchstaircase.js
- js/widgets/rhythmruler.js
- js/widgets/sampler.js
- js/widgets/statistics.js
- js/widgets/status.js
- js/widgets/temperament.js
- js/widgets/tempo.js
- js/widgets/timbre.js
I have migrated and formatted the innerHTML concatenation to template literals
> migrated all the innerHTML concatenation to template literals

- js/__tests__/mxml.test.js
- js/mxml.js
@walterbender please review this.
> Test Suite for mxml.js

- index.html
- js/block.js
Resolves #4315.
https://github.com/user-attachments/assets/dcb9ed98-cdd3-4ae1-a811-1dd4d6813b04
@walterbender @pikurasa please review.
> correct inputs

- js/__tests__/notation.test.js
- js/notation.js
@walterbender review this test 
now we are having 499 tests 🎉
> Test Suite for notation.js

- js/activity.js
- js/toolbar.js
issue https://github.com/sugarlabs/musicblocks/issues/4353
After fixing :- 
https://github.com/user-attachments/assets/1df51d17-b1ce-4c63-ba3a-a87140a59a92
> step by step fix

- js/__tests__/blockfactory.test.js
- js/__tests__/rubrics.test.js
- js/blockfactory.js
- js/rubrics.js
@walterbender i had created a test file js/rubrics.js and js/blockfactory.js.
it works absolutely fine.
> test suite for rubrics.js and blockfactory.js

- js/turtles.js
This pull request addresses the `@todo` comments in the  `Turtles.TurtlesView` class in `turtles.js`. The following changes have been made:
-  Added comments to describe each variable in the `Turtles.TurtlesView` classe.
- Added comments to describe the purpose of each variable in the `Turtles.TurtlesView` class.
This pull request addresses issue #4366 .
> Add comments to Turtles.TurtlesView class

- js/__tests__/turtle-painter.test.js
- js/turtle-painter.js
@walterbender i had created a jest test suite for js/turtle-painter.js please review this
> Test suite for turtle-painter.js

- js/__tests__/themebox.test.js
@walterbender I had created a test suite for js/themebox.js review this
> test suite for the js/themebox.js

- js/__tests__/protoblocks.test.js
- js/protoblocks.js
@walterbender review the test suite for js/protoblocks.js
> test suite for js/protoblocks.js

- js/__tests__/turtledefs.test.js
- js/turtledefs.js
@walterbender review the test suite for js/turtledefs.js
> test suite for js/turtledefs.js

- js/__tests__/turtle-singer.test.js
- js/turtle-singer.js
@walterbender created a test suite for js/turtle-singer.js review it please
> test suite for js/turtle-singer.js

- js/__tests__/artwork.test.js
- js/artwork.js
@walterbender I had created test for js/artwork.js review this please
> test suite for js/artwork.js

- js/guide_addingtest.md
The guide involves all the steps which a new contributor must need to follow in order to create and implement test suite.
> creating a guide for adding test suite

- js/__tests__/turtles.test.js
- js/turtles.js
created a test suite for the js/turtles.js
> test suite for js/turtles.js

- js/__tests__/palette.test.js
- js/palette.js
@walterbender I had created a test suite for js/palette.js please review it.
> test suite for js/palette.js

- guide/README.md
This PR updates the documentation for the Pitch Staircase widget by adding a wave icon note in the Save Stack.
> update pitch staircase widget documentation

- css/themes.css
Updates the background color of the dropdown content in dark mode to improve contrast and usability.
This change enhances readability and ensures better alignment with dark mode design principles, providing a more consistent and user-friendly experience.
before: 
after:
> fix dropdown content in darkmood

- js/widgets/pitchstaircase.js
This pull request introduces a play button icon in the pitch staircase widget to enhance user interaction.
> add play icon in pitch staircase widget

- js/js-export/__tests__/export.test.js
- js/js-export/export.js
@walterbender I had created a test suite for js/js-export/export.js please review this
> Test suite for the js/js-export/export.js

- js/midi.js
I have encountered this error now. It should solve this.
> console error 

- js/js-export/__tests__/generate.test.js
- js/js-export/generate.js
@walterbender I had create a test suite for js/js-export/generate.js.
> test suite for js/js-export/generate.js

- js/js-export/ASTutils.js
- js/js-export/__tests__/ASTutils.test.js
@walterbender i had created a test suite for js/js-export/ASTutils.js and got some very good results with 100% of function coverage..
> test suite for js/js-export/ASTutils.js 

- js/toolbar.js
- js/utils/platformstyle.js
This PR addresses issue #4429 and fixes UI issues in dark mode affecting the grid, dialog box, and dropdown. 
Fixed grid and dialog box styling to ensure proper visibility in dark mode.
Adjusted background and text colors to match the dark theme.
-   [x] The code has been tested in Dark Mode.
-   [x] There are no breaking changes.
> Fixed Dark Mode issues 

- js/blocks/DictBlocks.js
- js/blocks/__tests__/DictBlocks.test.js
@walterbender I had created test suite for the js/blocks/DictBlocks.js
> test suite for the js/blocks/DictBlocks.js

- documentation/README.md
This PR refactors the keyboard shortcuts context in the documentation and links it with the table of contents for better accessibility and organization.
> Refactor Keyboard Shortcuts in Documentation

- .well-known/funding-manifest-urls
In order for this to validate our schema, we would need to have this structure .
https://github.com/sugarlabs/www/pull/679
As present in the guidelines:
https://floss.fund/funding-manifest/
@pikurasa
> floss fund estabhlishment

- README.md
This PR updates the link to Music Blocks V4 to ensure accuracy and accessibility.
> Update Music Blocks V4 Link

- sounds/samples/README.md
This PR updates the `README.md` to include instructions on adding instruments. This makes it easier for developers to integrate new instruments by following the updated documentation.
> Add Instrument Support in Interface

- js/__tests__/lilypond.test.js
- js/lilypond.js
@walterbender I have made test suite for lilypond.js. Please review this PR.
> test suite for lilypond.js

- README.md
- documentation/README.md
This PR changes-
- Removed the Firefox browser `file:///` opening issue mentioned as Firefox now supports the same.
- Added note about Record feature incompatibility in some browsers.
> [docs] changes regarding Firefox browser

- js/blocks/BooleanBlocks.js
- js/blocks/__tests__/BooleanBlocks.test.js
@walterbender I had added test suite for js/Blocks/BooleanBlocks.js please review this
> test suite for js/Blocks/BooleanBlocks.js

- .github/FUNDING.yml
This YML file should trigger GH to display ways to fund our most popular projects.
> Add funding yml to display sponsorship options directly through GitHub

- js/blocks/DrumBlocks.js
- js/blocks/__tests__/DrumBlocks.test.js
@walterbender i had created a jest test suite for the js/Blocks/DrumBlocks.js please review this
> Test suite for the js/Blocks/DrumBlocks.js

- js/blocks/HeapBlocks.js
- js/blocks/__tests__/HeapBlocks.test.js
This PR adds a comprehensive test file for `heapblocks.js` that achieves 100% function coverage. The new test file covers all functions and conditional branches (including error cases) for heap blocks, ensuring robust and reliable testing of heap-related functionality.
**This PR solves issue #4543.**
- Added a new test file: `js/_tests_/heapblocks.test.js`
- Created tests for the following blocks:
- **HeapBlock:** Verifies both JSON output and status matrix behavior.
- **ShowHeapBlock:** Checks that the heap is displayed correctly and created if missing.
- **HeapLengthBlock:** Ensures correct heap length is returned and status matrix is updated.
- **HeapEmptyBlock:** Tests for accurate detection of an empty heap.
- **EmptyHeapBlock:** Confirms that the heap is properly emptied.
- …
> added test for heapblocks.js

- js/widgets/temperament.js
Resolves #4550.
@walterbender please review.
> Reset pitch colors

- css/activities.css
- js/activity.js
- js/midi.js
@walterbender I have made the dialogue box. The list ranges from 100 to 1200.  Please review this PR.
Sir, is 1200 as a max limit reasonable?
> midi dialogue box

- js/blocks/ExtrasBlocks.js
- js/blocks/__tests__/ExtrasBlocks.test.js
@walterbender i had added test usite for the js/blocks/ExtrasBlocks.js please review this !
> test suite for js/blocks/ExtrasBlocks.js

- js/guide_addingtest.md
@walterbender i had addedd some more points in the testing guide please review this
> Adding some more points to guide_addingtest.md

- js/blocks/BoxesBlocks.js
- js/blocks/__tests__/BoxesBlocks.test.js
I have created a test file for js/blocks/BoxesBlocks.js
So @walterbender @omsuneri  can you please review it 
these is the test checks 
and these are coverage of file
> added test to BoxesBlocks.js

- js/blocks/OrnamentBlocks.js
- js/blocks/__tests__/OrnamentBlocks.test.js
added tests for js/blocks/OrnamentBlocks.js file 
@walterbender  can you plzz review it
> added test for OrnamentBlocks

- js/blocks/VolumeBlocks.js
- js/blocks/__tests__/VolumeBlocks.test.js
added test to js/blocks/VolumeBlocks.js file plzz review it @walterbender
> added test to volumeBlocks.js file

- js/blocks/RhythmBlockPaletteBlocks.js
- js/blocks/__tests__/RhythmBlockPaletteBlocks.test.js
I have added test to js/blocks/RhythmBlockPaletteBlocks.js file @walterbender  plz review it
> added tests to RhythmBlockPaletteBlocks.js

- js/widgets/temperament.js
Resolves #4574.
https://github.com/user-attachments/assets/5a408f54-b783-4f0b-b86a-7ac2a9932153
@walterbender please review.
> Resolves playback button issue

- js/blocks/NumberBlocks.js
- js/blocks/__tests__/NumberBlocks.test.js
i have added test to js/blocks/NumberBlocks.js 
@walterbender can you plzz review it
> added test to NumberBlocks.js

- js/widgets/timbre.js
issue : https://github.com/sugarlabs/musicblocks/issues/4461
In timbre.js - Implemented Event Delegation
Instead of adding individual event listeners to each element, I've implemented event delegation by attaching listeners to parent containers and handling events based on the target element.
Created a centralized event handling system that manages all widget interactions in one place.
Replaced string concatenation and innerHTML updates with document fragments and direct DOM manipulation.
> [Optimization] Optimize DOM - improve the performance - timbre

- po/pt.po
Completes the Portuguese translation by filling in 500+ previously empty strings
Fixes part of #4607
> Complete Portuguese (pt) translation

- js/blocks/ToneBlocks.js
- js/blocks/__tests__/ToneBlocks.test.js
i have added test for js/blocks/ToneBlocks.js
can you review it @walterbender @omsuneri
> added tests for ToneBlocks.js file

- js/blocks/MediaBlocks.js
- js/blocks/__tests__/MediaBlocks.test.js
I have created test for  js/blocks/MediaBlocks.js ,
@walterbender plzz review it
> added test to mediaBlocks.js

- js/blocks/ToneBlocks.js
- js/widgets/timbre.js
This PR fixes bugs in the Timbre Widget, especially from the "effects" section.
@walterbender, Please check this PR.
Before : 
https://github.com/user-attachments/assets/6354d451-693e-41a5-8015-cecce86a3402
> FIX: Timbre (effects)

- js/__tests__/background.test.js
- js/__tests__/languagebox.test.js
fixes : #4627
**I've improved the test coverage for background.js from 0% to 100% for statements and functions, with 87.5% branch coverage by:**
- _Improved mocking technique_: Added callback capture to the browser API mocks to properly simulate event handling
- _Added event simulation tests_: Created tests that simulate browserAction clicks and extension installation events in both Firefox and Chrome
- _Added callback function testing_: Verified that the appropriate actions are performed when event callbacks are triggered
- _Added module exports testing_: Ensured the module correctly exports different values based on browser environment
**languagebox.js**
- Added test for all language selection methods
- Added test for Proper handling of japanese kana message display
Adding @walterbender …
> Improve test coverage for background.js  && languagebox.js

- js/turtleactions/__tests__/DrumActions.test.js
fixes: #4627 
Improved test coverage for drumactions.js reaching 98.07 branch coverage.
Thanks !
> fix(add): improved test coverage for drumactions.js

- js/turtleactions/__tests__/OrnamentActions.test.js
fixes: #4627 
Improved test coverage for ornamentactions.js reaching 96.87 branch coverage.
Thanks !
> fix(add): expanded coverage ornamentactions.js

- js/turtleactions/__tests__/VolumeActions.test.js
Fixes: #4627 
Improved test coverage for volumeactions.js reaching 96.25 branch coverage. 
Thanks !
> fix(add): more test coverage for volumeactions.js

- js/turtleactions/__tests__/DictActions.test.js
fixes: #4627 
Improved test coverage for dictactions.js reaching 95.31 branch coverage.
Thanks !
> fix(add): Improved test coverage for dictactions.js

- js/turtleactions/__tests__/MeterActions.test.js
Fixes: #4627 
Improved test coverage for meteractions.js reaching 97.05 branch coverage.
Thanks !
> fix(add):added tests for meteractions.js

- js/blocks/__tests__/ToneBlocks.test.js
@walterbender this resolves the failure of a test case in ToneBlocks.test.js
> Resolving failure of ToneBlocks.test.js

- js/turtleactions/__tests__/PitchActions.test.js
- js/utils/musicutils.js
- js/utils/utils.js
fixes: #4627 
Improved test coverage for pitchactions.js reaching 90.34 branch coverage.
Thanks !****
> fix(add): Improved test coverage for pitchactions.js

- js/activity.js
The new copy button added a class ID that broke the file parsing on load.
> fix regression with new save file type

- js/activity.js
The workaround for different saved html data formats was a bit of a hack. This implementation simply looks for the codeBlock class id and makes a decision on what to do.
> Check for class
