activity/activity.info
Its hard to even track this activity in the log since entries were with the name null-1,null-2 etc giving this a bundle name would make it a lot easier to track the activity when necessary.
=> Add bundle name org.sugarlabs.MusicBlocks

js/matrix.js
All the buttons/menus in the music blocks activity have an effect of becoming lighter on hovering over, but this is not present for the matrix. This adds a highlight when hovered upon.
=> Add hover color change effects for the matrix and matrix menu buttons

js/activity.js
Used the 'save' and 'open' icons for the save and load buttons.
Also made the right menu opens when the page loads as default
Issue: https://github.com/walterbender/musicblocks/issues/111#issuecomment-171763751
=> Add save and load buttons to the right main menu

js/logo.js
Only use 'a-z' , 'A-Z' , ',' , '.'  and ' ' with mespeak
Since mespeak does not recognize ! or ? etc. It only recognizes the above characters, so instead of passing it the entire string supplied, we could filer out characters that mespeak does not recognize.
=> Fix Issue #142

js/logo.js
This patch extends the duplicate note functionality to the matrix. The notes can now be seen multiple times in the matrix with the duplicate notes block
=> Extension: Duplicate notes functionality in the matrix

header-icons/plugins-button-white.svg, header-icons/scroll-unlock-button-white.svg, js/activity.js
Replaced `plugin-button.svg` and `scroll-button.svg` with
`plugins-button-white.svg` and `scroll-unlock-button-white.svg`, fixing
the tutorial, which was broken by 0cb41d8.
=> Replaced missing help icons

header-icons/clear-button.svg
Removing the background of the clear-button makes the button more consistent with the other icons on the navigation menu.
=> Removed the background for the clear button

js/activity.js
Changed alignment on navigation menu buttons so that they are now centered instead of aligning with the left edge.
=> Centered label on navigation menu button

js/activity.js, js/palette.js
In the left palette menu,
a)If we hover over an icon, we get the circles highlight draw on the icon.
b)If we now scroll then the icon moves away from its original location but the highlight stays in its place.
Before:
After:
I removed the highlight on scroll so that the problem does not occur.
=> Remove highlight of circles on the icons on scroll

js/basicblocks.js
Denominator ==> Note Value | Change default back for rhythm block; keep 3/1 for tuplet
>  I am checking out the latest commit--actually, I realized what the
> change was from reading the diffs directly on my phone (good for me! Anyhow...)
> 
> I like the change, but for /rhythm/ blocks nestled in tuplets only (for
> whatever reason, I thought we were only changing the defaults for the
> rhythm blocks within tuplets)
> 
> I do not like "denominator" instead of "note value" for just the rhythm
> block.
> 
> I really do not like having a default value of 1 (basically a whole
> note) for the rhythm block (aside from when it is inside tuplet).
> 
> **What I propose**
> 
> 1. Keep rhythm blocks how they were.
> 
> 2. Just change the default for the /rhythm/ block when a /tuplet/ block is pulled …
=> Denominator ==> Note Value

README.md
On directly clicking on previous route it is redirecting me to a relative url from the present page . hence I the url absolute by adding http:// in front the redirect url
=> Updated the README.md to match the correct route

js/logo.js, js/turtle.js
GCI 2016 - eohomegrownapps
I have implemented a note volume scale factor which scales the turtles
according to volume of notes - volume of 1 = 0.804*original, volume of
50 = 1*original, volume of 100 = 1.196*original where original is the
current turtle size * the scale factor of 60/55. You will notice that
this.blinkFinished and this.beforeBlinkSize have been added; these are
due to the fact that sometimes (i.e. when the tab is not in focus)
notes may play before the duration of the previous note is finished. So
if the blink function is called before the previous blink is finished
it will use a cached value of the turtle’s original size to prevent it
using the expanded size as the original size and expanding itself
further. I have also added tweening meaning the turtle will gradually …
=> More fixes to Turtle Blink task - in particular removal of delay and volume scaling

index.html
We have libararies stored locally, no needed to take them from websites what slowes down load time and additionally is double declaration of a one script. (However, FB SDK shouldn't be stored locally and we can't download it and put into `lib` folder.)
In the commit I have also removed completely blank `<script></script>` block and unnecessary new lines.
=> Fixed #394; Removed unneeded doubled scripts' declarations

css/activity.css
The space between "#popdown-palette:" and "last-child" was invalidating this selector. Removing the space fixed the issue.
=> Fixed #popdown-palette:last-child selector

js/activity.js, js/logo.js
Fixed @pikurasa's issue -- make it so that the stop button is hidden every time an error is reached.
Does not fix @Hrishi1999's issue; the stop button still momentarily appear nonetheless.
Fixes Issue: https://github.com/walterbender/musicblocks/issues/401
=> Hide "Stop Button" when fatal error reached, and make "no input in clamp" error non-fatal

js/palette.js, js/utils.js
Changing `turtledefs.js` would require us to change all PO files. Implemented workaround requires palette label to be always written with title case - if it is not, then first char of label gets automatically upper-ed. 
When this PR is merged, I will commit analogous changes to TBJS.
Preview:
=> Fixed #451; require palette labels to be written with title case

js/logo.js
This PR fixes issue #482 , calling the blink function only if the lilypondSaveOnly function is set to false.
=> Fixes issue_482

js/rhythmruler.js
`this._rulerSelected` had unexisiting values after restoring session, because it was set before existance condition was checked and applied. The result while undo started to work after doing some another action is that another dissection was requiring an app to set proper `this._rulerSelected` value.
=> Fixed #421; resolved logic error with 'rulerSelected'

js/blocks.js
removal of the only start block is now made impossible, user gets an error message after trying to perform such action
this is actually the fix of a logic error - function deteced no turtle will be left, but didn't stop proceeding
=> Fixed #495; made removal of the only start block impossible

js/rhythmruler.js
Fixes #381 and #497 
Also fixes unreported issue: you can no longer dissect a ruler while the rhythm ruler is playing, which had may unpredictable consequences.
There is still an issue with the drums gradually slowing down after a long period of play, but the flam issue is no longer apparent. 
The basic strategy was to maintain separate offsets for each ruler rather than depending upon only one master offset to track lag.
=> Rhythm timing

js/protoblocks.js
1. dockTypes of waitFor were mismatched, they should've been placed in reverse order
2. waitFor size is not a standard one, it has been adjusted to make it looking well in clamps
=> Fixed #492; waitFor now gets connected with other blocks

js/activity.js
Standard debugging and code look-up shows the function is never called during normal usage. To be removed.
=> Fixed #323; removed never used piece of code

js/pitchtimematrix.js
This PR fixes issue #348. It implements i18n for graphic blocks. The screenshot for Music Blocks in FF for Spanish is attached below.
=> Fixes #348; i18n for graphic blocks

js/rhythmruler.js
Rough workaround to get backspace press working on number input in rhythymruler. Reasons why it doesn't work as intended by default need further investigation.
=> Fixed #508; rough workaround to get backspace working

css/activity.css, header-icons/grab.svg, index.html, js/activity.js, js/rhythmruler.js, js/samplesviewer.js
Fixes #586 (First Row in Rhythm Ruler should always be visible | scrolling) by changing the underlying structure of the divs and tables.
rulerDiv contains two children:
drumDiv (to hold the widget buttons) and
rulerBody (to hold a table of buttons and rulers)
The first column of the table in rulerBody is fix when horizontal scrolling is active.
The entire table scrolls vertically when needed.
Up to four rulers are visible at any one time.
The sizes of the various elements are by-in-large defined in activity.css.
=> refactor rhythmruler code

guide/README.md, js/basicblocks.js
This PR fixes issue #573  which requires articulation block to be renamed and changes need to be made in Guide as to how it functions.
I have renamed Articulation to "set relative voice volume" and have updated the guide according to the conversation on #573 .
A little bit of svg editing is needed in the guide which @eohomegrownapps volunteered to do, so I am opening an issue regarding it as suggested by pikurasa.
=> Fixes #573; Articulation needs to be renamed

js/basicblocks.js
Status block now doesn't get cut from right side. (See image)
(Issue : https://github.com/walterbender/musicblocks/issues/572)
=> Fixes visual bug specific to status block

index.html, js/activity.js
Hello,
After try various things to fail loading MB at once, I finally came to this. MB, for about 60% of time, never loaded at once. I tested it in various ways. But this change, as I have tested, loads MB too fast (it loads for me, other people need to test it to confirm). The sdk.js can't be found. Now, it loads perfectly. Please test it. 
Note : Please do clear all the cache and try reproducing this issue after fix.
Also, the loading animation becomes a bit quick here. The eyes blink too fast.
=> Better startup performance (possible sdk.js error)

README.md, documentation/README.md
The whole <img> tag was getting displayed earlier instead of the image.
=> Resolved issues with image display and typos(for Outreachy 2017)

js/palette.js, js/protoblocks.js
Resize palette container based on the components it has.
Tested the code on both Windows and Mac environments.
=> fixes #667: resizing palette container

guide/README.md
Github is a bit fidgety when it comes to nested ordered lists, so additional blank spaces are needed to properly indent the next level of list items. Also, for TOC to function correctly, there need to be empty anchors (with correct `name` attributes) inside appropriate headings. I took care of these two issues.
=> Fix TOC and faulty internal links.

manifest.json
Unnecessary punctuation removed in manifest.json
=> unnecessary punctuation removed

js/basicblocks.js
Visual bug specific to tempo widget is fixed. On collapsing the widget, it wasn't showcased properly. Similar to #572
=> View bug fixed

js/block.js
tempo widget now shows "tempo" after being collapsed instead of "mode"
=> Collapsable name set

js/activity.js
Tested. Using backspace doesn't navigate to previous page. Test again before pushing.
=> Fixes backspace and TAB not working

js/samplesviewer.js
The strange blue rectangle in issue #707 was caused by a stray canvas not being hidden when Planet was opened. In samplesviewer.js, when Planet is opened, the canvas will now be hidden removing the blue rectangle.
=> Fixed issue 707

index.html
There are 4 input types shown in the place of on device project
thumbnail when opened a project from planet. They will be visible at the
bottom of thumbnail.
Problem : https://github.com/walterbender/musicblocks/issues/709
=> Fixes on device project thumbnail bug.

header-icons/fb-inactive.svg, header-icons/save-block-artwork.svg, header-icons/save-block-artwork_backup.svg, header-icons/save-png-inactive.svg, header-icons/save-png.svg, header-icons/save-svg.svg, header-icons/save-tb.svg, header-icons/upload-planet.svg, js/activity.js
The savebox panel is the same as the one already used in Turtle Blocks. The disabled save to Facebook button has been replaced by a button to save the block artwork (same as the Alt-B keyboard accelerator command).
=> add savebox support to MB; add save-block-artwork button

guide/index.html
Issue #808 was caused by reliance on Bootstrap's listing functionality which did not appear to support the 'a.b.c' numbering desired in this guide, and some mistakes in formatting `<li>` and `<ol>` containers. I added a few lines of CSS to enable the formatting, and corrected the issues regarding `<li>` and `<ol>` containers - for future reference, to have subtopics of a `<li>Topic</li>,` put the `<ol></ol>` inside the `<li></li>` as follows:
```
<li>Topic
<ol>
<li>A subtopic</li>
<li>Another subtopic</li>
</ol>
</li>
```
=> Fixed issue 808

css/activity.css, js/samplesviewer.js
1. To fix the issue of thumbnail padding, I reduced the width of the thumbnails so that the total width of each row would sum to 99% - meaning that 1% padding would be left at the right of the thumbnails as empty space.
2. As project names have no spaces, they would not ordinarily wrap in a `<span>` - thus I set wordwrap to break-word to force the names to wrap even when no spaces are present. I changed the display attribute of the 'content' divs (local and global projects) to flexbox to prevent thumbnail names which wrap onto the next line from overly affecting the layout of the grid.
=> Fixed issue #852

guide/fibonacci3.svg, guide/graphics1.svg, guide/lilypond1.svg, guide/tempo0.svg, guide/transform0.svg, guide/transform10.svg, guide/transform12.svg, guide/transform14.svg, guide/transform2.svg, guide/transform3.svg, guide/transform6.svg, guide/transform8.svg, guide/voices3.svg, guide/voices4.svg, guide/voices5.svg
This pull request is for issue #881 . Most of the changes in images are related to how transpose is now semi-tone transpose, however I also included new images for other discrepancies I noticed such as how duplicate notes is now duplicate, change in augmented and minor blocks, as well as the change in color for the tempo block.
=> Making Guide Images Relevant

header-icons/save-wav.svg, index.html, js/activity.js, js/logo.js, js/musicutils.js, js/savebox.js, lib/recorder.js
eohomegrownapps-GCI
Fixes issue #866
1. I added a new icon for saving as WAV - header-icons/save-wav.svg
2. I have altered the SAVEBOXSVG and a number of other 'magic numbers' in the code to allow for another icon in the box. This process was rather unpleasant - I'll modify these numbers soon to avoid the use of 'magic numbers'.
3. I'm using the FOSS library https://github.com/mattdiamond/Recorderjs (MIT licence) and have included it as a script in HTML - is there anything else I need to do to make it play nicely with require.js?
4. I added a recorder instance and download function to musicutils.js. Similarly to compile, pressing the 'save as WAV' icon starts the code playing with a recording flag - this tells logo.js to start the recorder before code starts and stop it after code starts. …
=> Fixes issue 866

css/activity.css
This issue was caused by code in activity.css (meant to style the search bar) having too wide a scope and styling all input fields like the search bar - even the fields for names in Planet. I fixed this issue by changing the CSS from `input` to `#search` thus restricting the effect of the styling to only elements with id 'search' (i.e. the search bar).
=> Fixes issue #956

js/activity.js, js/logo.js
When the user records a project, MB calls the compile function with a 'recording' argument. This then calls the playback function which records the music as normal. This fixes the first part of @pikurasa's suggested changes - I might sort out the second part tomorrow / at a later date if I have time.
=> Record function now uses compile

js/activity.js, js/samplesviewer.js
eohomegrownapps-GCI
This fix is in two parts: the addition of a flag selection mechanism to the Planet and the addition of more flags to activity.js.
Flag Selection Mechanism:
I created a div, made visible when the 'Advanced' button is clicked, which displays a list of checkboxes for different flags. When a checkbox is checked, the URL updates automatically. I also fixed a bug with the flag selection tooltips - previously, the flag selection tooltips for projects on the rightmost and leftmost columns would be only partially visible.
Addition of more flags:
As per the task description, I added 'show code blocks', 'collapse code blocks' and 'run code blocks' flags - does exactly what it says on the tin.
Please do let me know if there are any issues, particularly regarding the expected …
=> Fixes issue #548

js/analytics.js, js/basicblocks.js, js/blocks.js, js/logo.js
eohomegrownapps-GCI
As per the task description, I added 'leftpos', 'toppos', 'rightpos', 'bottompos', 'width' and 'height' blocks to the 'media' palette. Please do let me know if the coordinates are meant to be those of the canvas (as in the pull request) or those of the dotted orange 'bounding box' within the canvas.
=> Added screen position blocks to Music Blocks

js/logo.js
eohomegrownapps-GCI
To fix this issue, if logo.js is evaluating a doubly block, I follow the connections of the block until I reach a block that's not 'doubly' - I then evaluate the doubly block based on the type of block at the end of the 'doubly' chain.
=> Fixes issue #908

js/background.js, js/launch.js, manifest.json
This is for the purpose of easily installing Music Blocks, and being able to use it without being connected to the internet. Fixes #647 
Clicking the button on the top right opens musicblocks from locally installed extension files. It also opens when the extension is first installed. 
As an additional feature, should MusicBlocks also launch when the music blocks site is visited? 
We should definitely publish this in the webstore, and I'll probably be making a Firefox extension too.
=> Allows Music Blocks to function as a chrome extension

js/activity.js, js/turtledefs.js
Originally had ABC notation (with C being C), however I found that to be confusing as pitches in Music Blocks are defined by the solfege. Instead, `d` is `do`, `r` is `re` and so on. 
Will include chaining of notes in a separate PR
=> Add keyboard shortcuts for creating notes

guide-ja/README.md
It seems to work... see https://github.com/pikurasa/musicblocks/tree/svg-link-ja/guide-ja
Please change the solfege as well.
ド = Do
レ = Re
ミ = Mi
ファ = Fa
ソ = Sol
ラ = La
シ = Ti (literally "Si")
=> update links to link to Japanese translated svg files

js/activity.js
I was using the search function for MB when I realized that the search results menu doesn't actually hide if there is an existing input.
**Steps to reproduce:**
1.  open the search widget, key in any search. eg 'note value'.
2. without clearing the search, exit out of the search widget.
What I have done is that I changed `ui-helper-hidden-accessible` to `ui-menu`, keep the existing `hidden visibility` on `hidesearchwidget` and made it visible when `showsearchwidget` is called.
Now, even if I go through the above steps, the search results menu would be hidden from the canvas  after exit.
One more thing, I included the `disableKeys` if the search widget is visible, keeping my code in format with how `disablekeys` were set previously.
=> disable keys for search + search menu fixes

js/logo.js
> Right now, any mouse can change the pitch number offset for all of the other mice. It should be tracked per mouse instead of being a global.
Hello! I have changed `pitchnumberoffset` to be relative to each mouse.
=> track Pitch Number Offset per voice

guide-zhCN/README.md, guide/README.md
I have finished translating the Simplified Chinese version of the Music Blocks guide, all that is left now are the images which can be changed in a further commit. 
I have also resized the modified images in #1036 as they are currently out-sized. I have replaced the image Markdown code with a HTML tag as it can render images with length and width specifications.
=> Images Fixes, Finishing Chinese Translation For Guide

js/activity.js, js/basicblocks.js, js/block.js, js/blocks.js, js/logo.js, js/palette.js
Adds a new store in block with a embedded name.
Advantages:
* more compact: only one standard block height
* no need to manage the block name
We keep the old-style block in the palette as well so that you can rename the box.
=> New "named" store in block

js/activity.js
The files variable was improperly referenced, triggering an error message during file load. This patch uses the correct reference.
=> fix bad files reference

planet/index.html, planet/js/helper.js
The search bar did not appear on some versions of Chromium due to a security policy preventing the execution of inline JS (index.html:46 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.)
I moved a few instances of inline JS in index.html into the helper.js file, which should (hopefully) solve the problem.
(nb. I have been unable to reproduce the bug so cannot verify that it is fixed myself, but MB still appears to work)
=> Fixed issue #1221 - chrome security error

planet/js/GlobalPlanet.js
Fixes https://github.com/sugarlabs/musicblocks/issues/1264
Implemented the ability to set non-special tags as default; 'music' tag enabled. (@pikurasa sorry this is so late - I haven't had any coding time over the past few days)
=> Fixes issue #1264

js/activity.js
This was evaluating a function as if it was an attribute, which always returns true. That causes the ticker to redraw the screen continuously, resulting in high cpu usage and out-of-sync playback.
=> Correct evaluation of createjs.Tween.hasActiveTweens()

js/palette.js
During the MB workshop in Tokyo, I saw many teachers trying to close the palette by clicking the icon on the menu which totally makes sense to me while nothing happens. Currently, the only way to close the palette is by clicking the X button which is not intuitive. Therefore, I would like to propose to give users another way of closing the palette by the icon on the menu.
This is only a few lines of change but it should improve the usability of the MB significantly.
=> Hide the Palette when clicked again

guide/README.md
I found the charts to be confusing as well as the flow of the text.
I also think that the *odd* example is still confusing, but I added some text that I hope clarifies that the first `C` pitch is not being operated on.
=> Inversion clarification

js/palette.js
fixes #1350
Hidden blocks were causes lots of mischief with the palettes. This patch keeps every block in the model and only skips hidden blocks when generating the palettes from the model. Seems to fix the skew issue.
=> palette skew 

js/block.js
This patch explicitly display "up" and "down" for step pitch when collapsed.
I think up and down is consistent with forward/back and crescendo/decrescendo
In Japanese, it wil be 上 and 下 or うえ and した
=> Change collapsed step pitch from "+/- value" to "up/down value"

documentation/slur-block.svg
Having only a single note inside the slur clamp is misleading and I think has caused confusion. I changed the example to show two notes within a slur clamp.
=> Two notes within a slur as our example

js/activity.js, planet/js/main.js
Previously, there was a placeholder i18n function in planet/js/main.js which prevented i18n from working properly on Planet - this has now been removed, and the 'main' i18n function for MB is now passed to Planet through the PlanetInterface.
=> Replaced placeholder translation function in Planet

index.html
I *think* the problem is that when the maximise button is clicked the resize functions gets the width of the screen before the maximise button is pressed.
It then resizes the window to this width (which is the window size prior to the maximise button press).
I added a delay to make sure this doesn't happen.
=> Adds delay to resize (Fixes #1452)

lib/require.js
Tripled waitSeconds in require.js - did not encounter any adverse effects.
For me at least, this ensures all samples load.
Please test.
=> Ensure all samples load (Fixes #1414)

index.html, js/SaveInterface.js
I have commented out all PDF related code until the server supports conversion of ly to a PDF format.
This means the Save as PDF button on the "Save as sheet music" modal is no longer available.
This should address #1611
=> Disabled "Save as PDF" until server supports it

js/block.js, js/logo.js
Fixes issue #1423. I made a new constant, `PREVIEWVOLUME` and the `__pitchPreview` function now uses this instead of `DEFAULTVOLUME`.
Note: something strange happened when I force pushed, and my old PR (#1604) didn't update the commits after that. So I opened this one.
=> Make preview volume louder

js/activity.js, js/toolbar.js, js/turtle.js
Click "Collapse" -> Open the auxiliary toolbar -> click "Expand" 
The stage's reset causes an overlap:
With my patch, the aux toolbar closes if expand is clicked (as it does when collapse is clicked).
=> More re menu overlap (#1582)

planet/css/style.css, planet/index.html
When the window is resized, the Planet code becomes central resulting in an overlap as in #1631 
To combat this, I made the Planet logo stay left aligned on resize:
When the window is very small (<655px wide), in order to prevent further overlap, I made the "Planet" text disappear (I feel this is a good enough compromise as resizing to this extent is very rare):
=> Left-aligned Planet logo (Fixes #1631)

lib/materialize-iso.css, planet/css/style.css, planet/index.html, planet/js/ProjectViewer.js, planet/js/StringHelper.js
In order to reduce overlap and stop the user having to scroll the "modal footer" in a project's description, I replaced the button with an icon:
Here's an example of a reported project (observe the icon):
Here's an example of an unreported project when the window width is as small as possible (in Japanese):
Please note there is also a "Report Project" tooltip for the icon (enabled for translation too)
I think using an icon in place for the previous icon not only prevents overlaps but also betters the responsiveness - previously a scrollbar would be needed for the modal footer (observe the footer scrollbar below):
=> Replaced "Report Project" with an icon (Fixes #1639)

planet/js/GlobalPlanet.js
I have attempted to make this clear in this gif:
(1) After clicking off multiple tags, there is always one last tag which is last to be 'clicked off'
(2) After this click off, only the projects containing last selected tag are being shown. 
This causes the console to throw:
In order to resolve this (and keep it line with how Turtle Blocks handles this) I have made "All Projects" the 'fallback' tag if no others are selected.
I think this patch is possibly related to @pikurasa comment in #1655
=> Make 'all projects' the fallback tag

js/turtledefs.js
In offline version of MB, if we select any language other than japanese 'Meet Mr. Mouse!' page of the help widget shows the default logo of mouse -
However, in Japanese, the same page shows the following image which I don't think suits the title of page -
With this commit I am suggesting that the image should be the  default logo of mouse as shown below-
=> Meet Mr.Mouse LOGO changed to LOGODEFAULT

js/toolbar.js
The pie menu in the project space used to remain even when the planet is
opened and covers the planet until the user clicks.
Making the display of the pie menu "none" when planetIcon is clicked fixed
the issue.
Fixes https://github.com/sugarlabs/musicblocks/issues/1676
=> Fixing Pie menu overlapping

js/widgets/help.js
The drag feature in help was not working properly
Before:
After:
=> fixed the drag issue in help

js/toolbar.js
The Context Wheel in the project space also used to remain even when the planet is opened and covers the planet until the user clicks. 
As done in previous PR #1684, the display of the Context Wheel should also be made "none".
=> Fixing Context Wheel overlapping

js/widgets/timbre.js
Open timbre widget menu
Single click on drag icon.
Drag icon will disappear.
This PR fix that issue
=> Drag icon disappear fix

js/basicblocks.js
To have a default for https://github.com/sugarlabs/musicblocks/issues/1421
I do not think number other than 0 is required for y as well. Just 100 for x is enough to get the idea.
=> Change x default for scrollxy to 100; 100 is more obvious than 10

js/block.js
The arc block doesn't have a pie menu. With this commit I am suggesting to add it for angle and radius values.
=>  Pie Menu For "Arc" block

js/widgets/timbre.js
This fix (#1155) checks the present filters and add different filter and gives warning when we select filter which is already present in timber widget.
=> fixed #1155

js/block.js
Fix https://github.com/sugarlabs/musicblocks/issues/1746
Stop hiding label on the input change and instead hiding it on enter or tab key press or clicking outside the label.
=> fix: stop hiding input label on change

js/utils/musicutils.js
As you can seen from the images the note value displayed is not correct it should be 1.25/2 instead of 1.5/2
Should be [1/4 1/8 1.25/2] but is [1/4 1/8 1.5/2]
=> Correct note value not displayed

js/basicblocks.js
I think that the issue stemmed from one of the following two:
1) attempt to correct something for JA translation (although I wonder why, as "on weak beat do" should be a unique string)
2) an attempt to resize the block
At any rate, at some point this one arg block was made into a two arg block, which is why crab canon was not "rendering correctly".
=> Fixes #1719 (Crab Canon) | On "weak beat do" is one arg block

js/logo.js
As you can seen from the images phrase maker doesn't show correct tables for tuplets. This fixes that.
=> phrase maker tuplet display error

css/activities.css, index.html, js/activity.js
Replaced canvas text box with HTML div and added close icon as per @walterbender comment on PR #1804
Behaviour is slightly different now in that the red arrows coming from the error box with the artwork are no longer hidden when the error text box is clicked on due to it not being a canvas container any more. I can look at recreating this but it may be more helpful to keep it as it is i.e. arrows stay visible until the artwork box disappears.
=> Clearing error text more obvious. Follow on from issue #1726 (PR #1804)

js/widgets/musickeyboard.js
Added pie menu containing add, delete and divide function for note duration.
=> Add, Divide, Delete menu for note durations

index.html
The issue was caused because the logo was an <a> component with line line-height: 64, which caused overflow when showing the focus or shadow on the nav bar, so I changed it with {line-height: 64;} and height 100% so it didn't stop occupying al posible space
=> Fixed misterious div

js/activity.js
Resolves #1854 
When a user loads MB for the first time or clears the browser cache, "localStorage.getItem('beginnerMode')" is undefined and bypasses the strict equality check to null.
This PR fixes it.
=> Enter advanced mode with only one click

js/widgets/modewidget.js
Fixed the issues from the previous pull request for fixing issue #1901 - changes are still in js/widgets/modewidget.js. From previous pull request:
The issue was based on incorrect indexing of the blockList and caused the key name to be updated with the mode name occasionally.
=> Fixed Issue #1901, revised.

js/block.js
The detection method for if the cursor had moved during a click was broken in Chromium-based browsers running on Windows. Also adding a check to compare the pointer location fixes this issue.
=> Fix pointer clicks on Chromium/Win10

package.json
A fix for the #1924 in using npm serve.
Tested on Fedora 31. Fedora 31 uses python defaults to python3. So the circumstances for testing this was right. Tested also with aliases of python as python2 and python3. PR works for all versions. 
It runs python, checks if the `python` is actually `python2` or `python3`. If it is python2 execute python -m .... and if its python3 execute python -m .... Both should work with python executable existing in the PATH.
~ wrt GCI
=> Fix #1924 $ npm run serve - python2,3 [GCI]

js/activity.js, js/logo.js, js/widgets/pitchslider.js, js/widgets/status.js, js/widgets/widgetWindows.js
As well as porting the status widget, this also has some boilerplate work towards restoring widgets after opening the planet. It's only implemented for the status widget so far, but starting to move some of the other things in `activity.js` (~ln4000) over to using the functions `widgetWindows` exposes instead of querying CSS styles should be fairly trivial.
=> Port status widget to widget windows

js/mxml.js
fixes @pikurasa 's issue with measure info not being loaded unless explicitly specified by the user. Now it defaults to 4/4 time if tempo is not specified.
=> push measure info by default if it's the first measure

js/block.js
Left and Right Blocks should now have a pie menu.
Note that they both have the same value, as said in #1945 , except that the Left block is backwards of Right block value.
=> Add Pie Menu for Left and Right Blocks

js/logo.js
Pitch Number block should now have a sound preview. This should fix #1903 
In my opinion, this is more of a bug fix than an enhancement, as Pitch Number block do actually run a sound preview. However, it tries to run a number, not a pitch, and hence it throws this error:
This fix should first translate the number into pitch before passing the values to getNote function.
=> Preview Sound for Pitch Number Block

js/block.js
When the user clicks pitchnumber's pie menu, a preview sound should be heard. Hopefully fixes #1903
=> Sound Preview for Pitch Number's Pie Menu

index.html
It seemed as though the autocomplete handler must be called on page load. I also removed the "defer" in the JQuery link file as it doesn't run $(document).ready();
This is more of a work in progress PR, as I have never seen MB's search autocompletion, and thus, I don't know what it should look like. As always, let me know what you think!
=> Possible fix for Issue #1782

js/block.js, js/blocks.js, js/widgets/rhythmruler.js
Rhythm Ruler should now be able to re-initialize (as said in #1725 ) when user changes blocks/label while widget windows is open:
I also created `this.reInitWidget` function to save up lines of code.
=> Re-init Rhythm Ruler Widget Window

lilypond/README.md
@walterbender I found the markdown in lilypond/README.md was not implemented correctly due to which the **headings** were not appearing as they should have earlier.
After fixing,
=> Fixed Markdown in lilypond/README.md

js/block.js, js/blocks.js
Status and Phrase Maker Widget Window should now be able to re-init when user changes the label or add/deletes a block inside the widget clamp.
Let me know what you think!
=> Re-init Status and Phrase Maker Widget Window

js/block.js, js/blocks.js, js/widgets/modewidget.js
Mode widget should now adhere to the new design of widget windows. A continuation base on @Bottersnike 's design. I've also added the re-init functionality when label was changed and/or block is added/removed:
Feedbacks are appreciated!
=> Refactor Mode Widget to Widget Windows + Re-init Functionality

js/block.js
Context wheel remains open after pressing the duplicate button. 
Fixes #1984
=> Not setting the display to none on duplicating.

js/widgets/meterwidget.js, js/widgets/widgetWindows.js
This should fix #2057 , where the introduction of `this.onmaximize` caused the fullscreen button functionality to misbehave when returning to unfullscreen mode.
=> Fix regression on fullscreen button for widget windows

js/block.js, js/blocks.js, js/widgets/temperament.js
Temperament widget should now adhere to widget windows design. However, this is still a work in progress PR, as the note info seem to hide on the edges when clicked:
Thoughts?
=> Refactor Temperament Widget on Widget Windows + Re-init Functionality

js/block.js, js/blocks.js, js/widgets/timbre.js
Timbre widget should now adhere to the new widget windows design:
=> Refactor Timbre Widget to Widget Windows + Re-init Functionality

js/activity.js
As discussed with @AndreaGon  , load animation should not be  called in doAnalytics .
It is causing infinite loading animation .So, removed it from that patch.
=> #2067 Animation removed from statisics

js/turtle.js
This should fix #2047. The container of the mouse should be rotated instead of the actual mouse image.
=> Rotate Mouse Container instead of Image

js/activity.js
This commit disables keyboard input while MB loads to prevent unexpected side-effects as mentioned in #800 
This is the console log showing keyboard disable before loading and enable after loading.
=> Disabled keyboard input while MB loads

css/activities.css
I've added z-index so that widgets in fullscreen mode can see printed message, as said in #2018
=> Add z-index for printed text

js/activity.js
It gets into infinite loop of loading animation when I chose a plugin .
So , I removed **doLoadAnimation();**
@walterbender  . Please review this.
=> Animation removed from loadPlugin

js/turtle.js
Mouse (avatar) image is cropped when rotating mouse using the setheading block. I've changed the code from 'this.bitmap.orientation' to 'this.container.orientation'.
=> Small Fix Regarding Cropped Avatar Img when used Set Heading

gulpfile.js
There was an unused **const cleanCSS** package. I have removed its declaration from _gulpfile.js._
This will reduce some overhead time for the compilation of the code.
=> Fixed Gulpfile.js

js/logo.js
@walterbender  In this PR, due to a spelling mistake , the timber widget  was not running.
I have fixed the typo. Please take a look.
=> fixed typo in timer

js/widgets/help.js
- After introductory help regarding palette buttons and toolbar, go through block help of all blocks.
- Beginner blocks are shown first.
- (WIP) Showing more info regarding each block like : Whether or not the block is beginnerMode or not and incorporating a show button which opens up the palette which contains the block.
- Fixes #1670
=> Feature: Cycling through block help after introductory help 

js/blocks.js, js/utils/utils.js
=> close widgets when sending the blocks to trash

js/widgets/pitchtimematrix.js
I've created a new function that generates the notes and note-values from the `rowLabels` and cell attributes (from "alt" attribute) in a row.
Now, I've called this before playing and saving. This fixes #2165.
It removes the task of maintaining the `_notesToPlay` list and now has only 18 references, previously it had 33.
=> Generate notes to play/save on the fly

js/widgets/pitchtimematrix.js
@pikurasa This fixes #2051. The repeats were being skipped because the IDs of note blocks inside repeat blocks were getting augmented and so weren't producing a match.<br/>
For example, in
the block IDs were like
The IDs were getting added to a larger number. I fixed the comparison by comparing the trailing characters only, which would then match.<br/>
I've removed the sort when the phrase maker matrix is created and it contains note blocks. This is because we might want to see the corresponding note in the matrix when the note is part of some other block, e.g. `action`. Also, this could be a step towards being able to change the corresponding note from the phrase maker itself, which would be reflected on the blocks. However, this feature isn't added yet. Irrespective, we can sort the …
=> Fixed issue of notes being inside repeat block in phrase maker

index.html, js/activity.js, js/toolbar.js, js/turtle.js
There are a few things up for discussion:
- As per discussion in https://github.com/sugarlabs/musicblocks/issues/2143#issuecomment-606122383 , I've added the button to the Aux menu. We can add it alongside clean, collapse buttons. 
Also if the aux menu is decided, is the position correct or it needs changing?
- Does the icon work? In the icon library we use, I couldn't find any other suitable icon for wrapping. We can use a custom one if this doesn't seem apt.
- Do we want this as an advanced mode option?
I think we can discuss these points and make changes accordingly, if any.
- Regarding the feature, by default the wrapping is turned on, turning it off implements the previous logic of turtle movement. ( Before #2169 was merged )
- Also there needs to be an indication to the user if the …
=> Add wrap button to aux menu

.gitignore, gulpfile.js
I've fixed some changes that were causing error on running gulp after merging #2116 
- Converted `gulp.task`  to function for `prettify` and `validate`.
- Converted rest of the functions to arrow functions as part of #2198 
Also added `package-lock.json` to  `.gitignore` as we don't want contributors to commit their `package-lock` file.
=> Fixed gulpfile and gitignore

js/blocks/EnsembleBlocks.js, js/protoblocks.js
- Added a third property, `bool` apart from the currently existing true/false.
- This property can be used for constructing `one-argument boolean-output` e,g found mouse block
- Fixed #2210
=> Additional `bool` property for flows.left 

js/block.js
Hi, I have made changes to this file most of which is `var` to `let`. I also tested the changes to make sure nothing breaks. I had to leave some declarations with `var` because of their global use.
I also noticed something I think is a mistake on line `3289` of the current version and line `3272` of this commit. The variable `selectedNote` is declared and assigned a value but never used. I think this variable is meant to be  `selectednote`. Because if you look in the current version, within the same scope on line `3306`, there is a passing of an argument `selectednote` to function `piemenuPitches()` which I believe should be the value defined for `selecteNote`. If you could please look at it. 
There were also place I moved the variable declaration to a more global location within the same …
=> let there be let

js/blocks/PitchBlocks.js
Fixes issue mentioned in https://github.com/sugarlabs/musicblocks/pull/2207#issuecomment-610743945
=> Add transposition definition

js/blocks/DrumBlocks.js, js/logo.js
Fixes #2162. Previously, if there was a "drum style" set for a note block, it wouldn't check whether it also has an "instrument name" set. The issue originated due to this; here both of them were set.
I've added a case check to find if there is a `settimbre` block before the lowest `setdrum` block among the note block's parent blocks. If the case is found to be true, the drum won't be played, rather the synth with the set instrument would be played.
=> Fix set drum overriding set instrument issue

js/logo.js
Fixes #2228.
I found that the `SynthVolumeBlock` in `VolumeBlocks.js` returns `synthVolume` for a particular synth. However, `setMasterVolume(...)` in `synthUtils.js` updates `instruments[..][..].volume.value` and not `synthVolume`. I've added `synthVolume` update in `_setMasterVolume(...)` in `logo.js`.
@pikurasa "Set Master Volume" now sets the synth volumes across the canvas. I've tested for your test case.
=> Update all synth volumes on encountering "set master volume" block

js/block.js
decrement function will work even when cblk2 : null
This allows user to decrement values in pie menu when the block is not connected to another.
=> handles cblk2 is null error

js/block.js
Fixes #2236. However, it's not just the `scaledegree` broken that would break it's clamping block on collapsing: same thing would happen for `pitch`, `hertz`, `steppitch`, and `pitchnumber blocks too`. The bug comes out of a trivial variable scope issue.
=> Fix broken note block collapse

js/utils/synthutils.js
This is possibly the last fix required for synthutils.
Error:
vibrato, distort, tremolo, phaser, chorusEffect and neighbourEffect are all undefined in this scope. 
I've reverted their definitions to use `var` instead.
=> Fix errors in synthutils

js/block.js, js/blocks/RhythmBlocks.js
null was being pushed to queue .(when both "on strong "and "on every beat" were  #used).
this can help until we look for better "on beat" blocks
=> fixes issue #1898

js/blocks/MeterBlocks.js, js/logo.js, js/widgets/meterwidget.js
#2253
-meter widget will have default beats when we open 
-if no strong beat block is used default values will be considered as strong beats(. but, to do some action on strong beats you would have to use strong beat blocks anyway  )
=> add default strong /weak for meter block

js/blocks/PitchBlocks.js, js/utils/musicutils.js
- Defined a new variable `deltaSemi` alongside `deltaOctave` which looks for changes in Octave that we play and adapts according to the key selected.
- `deltaOctave` calculates changes in reference octave which occur a semitone before the key selected.
- Fixes #2238
=> Octave calculation fix for scale degree block (nth modal pitch)

js/utils/musicutils.js
- add an alias for `minor` in MUSICALMODES alongside `aeolian`. Both produce the same result but this provides more flexibility.
- Fixed #2237
=> add minor to MUSICALMODES

js/palette.js
executing showmenu() "after" all visible palettes are closed .
this fixes a issue mentioned  in pr #2060  (https://github.com/sugarlabs/musicblocks/pull/2060#issuecomment-577365620),
continued from #2052
=> palette scroll issue

js/utils/musicutils.js
- This patch covers most cases of Accidental export issue to lilypond. There are a few corner cases related to E<->F and B<->C keys.
- Those issues will be addressed separately. ( Part of my discussion with @pikurasa )
=> Sharp and Flat preference for building scale

js/activity.js, js/blocks.js, js/blocks/MediaBlocks.js, js/logo.js, js/turtle.js, js/turtles.js
This branch is forked from [meganindya/musicblocks/turtle-component](https://github.com/meganindya/musicblocks/tree/turtle-component) and contains commits pushed on that branch, so, should be merged after #2312.
=> Remove deprecated content and rework on accessibility of variables in Turtles

js/utils/musicutils.js
Usually, empty positions in MODE_PIE_MENUS are denoted by a single space : " "
In the case of 7b, it was "" without the spaces. 
- Fixes #2335
=> fix regression in mode pie menu

js/turtles.js
`getTurtleList()` was replaced by `turtleList` (`getter`) - missed that during merge conflict resolving.
=> Fix regression in Turtles

js/blocks/ExtrasBlocks.js, js/blocks/PitchBlocks.js, js/notation.js
This is a partial fix to #2326 (It addresses the regression for using the Print block for lyrics in Lilypond output but does not yet address the regression with the Hertz block.)
@meganindya Am I using the notation syntax as you intended?
=> Add markup for print block

js/widgets/musickeyboard.js
I am using the web Midi api available on https://www.w3.org/TR/webmidi/ 
to communicate with a physical midi keyboard ,
I have added a button(MIDI) in the music Keyboard widget , (to be pressed once connected with keyboard ) ,I would like to add a svg for this button also .
Currently this works with alphabet pitches (only FLATS ) u can use this keyboard for testing -
[midi (1).zip](https://github.com/sugarlabs/musicblocks/files/4741160/midi.1.zip)
=> Add MIDI compatibilty (usb)

js/blocks/SensorsBlocks.js, js/logo.js
Implemented the correct way to interpret pitchAnalyser.getValues() .
=> PitchAnalyser

js/activity.js, planet/js/Planet.js, planet/js/Publisher.js
=> add suggested Tags when publishing

js/activity.js, js/palette.js
=> improve Search

js/block.js
#2301 added a pie menu for the beats per minute block. It should now look like this:
=> added pie menu for bpm

js/SaveInterface.js, js/logo.js, js/toolbar.js, js/utils/synthutils.js
#1744
ogg => chromium 
wav => firefox
: using MediaRecorder api (https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder)
we can remove Recorder.js library if this works .
=> recorder (save as wav/ogg) 

js/activity.js, js/palette.js
this functionality was lost when we changed palette code.
this is different than issue mentioned in #2466
=> close search when clicked outside

js/turtleactions/PitchActions.js
- The misbehavior of a ternary expression led to incorrect calculations of octave.
=> fix regression in nth modal pitch

js/blocks/MeterBlocks.js, js/turtleactions/RhythmActions.js
=> fix reference error

js/logo.js, js/turtle-singer.js
rerun flowBLock functions connected to "pitchHertz" / "currentPitch"
=> update pitchHertz/currentPitch arg blocks

js/blocks/MediaBlocks.js
Fix a typo from "medain" to "mediain" allowing the play back media block to accept a load file block as an argument. Now when a .wav file is imported to a load file block used as an argument for a play back block, the sound file is played.
=> Allow 'play back' block to accept 'load file' block

js/utils/utils.js
The issue #2574 finds it's fix in here, the error was because the code previously used deprecated methods.
=> fixing the regression with camera block error

js/widgets/widgetWindows.js
In continuation of #2656 
The `js/widgets/widgetWindow` port to ES6.
=> Widget Window port

js/widgets/oscilloscope.js
In continuation of #2656 
and part of fix as proposed in #2609 
@meganindya the `js/widgets/oscilloscope.js` is now completely cleaned up and no traces of `var` or `that` were there.
Only functions needed some porting, So I did that accordingly.
pls review.
=> Oscilloscope Cleanup

js/widgets/pitchslider.js, js/widgets/status.js
In continuation of #2656
and part of fix as proposed in #2609
@meganindya `js/widgets/status.js`  and `js/widgets/pitchslider.js `are now completely cleaned up. No traces of var or that were there.
Only functions needed some porting, So I did that accordingly.
pls review.
=> PitchSlider and Status port to ES6

js/widgets/help.js
In continuation of #2656
and part of fix as proposed in #2609
` js/widgets/help.js` is now completely cleaned up.
=> Help.js port to ES6

js/blocks.js
=> adding classes to blocks.js

js/activity.js, js/boundary.js
=> adding classes to boundary.js

js/languagebox.js
=> adding classes to languagebox.js

js/widgets/help.js, js/widgets/widgetWindows.js
fixes #2690
post changes, the behavior:-
=> Help widget fix

js/widgets/oscilloscope.js
Fix for one of the files mentioned in #2629.
`widgets/oscilliscope.js` was mostly up to date with ES6+ syntax. There was just one place where I found we could use the newer template strings syntax instead of the older one.
Please let me know if you have any further suggestions. Thanks.
=> fix(widgets): Ported widgets/oscilliscope.js to ES6+ syntax 

js/activity.js, js/piemenus.js, js/widgets/help.js
=> adding classes to widget/help.js

js/widgets/help.js
The Tour window upon loading at the inception, showcases regression. 
The regression arises, as the current method of calculating height of help widget is dynamic
`widgetWindow.getWidgetBody().style.maxHeight = ${0.75 * canvasHeight}px;`
Initially canvasHeight is 0 when the DOM is loaded
To solve, 500px is the threshold
This PR solves the aforementioned minor regression
=> Minor regression with rawgit

js/activity.js, js/toolbar.js
=> adding classes to toolbar.js

js/widgets/widgetWindows.js
Scrolling in any widget window leads to errors in the console.
The issue originated from `widgets/widgetWindow`, closer inspection revealed that this file's porting to ES6 done in #2722 had several other issues.
This PR aims to fix bugs, properly port to ES6 and add jsDoc style documentation for `widgetWindow` .
As always, please share feedback and suggestions. Thanks
=> Refactor, Documentation and Bug Fix: widgets/widgetWindow

.eslintrc.json, .github/linters/.eslintrc.yml, js/js-export/ASTutils.js, js/js-export/export.js, js/js-export/generate.js, js/js-export/interface.js, js/js-export/samples/sample.js
Fixes #2757.
- Fixed method calls for `random`, `one of`, `distance`
- Fixed getters in JS generation: `X`, `Y`, `HEADING`, `PENSIZE`, `SHADE`, `COLOR`, `GREY`
@pikurasa `Math.random(2, 5)` is the JS way of doing random. In MB we actually have wrappers around the number actions, in a class called `MathUtility` in `utils/mathutils.js`. Hence, the call is `MathUtility.doRandom`. Added that to the JS Editor documentation as well.
=> Fix JS Editor bugs for some number, graphics, pen blocks

js/toolbar.js
In reference to #2629,
Classes were added in #2648 . However, a function was not updated to the ES6 arrow function.
=> Update a function to ES6 Arrow Function in js/toolbar.js

js/widgets/phrasemaker.js
In the Phrase Maker upon clicking on the play button, ideally sound should start playing and it should turn into stop button. Either upon clicking on the stop button or when the sound has finished playing the stop button should turn into the play button again.
Upon clicking on play button, sound starts playing but it does not turn into stop button
- Upon clicking on play button sound starts playing and it turns into stop button
- Upon clicking on the stop button while the stop is playing, the sound stops playing and the stop button turns back into play button
- When the sound has finished playing, the stop button turns back into play button
=> BugFix: Phrase Maker - play stop button

js/turtle-painter.js
Implements no wrapping in graphics in middle of `fill` block or between `begin Fill` and `end Fill` blocks.
=> No wrapping in middle of fill

js/widgets/statistics.js
=> refractor:widget/statistics-lint, prettify and documentation

.eslintrc.json, js/widgets/help.js
=> Refactor: widgets/help - lint, prettify and documentation

js/widgets/meterwidget.js, js/widgets/widgetWindows.js
This PR does the following
- fixes sound playing indefinitely bug when reloaded while playing
- enhances fullscreen mode for this widget
- adds jsDoc style documentation
- fixes linting issues
- prettifies code
Related Issues #2767, #2630, #2609 
When the sound is playing and the widget is reloaded with new settings then the widget reloads but the sound does not stop playing and it plays indefinitely. Even closing the widget does not stop it. The ideal behaviour should be that the sound should stop playing when the widget is reloaded.
Please keep audio on while playing the video below to notice the bug.
https://user-images.githubusercontent.com/39027928/105640365-9eb0d000-5ea3-11eb-8ad2-4a2653117f28.mov
Fullscreen mode does nothing, the extra space in fullscreen mode is not utilised in a …
=> BugFix and Enhancement: widgets/meterWidget

js/blocks/WidgetBlocks.js, js/widgets/rhythmruler.js
=> Porting  ES6 widgets/rhythmruler.js

js/blocks/WidgetBlocks.js, js/widgets/temperament.js
Issue reference:- #2767, #2630, #2609
When stop button is pressed, temperament widget continues to play the previous value of the pitch in conjunction to the pitch values from the start. Notice the erratic behavior in the video below.
https://user-images.githubusercontent.com/50985033/105727096-bbefa800-5f50-11eb-84cc-5f434318090a.mp4
https://user-images.githubusercontent.com/50985033/105726329-f73da700-5f4f-11eb-921f-36f931a82432.mp4
https://user-images.githubusercontent.com/50985033/105726553-323fda80-5f50-11eb-8819-fb5ed62c73d6.mp4
As is, this port didn't produce any errors for me on my system locally, however if any error/erratic behavior is produced due to this port, do let me know. Thanks
=> Temperament BugFix and ES6+ port

js/widgets/widgetWindows.js
https://user-images.githubusercontent.com/39027928/106090439-2b7fb600-6150-11eb-8100-b74f7c496c2a.mov
Event Listeners created on document level by the widgetWindow persist after the window is closed, ideally these should be removed when the widgetWindow is destroyed. This PR also fixes this issue.
https://user-images.githubusercontent.com/39027928/106097500-6e945600-615d-11eb-9785-9d00d208c547.mov
https://user-images.githubusercontent.com/39027928/106097516-72c07380-615d-11eb-97bb-5aa1d7eacd2b.mov
=> Feature: dragging windows to top to maximize - windows/widgetWindow 

js/widgets/widgetWindows.js
In some widgets which has interactive elements in the widgetBody show some strange behaviour for mouse events in full screen mode. This PR fixes these issues.
In Mode widget, unable to select items in fullscreen mode
In Phrase maker, pie menus don't appear upon clicking on note values
=> BugFix: strage behaviour for mouse events in some widgets

js/widgets/modewidget.js
This PR does the following:
1. Fix sound bug - Sound keeps on playing even after the widget was closed.
2. fixes linting issues
3. prettifies code
Reference : #2767, #2609
The sound does not stops when the widget is closed. This can be seen in the video attached.
https://user-images.githubusercontent.com/66181127/105908169-e96d4c00-604b-11eb-90b6-8dd5b51d71e5.mov
https://user-images.githubusercontent.com/66181127/105908218-f5f1a480-604b-11eb-8368-360a28d6fd31.mov
=> BugFix and Refactor : widget/modewidget.js

js/turtle-singer.js, js/turtleactions/PitchActions.js
Fixes #2318 
Please mind the notes, visual appearance might differ depending upon the editor used.
Please mind the notes, visual appearance might differ depending upon the editor used.
- Odd inversion of C4, Step -1(B4) about D4  -> F F#
- Scalar Inversion of B4, Step -1(A4) about G4 -> E F
So all three inversions, even, odd and scalar seem to work fine now with scalar block inside invert.
Please share feedback and reviews. Thanks
=> BugFix: Scalar step behaving incorrectly inside invert

js/widgets/pitchslider.js
=> refractor/pitchslider:fixed linting errors and added js docs

js/blocks/WidgetBlocks.js, js/widgets/rhythmruler.js
Issue reference:- #2779 #2767, #2630, #2609
Described in detail in #2779 
_**Video description of the bug:-**_
https://user-images.githubusercontent.com/50985033/106359562-9b9d6000-6339-11eb-8218-65f6dfb64946.mp4
_**Obviation of bug, post fixes:-**_ 
https://user-images.githubusercontent.com/50985033/106359598-bcfe4c00-6339-11eb-9462-c49419f38127.mp4
This PR has also added detailed JSDoc, lint & prettified the file a little bit.
=> Rhythm Maker solving regression, linting & jsdoc

js/turtles.js
=> refractored: turtles.js JSDoc, lint and prettify

js/block.js, js/blocks/GraphicsBlocks.js, js/piemenus.js, js/turtle-painter.js
Implements #2750 
The block is made a clamp block to avoid ambiguity as the wrapping tendency is also affected by the turtle wrapping that could be set in the toolbar globally.
- Basic functionality of wrap block, 
wrapping is on globally (from the toolbar) but if the wrapping is turned off in the `wrap` block then the statements within it don't wrap
https://user-images.githubusercontent.com/39027928/106382544-4c613900-63e6-11eb-8348-65f17261bc3d.mov
- In the demonstration below, the horizontal rectangle is affected by global wrapping, vertical rectangle is affected by the settings of `wrap` block.
https://user-images.githubusercontent.com/39027928/106382552-597e2800-63e6-11eb-9eee-68ae13a2edd7.mov
- Wrap block inside fill
Wrapping should not happen in the middle of fill, even if wrapping …
=> Feature: Wrap Block

guide/timbre4.svg, guide/timbre5.svg
While solving #2591 unknowingly, certain erroneous svgs were generated. Couple of svgs in the guide pertaining to timbre widget were erratic. SVGs were namely, `timbre4.svg` and `timbre5.svg`
Behavior before :- 
and 
they've been fixed in this PR.
=> timbre erratic svgs update

js/piemenus.js
In the mode pie menu of custom mode block we could play the preview of the currently selected option but there are some bugs associated with it.
- The play button could be clicked multiple times consecutively, this leads to some strange behaviour. Ideally the play button should disable for the period when sound is playing.
- On click the play button it turns from black to white but it does not go back to black even after the sound has finished playing, ideally it should be white for as long as the tune is playing and then it should go back to its original colour.
- On closing the piemenu when the tune is playing it results in an console error.
=> BugFix: custom mode block mode preview

js/widgets/temperament.js
Minor UI Improvement: Related to #2767 
This PR resolves a UI inconsistency in the temperament widget in which several buttons would have the cursor as "pointer" on mouseover while others did not. Also, the text in various buttons was not vertically central-aligned. Specifically, once clicked on the "Preview" button in the "Equal" and "Ratios" tab, the appearing "Back" and "Done" buttons had this issue:
Also, the "Clear" button in this widget did not have a pointer cursor. Finally, all button-texts were vertically central-aligned.
After resolving these, final result looks like this:
=> Update UI of Temperament Widget

js/js-export/API/DictBlocksAPI.js, js/js-export/API/DrumBlocksAPI.js, js/js-export/API/GraphicsBlocksAPI.js, js/js-export/API/IntervalsBlocksAPI.js, js/js-export/API/MeterBlocksAPI.js, js/js-export/API/OrnamentBlocksAPI.js, js/js-export/API/PenBlocksAPI.js, js/js-export/API/PitchBlocksAPI.js, js/js-export/API/RhythmBlocksAPI.js, js/js-export/API/ToneBlocksAPI.js, js/js-export/API/VolumeBlocksAPI.js, js/js-export/ASTutils.js, js/js-export/constraints.js, js/js-export/export.js, js/js-export/generate.js, js/js-export/interface.js, js/js-export/samples/sample.js
=> Lint, Pretify js/js-exp files

js/widgets/temperament.js, js/widgets/tempo.js
Issue Reference: #2767 
In the Arbitrary Tab of the Add Pitches section in the Temperament Widget, I noticed that once if you hover on the outer circle before the animation is completed, it remains incomplete forever.
Before:
https://user-images.githubusercontent.com/60084414/106860648-afa2e200-66ea-11eb-9dfb-63355fde9680.mp4
So, I just added a Timeout on the event listener of mouseover event so that it activates only after the animation is completed.
After:
https://user-images.githubusercontent.com/60084414/106860850-f7296e00-66ea-11eb-8960-1cf0f49db968.mp4
Also, in the Tempo widget, it showed "Play" on the Pause button and vice-versa.
This was fixed in this PR.
Finally, there was no error shown on clicking the down button when the BPM is 30 or clicking the speed up button when the BPM …
=> Fix Bug in Arbitrary Edit Tab and improvements in Tempo Widget.

js/widgets/jseditor.js
=> widgets/jseditor.js: Linting and Prettify

js/utils/platformstyle.js
Issue Reference: #2767, #2609 , #2630
=> utils/platformstyle.js: Pretiffy, Linting and JSDoc Documentation

js/piemenus.js, js/turtleactions/IntervalsActions.js
Set key and define mode blocks implement movable do in music blocks but there seems to be some issues specially when in custom mode.
Issues -
- When execution flows through the define mode block we get a console error.
- The output is not as expected when the selected mode is different from modes in the group 7 including custom mode. First set to major mode from group 7 and play, then select any another mode from any other group the output stays the same. The video below demonstrates this issue with custom mode.
https://user-images.githubusercontent.com/39027928/107147460-4209e680-6974-11eb-9053-c49de17409b7.mov
The expected output for the custom mode in the video above being
The video below demonstrates how only modes from group 7 give the correct output …
=> Fixing movable do - set key not working as expected

js/notation.js
=> notation.js: Linting and prettify

js/utils/munsell.js
=> refractor: utils/munsell.js: linting, prettify

js/widgets/widgetWindows.js
Issue Reference: #2808 
This PR introduces a feature to maximize the widget window by double-clicking the top-bar of the widget window. This is necessary as every Operating system has this feature and thus, people are used to this.
https://user-images.githubusercontent.com/60084414/107497055-0f503000-6bb8-11eb-92f2-cddb29be2051.mp4
Also, while the feature of dragging the widget to the top and maximizing was very useful, there was no indication for a new user that this feature was present. Thus, I added a white overlay on the event of the widget window reaching the top so as to indicate to a user that this event will maximize the widget window. This will enhance the experience of dragging and maximizing the widget window.
https://user-images.githubusercontent.com/60084414/107497308-6a822280 …
=> WidgetWindows: UX Enhancement

js/widgets/status.js
Issue Reference: #2767, #2808
Before:
After:
On Maximizing the widget,
Before:
https://user-images.githubusercontent.com/60084414/107776768-00a87b00-6d68-11eb-8158-fac65c9a8547.mp4
After:
https://user-images.githubusercontent.com/60084414/107776802-0c943d00-6d68-11eb-8aa7-0cd3f514a65c.mp4
=> widgets/status.js: Improved UI of status widget

js/widgets/pitchstaircase.js
Issue Reference: #2767 
The sound kept playing even after closing the pitch staircase widget.
Before:
https://user-images.githubusercontent.com/60084414/107670483-c9c75c00-6cb8-11eb-9d54-34f3849ef406.mp4
After:
https://user-images.githubusercontent.com/60084414/107671443-d9937000-6cb9-11eb-83f3-e65d4403f21f.mp4
=> pitchstairecase Bug Fix: Sound keeps playing even after closing the widget.

js/blocks/WidgetBlocks.js, js/widgets/musickeyboard.js
When hertz or pitch blocks are added to the music keyboard widget through the widget window then ideally the newly generated blocks should connect and align properly with the existing blocks in the clamp of the widget block but this it shows regression.
https://user-images.githubusercontent.com/50985033/107875014-6ff6aa00-6ee3-11eb-8012-3b63da732e71.mp4
https://user-images.githubusercontent.com/39027928/107947235-2330d300-6fb8-11eb-84a7-f1b89da8a94e.mov
References
- https://github.com/sugarlabs/musicblocks/pull/2826#issuecomment-776954859
- https://github.com/sugarlabs/musicblocks/issues/2839#issuecomment-778762806
=> Fixing regression in Music keyboard widget block with alignment of blocks

js/widgets/musickeyboard.js
This PR fixes the issue of generation of extra octave in music keyboard when there is a hertz block in the widgetBlock.
https://github.com/sugarlabs/musicblocks/commit/d449b0f454d1d73d943101795600d27667643d23 fixes this issue for standard auto generated values but the issue still persists for custom values as demonstrated in the video below.
https://user-images.githubusercontent.com/39027928/107997911-f4dbe380-7009-11eb-8ce5-1f96ab414e1c.mov
@walterbender
=> musicKeyboard: fix extra octave generated with hertz blocks

js/widgets/musickeyboard.js
Updated
When hertz blocks are added to the music keyboard widget then the hertz blocks get mixed up with notes. Ideally all heartz blocks should be present in the right most side arranged in increasing order of frequency. Relaunching the widget fixes this issue but that leads to bad user experience.
https://user-images.githubusercontent.com/39027928/108241317-b2cdb180-7171-11eb-8ecf-2a412a3a0714.mov
When adding pitches, leftover pitches in the current octave are skipped and pitches from the next octave are included. Ideally it should move to pitches in the next octave after exhausting the current octave.
https://user-images.githubusercontent.com/39027928/108286179-a0be3400-71ae-11eb-88bc-225a4d0183e3.mov
In the video above we already had C, D, E, F and G in the 4th octave. If a next pitch …
=> Multiple Bug Fixes and Enhancements to Music Keyboard

js/widgets/pitchstaircase.js
Issue Reference: #2808, #2767 
This PR enables scrolling in the pitch staircase widget as earlier, on the addition of more items, the widget would ultimately reach its maximum height and the earlier items became inaccessible. Also, this enables scrolling in case maximized widget due to same issues earlier.
Before:
https://user-images.githubusercontent.com/60084414/108665153-44cf1480-74fa-11eb-932a-6b40914d622b.mp4
After:
https://user-images.githubusercontent.com/60084414/108665181-544e5d80-74fa-11eb-8570-7557f3784afe.mp4
=> Bug Fix: Pitch Staircase Widget

js/widgets/oscilloscope.js
Issue Reference: #2767
In the Oscilloscope widget, the buttons of "Zoom In" and "Zoom Out" functionalities are cross-matched with their icons, i.e., the "Zoom Out" button executes the "Zoom In" process.
Before:
After:
=> Oscilloscope: Error Fix and UI modification

js/widgets/temperament.js
Issue Reference: #2767 
There were some bugs in this widget, all connected to the Play and Stop functionality.
- Firstly, if the STOP button was clicked on a certain note (let's say 3), it would not reflect that as the same in the UI. Instead, it would appear to be stopping on the next note (i.e., in this case, 4):
https://user-images.githubusercontent.com/60084414/107975089-91d45780-6fdd-11eb-87d4-1bd0b44d6ed4.mp4
- Secondly, if the widget was closed while it was still playing, the sound of the same note would still be heard (once again), even after closing:
https://user-images.githubusercontent.com/60084414/107975431-1b842500-6fde-11eb-8302-3b882ed91bbe.mp4
- Lastly, if the process was Stopped in the counter-clockwise cycle, i.e., when `this.playbackForward = false`, the stopping …
=> Bug Fix, Temperament Widget: Play and Stop not working properly

css/activities.css, js/activity.js, js/palette.js
The current version of the search-bar and its suggestion had few inconsistencies.
- Search Bar blocked some of the search icon (magnifying glass icon) and the subsequent palette icons. Also, its alignment was slightly off.
- Bullets in the list feel unnecessary.
- The search input suggestions had a different width than the search bar, which also compromised the alignment.
- The suggestions of this search bar were too cramped in the list, which lead to the addition of a new line in the case of the block names, which were comparatively longer. So some negative space was added between them.
- This list of suggestions had the same white background color as the palette beneath it. Thus, there was no differentiating between them.
These are fixed in this patch, as shown below.
Before:
After:
=> Enhanced the UI of search-bar and its suggestions

js/widgets/help.js, js/widgets/pitchslider.js, js/widgets/pitchstaircase.js, js/widgets/tempo.js, js/widgets/timbre.js, js/widgets/widgetWindows.js
This PR does the following
- Fixing issue with overlay, steps to reproduce - maximise a widget window by dragging it to the top then minimise it using the minimise icon, the overlay sticks around and could not be removed unless the widgetWindow is closed. Ideal behaviour should be that the overlay should appear only on dragging the window to the top to indicate the window could be maximised and should not stick around in after the window is minimised.
- Maximise functionality in all forms (double click, drag to top and maximise button) disabled for the help, tempo, pitch slider, pitch staircase and timbre widgets.
@meganindya
=> Fixes regression in overlay of full-screen mode and disables full-screen in some widgets

js/turtles.js
=> Bug Fix: Tooltip of Collapse Icon

js/blocks/ToneBlocks.js, js/turtleactions/ToneActions.js, js/utils/synthutils.js, js/widgets/sampler.js
- The sampler widget no longer attempts to play a sound on starting up.
- It no longer attempts to play a sound after a sample is uploaded.
- If there is no sample, the play button will not attempt to play a sound.
- The play button also becomes paused after one second of the sample is played.
=> Sampler widget no longer attempts to play a sound on load, changes to play button.

js/widgets/musickeyboard.js
After #2849, the Music Keyboard widget has two regressions:
- The lower 8 notes from G4 to C4) in the column of the grid were unclickable.
This is happening as the `for` loop (starting from line 1057 in the `makeClickable` function), the parameter `this.layout.length` is getting set to 5, after #2849, instead of 12.  Now, the error arises in the `_keysLayout` function where the notes are pushed in the layout array. So, `sortedList` is replaced by `newList` . Here,
`newList = fillChromaticGaps(sortedNotesList)` 
Thus, `newList` contains all the 12 notes whereas `sortedList` contains only the first 5 notes.
- In case when multiple notes were selected in a column, the music would stop playing and not move any further.
This regression arises as when multiple notes are selected, the `playOne` …
=> Fix regressions in MusicKeyboard widget

js/widgets/phrasemaker.js
Here is a a short video on how the issue might be reproduced.
https://user-images.githubusercontent.com/39027928/111003945-17b1ab80-83ae-11eb-93c1-9278f94faf8b.mov
When any of the cells of the row of the custom pitch is selected in the PhraseMaker widget window then leads to an error rendering the widget unusable. Even if we manage to select the cell without any errors then more errors are encountered upon either playing or saving the selections, as demonstrated in the video below
https://user-images.githubusercontent.com/39027928/111004218-9ad30180-83ae-11eb-8fdc-7bac458b94a7.mov
This PR fixes all the issues when either selecting cells of custom pitch, playing or saving the selections.
https://user-images.githubusercontent.com/39027928/111004584-52681380-83af-11eb-974a-49a862c4b46a.mov …
=> Fixes bugs in PhraseMaker with custom pitch and custom temperament

js/widgets/statistics.js
Ref #2808 
The Statistics widget takes only a very small portion of the screen in the fullscreen mode. When not it fullscreen mode the radar chart is barely visible and it would be nice to be able to utilise the extra space of the fullscreen mode to show the graph in greater detail.
Here is how it looks,
@meganindya
=> Statistics Widget: Enhancements to fullscreen mode

js/widgets/modewidget.js
Ref #2808 
The extra space in the fullscreen mode is not used in a meaningful manner for mode widget. It could be used to make the note wheel larger. This would specially be helpful for modes in non C keys.
https://user-images.githubusercontent.com/39027928/111056494-2cbd3600-84a5-11eb-98c0-eec2c09f05ce.mov
https://user-images.githubusercontent.com/39027928/111056525-832a7480-84a5-11eb-9224-d42978d6583a.mov
=> Mode Widget: enhancements to fullscreen mode

js/widgets/rhythmruler.js
The rulers overflow outside the widget window due to this after dissections some notes may completely fall outside the widget window and could not be reached.
Here is a video demonstrating the overflowing rulers issue
https://user-images.githubusercontent.com/39027928/111056863-a3a7fe00-84a8-11eb-9d7d-904d46bd2543.mov
Ref #2808 
Currently, the fullscreen mode of the widget has no meaningful functionality. For smaller notes specially notes below (1/32) its difficult to see them in the ruler so it would be helpful if in the fullscreen mode the width of the notes is increased to better utilise the extra space and interact with the rulers.
Here is how the fullscreen mode looks now
https://user-images.githubusercontent.com/39027928/111056935-642de180-84a9-11eb-9fb0-2cbb3653cf90.mov …
=> Rhythm Ruler Widget: fix rulers overflowing outside widetWindow and enhancements to fullscreen mode.

js/rubrics.js, js/widgets/statistics.js
Ref #2896 
https://user-images.githubusercontent.com/39027928/111105548-3e700d80-8579-11eb-99b8-5c9be8dd6ea1.mov
https://user-images.githubusercontent.com/39027928/111105116-3bc0e880-8578-11eb-8ab8-24ca93a853b1.mov
I could reproduce the issue for custom pitches in custom temperaments. If the is reproducible in other cases as well, please share in comments. Also the statistics widget window could not be reopened once closed, this issue has been fixed as well.
@walterbender
=> StatsWidget: Fix regression in frequency values when using custom pitches

js/widgets/rhythmruler.js
The Rhythm Maker widget does not change the PLAY button to the PAUSE button when an individual note is played. This patch fixes that and adds global locations along with prettifying the code.
Before:
https://user-images.githubusercontent.com/60084414/111164151-c975f580-85c3-11eb-83c6-0b813e541e26.mp4
After:
https://user-images.githubusercontent.com/60084414/111163762-671cf500-85c3-11eb-8dc3-7ed0a9a25fe5.mp4
Please review this and share your thoughts @walterbender @meganindya.
Thanks.
=> BugFix: rhythmruler widget does not render individual pause buttons 

css/activities.css, js/widgets/pitchdrummatrix.js
The pitchdrum-mapper widget did not have a STOP functionality which meant that whenever a user clicked the PLAY button, the sound started playing irrespective of whether it was already playing or not. Thus, if once the PLAY button is clicked, if it is clicked again, the sound would start playing from the first note again in addition to the already playing sounds. Additionally, one could not stop the sound in any way. It also started playing even when no cells were selected to be played. Also, some rows of cells along with the drum row could not be accessed without maximizing the widget in case of a larger grid, and there existed a wide gap between the control buttons and the grid. This patch solves all these issues.
The PLAY button is clicked twice in the video below, and one can notice …
=> pitchdrum-mapper: Implement Stop Functionality and enhance UI

js/blocks.js
An attempt to fix a part of #2928.
This PR fixes the regression in which the octave arg block would remain sticky with the mouse cursor upon clicking in its detached state from its parent block and would generate errors. To fix this, a condition/check is added to the `octaveNumber` method to check if the block has connections or not.
https://user-images.githubusercontent.com/60084414/116188165-8a9b9980-a744-11eb-9396-e26615dab26b.mp4
https://user-images.githubusercontent.com/60084414/116188215-a99a2b80-a744-11eb-8d95-a93586dc624c.mp4
=> Regression Fix: Add check to avoid name undefined errors

js/blocks.js
Currently, when you bring up the pie menu on a block and press duplicate, it duplicates the entire chunk that the block is part of. This is inconsistent with the behavior of "extract", which only extracts that block. The modified code changes the `this.selectedstack`  assignment in `prepareStackForCopy()` from getting the top level block to the active block.
=> "Duplicate" now only duplicates the selected block

index.html
What problem is this PR trying to fix?
If you search for "Music Blocks" in a search engine (e.g. Google), you get several relevant options. One of the options, thankfully, is musicblocks.sugarlabs.org
However, the description that is displayed in a query is a mess and could be offputting to someone who stumbles upon Music Blocks in a search. Plus, without any other descriptive words, it limits which search words would point to Music Blocks.
I don't really know if this fixes it, and cannot really test, but found the info on https://ahrefs.com/blog/seo-meta-tags/
I noticed we did not have a Meta Description Parameter as in `<meta name="description" content="Place the meta description text here.">`
This adds one.
=> Added Meta Description for SEO

js/blocks/BooleanBlocks.js, js/blocks/DrumBlocks.js, js/blocks/IntervalsBlocks.js, js/blocks/MediaBlocks.js, js/blocks/NumberBlocks.js, js/blocks/PitchBlocks.js, js/blocks/ToneBlocks.js
Fixes: #3014 
Enhanced the "help window carousel" with titles similar to other blocks, like shown below-
=> Updated "help window carousel" with title of blocks

css/activities.css
Fixes #3026 
Popup message from language select needed CSS styling.
Before
After
I made the background color, text color, and font consistent with the theme of the rest of the program.  I also adjusted the positioning of the popup and its contents so that it scales properly with viewport resizing.  Note that all popup messages are now styled accordingly.
=> add popup message style: color, font, position

js/utils/musicutils.js
For:- 
**Before:-** 
**F♯4, G♯4, A♯4, B4, C♯5, D♯5, E♯5 F♯5, G♯5, A♯5, B5, C♯6, D♯6, E♯6 is what one would expect to see**
So the transition from D#5 to F5 is where things begin to break down.
The F# through A# are skipped for some reason.
Maybe it gets confused when it does the conversion from D# to F (which it really should not be doing in F# Major)
**REASON**
F# major is broken due to a nomenclature anomaly
F# major (full, full, half, full, full, full, half) is:
F# -> G# -> A# -> B -> C# -> D# -> E# -> (+1)F#
this is the internal representation used
F#, G#, A#, B, C#, D#, E#, F#
the thing is ... E# is same as F
so the code is trying to find F in the scale (list) but the list instead has E#
improve on the "find in list". Instead of string equality if you can find logical equality it …
=> Regression Resolved

guide/README.md
**URL now points directly to the linked object.**
**Before :-** 
**[note1.svg]**
**After :-**
**[note1.svg]**
**Closed #3056**
=> Link of images in documentations

guide-zhCN/README.md, js/turtle-singer.js
Removed the WARNING when you try to play a note longer than 2 whole notes since some samples are very long.
closes #3065
=> Removed warning

guide/README.md
There were some errors in the table.
As I was working through it, however, I thought that it would probably be best to use more common examples, so these examples stick to keys with fewer sharps and flats.
I added some language that hopefully helps walk the reader through some of the tables as well.
=> Updates to set key that consequently avoid some errors

js/widgets/sampler.js
Added file type checking to the Sampler widget in _sampler.js_ because it only accepts .wav files to fix issue #3064.
Also added an error message if the user uploads an incorrect file type.
=> Added file type checking to the Sampler widget (fixes #3064)

js/blocks.js, js/blocks/WidgetBlocks.js, js/turtledefs.js, js/widgets/arpeggio.js
A class variable was inadvertently renamed, which broke the ability to override the default column value.
=> Arpeggio Widget bug

js/piemenus.js
The indexing for setting up the custom note pie menu logic was not correct. Not sure when the regression was introduced.
=> fix regression in custom note pie menu

js/piemenus.js
The format in some saved projects seems to differ sometimes from the format saved by the widget... catching all variants now...
=> some saved projects have a different format

js/blocks/PitchBlocks.js, js/piemenus.js, js/turtle-singer.js, js/turtleactions/PitchActions.js, js/widgets/temperament.js
* Add up-down notation to custom notes (See #2859)
* Fix orientation of custom note pie menu
* Use note value of 32 for standalone Hertz block (See #2410)
=> Up down notation at al.

js/utils/musicutils.js, js/widgets/temperament.js
By returning neg. cents in the frequencyToNote method, the temperament calculation can be simplified.
Also, the octave was missing for notes (0%) so the separate logic for that pathway was removed.
=> use negative cents

guide/README.md
I corrected the link-(scale degree improv) after the illustrative example that demonstrates how  Scale Degree functionality combines math and musical modifiers.
=> Corrected a wrong link in the music blocks guide

js/piemenus.js, js/turtleactions/IntervalsActions.js, js/utils/musicutils.js
It is a bit anomalous, but we should be more flexible with the arguments to setkey. This patch allows solfege (with a built-in assumption of C Major, movable=false) to be used as an argument to setkey. (Fixes #3168)
=> allow for solfege when setting key

js/palette.js
closes: #3178
Grid, show/hide block, Expand/collapse blocks buttons is now under the Palette in small screen.
result:-
=> Z-Index of Palette is added 

js/blocks.js, js/macros.js
Pallet width offset is dynamically added to macros and blocks.
=> fix blocks generating behind palette

js/palette.js
Make the Palette Body Item width and height (dimensions) responsive and flexible according to the immersing content size. 
NOTE: palBodyHeight is a fixed calculated value. 
- If the content is smaller, then resize the dimensions to fit the content. If larger than the calculated palBodyHeight value, then a scrollbar is added AND thus, the height never exceeds the palBodyHeight value. 
- In other terms, height: fit-content(palBodyHeight) 
BEFORE: 
AFTER: 
PS: @walterbender  
Thanks in advance.
=> Fixes #3184: Enhance the Palette Body-Items Element(s)'

js/activity.js
- Due to the dearth of z-index property on the input block, the z-index value of the palette body items was the only dominating value and thus, the undesirable order of elements. 
- After adding a  z-index value that is greater than that of the z-index value of palette body items, the input display block will take precedence and will be displayed on top. 
NOTE: Display Block was GIVEN A YELLOW BACKGROUND to highlight the issue. 
BEFORE: 
AFTER: 
@walterbender  Would you mind sharing some tips regarding how to quickly and efficiently navigate to the target file which has the code that contains the breaking changes/needs enhancement? Is it strange that it takes me hours to find the exact point of code that needs to be changed and a minute to make the changes?  
Thanks in Advance
=> Fix the palette-search-display block visibility issue

dist/css/windows.css, js/widgets/widgetWindows.js
RATIONALE : 
- In Smaller Screens (<= 600px) the Help Block took the entire width and height of the device. But immediately after the animation was completed, you'd have a palette on top of the Help section which isn't well reasoned/rational. 
-  In my humble opinion, the user should/would want to first take a tour and learn about the project if (s)he's a first-time user. An extra palette on top of the help section would discombobulate the user. After the user completes the intro to the project or skips it, then along with all other blocks, the palette must be visible. That was the intent behind these changes. 
- Now in all viewports, the help block when focused, has the highest z-index. 
BEFORE: 
AFTER: 
@walterbender  I appreciate it.
=> Enhancement: Enrich the Help-Block UI for smaller Viewports

css/activities.css, js/widgets/help.js
RATIONALE:
- The Content of the Help Block's Body Div wasn't quite appealing to the eyes.  The icons that were dynamically added weren't inside a separate container. 
- The Code was in pre-ES6 syntax which made it quite illegible and indecipherable. Particularly the dynamically generated elements and their attribute values. 
COMMIT DESCRIPTIONS: 
- The First commit essentially contains the changes that are confined to the realm of code upgradation. The majority of the code is now in ES2015 and beyond.  
(String concatenation are now replaced with modern string literals. InnerHTML is now 
replaced with the insertAdjancentHTML method)
- The second commit contains the structural and stylistic changes for a new container which was only created to store the icons together. 
BEFORE: 
AFTER: …
=> Enhancement : Enhance the UI of Help Block's Body

js/activity.js
I fixed the frame resizing issue that clears project after  saving as PNG on chrome
issue  --  #3034
https://github.com/sugarlabs/musicblocks/issues/3034
@walterbender 
I will also love to know if you will suggest the restriction of this changes to chrome browser alone or it's okay like this.
=> Fix  project remove after saving as png  [Chrome] #3034

js/activity.js
The following pull request fixes issue #3066 dismissing an error message removeArrow() is not found
=> fixes issue #3066 - to remove arrows on dismissing error message

planet/js/GlobalPlanet.js
- RATIONALE: 
- If in the global project container, for some reason, data couldn't be fetched then according to the error handling process, a container was rendered which had an error message with a request to reload the page. 
- Same was true if there were no cards that matched the selected tags/queries. 
But in some cases like a slow internet connection, the message was delivered and it persisted despite the rendering of all the projects after a while. So the container displayed both the error message and the projects that matched the query/tags AT THE SAME TIME, which is irrational. 
- To solve the problem a new method was added which, before rendering the projects, checks if the error message is still displayed on the screen. If it is, then it is removed from the DOM before the …
=> Bugfix: Fix the redundant display of Offline/No project message 

js/lilypond.js
Here is a potential fix for issue https://github.com/sugarlabs/musicblocks/pull/2843
I fixed a regression in the lillypond code by correcting the wrongly generated syntax \< \> [ Crescendo start syntax and the Decrescendo start syntax ].
here is a sample MB project to test this
[dynamicstest.zip](https://github.com/sugarlabs/musicblocks/files/11175239/dynamicstest.zip)
Now using decrescendo and crescendo in any MB project wont be an issue as one can generate the lillypond code without error
@walterbender I will love to know your view about this
=> Fixed regression in lillypond- corrected the wrongly generated syntax

js/planetInterface.js
RATIONALE: 
- The 2 button containers TOP AND BOTTOM mustn't be visible when planet is displayed. The planet HTML page is loaded via Iframe. But after rendering, whenthe viewport was resized, the button containers would become visible on top of the planet page. 
- In order to fix this problem, a z-index was added.
BEFORE:
=> Bugfix: Fixing the redundant display of buttoncontainers (TOP&BOTTOM). 

js/background.js
The tab parameter has been replaced with details to reflect the current API syntax for both Chrome and Firefox.
=> Updated background.js

js/activity.js, js/blocks.js
For issue #3317:
This also worked on touch device 
Now, blocks are deleted instantly after coming into the trash area, and the red color of the trash boundary is set to be in its original color after the event.
=> Solving rendering problems during the trash events

dist/css/windows.css, js/widgets/musickeyboard.js, js/widgets/phrasemaker.js, js/widgets/widgetWindows.js
For issue #1144 
[WidgetWindowScrolling.webm](https://github.com/sugarlabs/musicblocks/assets/81846020/72efae2f-6155-4e2d-bbf4-274eb8943cdf)
=> Implementing scrolling on the phrase maker

js/SaveInterface.js
This pr fixes the issue #3376  
1. I removed the `returnValue` property from the `saveInterface` class as it is deprecated and the `preventDefault` property is sufficient to prevent the default behavior during the `beforeunload` event.
2. changed the `.bind` method to `.on` since its deprecated in jQuery 3.0 version
=> Removed the deprecated returnValue property from the saveInterface class 

js/utils/utils.js
This PR fixes the issue #3374 
The warning is because the condition args === [] will always return false as JavaScript compares objects by reference, not by value. An empty array is an object, and  using === to compare objects, it checks if they refer to the same object in memory.
To fix this, I used  its length is 0  to determine if it's an empty array instead of using args===[ ].
@walterbender
=> fixes Warning issue in utils.js

js/widgets/jseditor.js
In js webeditor while calculating height in "calc(100vh - ${64 + 33}px" closing parenthesis is missing which can effect the layout of JavaScript editor widget.
=> fixed missing closing parenthesis

dist/css/windows.css
fixes #3366
This PR adds Red color to 'close' button and Green color to 'rollup' button. It helps in enhancing UI and increasing Accessibility.
https://github.com/sugarlabs/musicblocks/assets/109718740/3d9bd2fd-2344-4cfb-a4ae-d612dabaf9f6
=> added color to close and rollup buttons when hover

js/logo.js
This PR fixes issue #3381 and refrences PR#3382 
if the browser supports the Object.keys method. it uses Object.keys to get an array of the object's own enumerable property names, and checks if the length of that array is zero. If  object is empty the function returns.
If the browser does not support Object.keys, it uses a loop to iterate over the object's properties. It sets isEmpty to true initially and changes it to false if it finds any property. The loop breaks if a property is found. After the loop if isEmpty is still true, means  object is empty, and the function returns.
@walterbender
=> fixes error in logo.js

js/blocks/ActionBlocks.js, js/blocks/BooleanBlocks.js, js/blocks/BoxesBlocks.js, js/blocks/DictBlocks.js, js/blocks/DrumBlocks.js
#2630 
Since this process of adding JS doc style to the whole process is very time consuming as I have to understand parts of the codebase, I am adding JS Doc style file by file to keep it error free.
Added the JS Doc style in the following files:
1. Action Blocks js
2. Boolean blocks js
3. Boxes blocks js
4. Dict blocks js
5. Drum blocks Js
Kindly review it.
@walterbender  @meganindya
=> Updated ActionBlocksJs with JsDoc style

index.html, planet/index.html
This PR fixes #3401 
There is incorrect use of label tag  as  the "for" attribute of <label> tag must be equal to the id attribute of the related element to bind them together.
=> fixes incorrect use of label tag

css/activities.css
Fix  hidden deprecated warning which appeared in the console
=> fix hidden deprecated warning

js/js-export/export.js
Fixes #3286
This PR fixes the problem of undefined TypeError that occurs when the code in the JSeditor is ran twice as shown in the image below 
Current Behavior :-
When the code in the JSeditor is ran the second time a TypeError is thrown in the console of `removeEventListener` being undefined.
Fix :-
This error occurs because there's no check in place to ensure that the `eventlistener` exists before removing it.
Hence I add a simple if block to ensure the `removeEventListener` runs only if `eventlistener` exists. 
@walterbender please review this PR and let me know if any changes are needed!
=> Fixes #3286 - TypeError while running the JavaScript code in the editor

js/README.md
Fixes #3437
This PR fixes the spelling mistakes in README.md file of js folder.
please review this PR @walterbender sir
=> Fixestypo in readme file of js folder

js/js-export/export.js
This PR fixes #3435 
I have use Array.isArray(args) to ensure that args is an array and args.length === 0 to check wheather it is empty or not .
so
(Array.isArray(args) && args.length === 0) checks both aspects: whether args is an array and whether it is an empty array.
=> fixes warning issue in export.js

js/blocks/IntervalsBlocks.js
This pull request resolves issue #3443, which concerns the missing description for the Interval Number Block in the Music Blocks tour. The absence of a description hinders users' understanding of this important component in the music creation process.
=> Fixing Description for Interval Number Block in Music Blocks Tour - issue #3443

sw.js
fixes #3449 
This modification ensures that the updateCache function is only called with a complete (successful) response, preventing the TypeError related to partial responses.
=> fixes failure on attempting to add an item to the cache

js/widgets/jseditor.js
Fixes: #3454
This PR fixes the size of theme button in javascript editor. making it sync with the size of other buttons 
kindly review this @walterbender sir
=> fixes the size of theme button in js editor

js/widgets/widgetWindows.js
This pull request addresses issue #3456  by implementing a fix that ensures the blocks hidden when "Display Statistics" is clicked in Advanced Mode will revert to their default visible state when the user closes the window
https://github.com/sugarlabs/musicblocks/assets/88442916/78dff7d4-5bd6-475f-bb70-25e00ea5ccf6
=> Fix/'Display Statistics' window in Advance mode - Restore Hidden Blocks on Window Close - #3456

css/activities.css, js/widgets/help.js
This pull request addresses issue #3476, which involves disabling the right arrow on the last slide of the blocks tour. This action is taken because allowing navigation to the next slide is unnecessary as there are no further slides for the user to access.
https://github.com/sugarlabs/musicblocks/assets/88442916/943f1766-e043-4601-94b4-b1b4cf3075f3
=> fix/disabling-right-arrow-of-last-slide-of-blocks-tour 

js/block.js, js/blocks/GraphicsBlocks.js
Fixes #3315
Based on trial and error and feedback from maintainers on #3338, I have made the following observations :
1. The forward block encounters issues with integer input values exceeding 5 digits.
2. For float values, the forward block works well unless the absolute integer part is 5 digits or more, leading to problems.
To address this, the following adjustments were implemented:
1. For positive integers with 6 digits or more, the input is sliced to 5 digits.
2. For negative integers with 6 digits, the input is sliced to 5 digits, considering the minus sign.
3. For float numbers with 5 digits or more, the absolute value is taken.
I have also added an additional check in the arg passing in GraphicsBlocks.js in the forward block class.
=> Fixes #3315

js/widgets/help.js
This pull request addresses issue #3492  by implementing keyboard navigation functionality in the tour window of Music Blocks. Users can now navigate between tour widgets using their keyboard's left and right arrow keys, enhancing accessibility and improving the user experience.
https://github.com/sugarlabs/musicblocks/assets/88442916/b1a71f09-72cb-4772-a7fd-ae4e33ea72d7
Note: Changes are made in such a way that it does not impact any existing functionalities
=> Add Keyboard Navigation to Tour Window

js/widgets/help.js
I encountered a bug related to the help window image size. Image breaks on certain blocks like scaler block because they are to big .
Before:-
After:-
=> fixes help img width

css/activities.css, css/style.css
fixes #3497 
This modification ensures compatibility across different browsers. The user-select: none; property prevents the user from selecting the text within the specified element.
for the standard property 'user-select' for compatibility, I included the non-prefixed version along with the prefixed version for older browsers.
=> fixes #3497

js/palette.js
issue : #3501 
before the search bar was overlapping with the palette body now it is resolved I have attached the screenshot in the issue 
after:
=> over lap issue resolved

js/activity.js
In actvity.js for refreshing canvas of undefined activity is removed now no console error is coming regarding that.
https://github.com/sugarlabs/musicblocks/assets/127110636/1bfe9d7f-8dda-4b8f-b145-44246524a12a
=> Console_errors_removed

js/widgets/pitchslider.js, js/widgets/pitchstaircase.js, js/widgets/timbre.js
fixes issue #3528 
All the widget window have implemtation of full screen expansion and contraction but missing in pitchstaircase , pitchslider and timber... I have set fullscreen to true ..This modification ensures expansion and contraction of widget windows .
=> added fullscreen mode in widget window

js/widgets/help.js
Related to Issue :https://github.com/sugarlabs/musicblocks/issues/3481
=> Left Arrow functionality to the left arrow in beginner block 

js/widgets/help.js
This PR resolves the issue #3549  with the disabled left arrow functionality in the widget help tour, preventing users from navigating back to the previous page.
https://github.com/sugarlabs/musicblocks/assets/88442916/0bf061b1-bc75-4aa5-80bb-58aead06a64d
=> Fix: Enable Left Arrow Navigation in Widget Help Tour

.github/ISSUE_TEMPLATE/bug_report.md
Fixes: #3557
This PR adds a section 'How to Reproduce' in the Issue Template for better tackling of it.
kindly review this @walterbender sir.
=> add how-to-reproduce section in issue template

js/activity.js, js/toolbar.js, js/utils/platformstyle.js, planet/index.html
Fixes #3526
In #3526 I have created a constant in utils/platform.js and used in toolbar.js and activity.js.
ALSO same functionality for ENTER is also defined stop button turns red even on clicking ENTER...
https://github.com/sugarlabs/musicblocks/assets/127110636/df42f398-8b00-45b0-8c67-a9ffcf167429
=> Stop_button_red_on_keyboard_shortcut

js/block.js
- fixes #3485
It displays this error, and the block value defaults back to the previous value
=> Limits number of digits to 12 in number block

js/widgets/help.js
This pull request addresses the issue described in #3577 
Changes made:-
Right after the help block is finished , the beginner and advanced blocks are added. During that process the widget is centered using a function. I removed that function call.
=> Fixed unwanted help window center on left and right clicks

js/blocks.js
I have reduced the delayExecution time to 100 from 500 which provides much faster UX on rescaling the blocks .
=> Fixes#3508

js/widgets/pitchslider.js
Fixes #3535 
Changes made to pitch slider widget to allow fullscreen
=> fix bug: fullscreen button added to widget pitch slider

package.json
fixes #3593 
This pull request addresses the issue where running npm run serve in the musicblocks repository results in the system being unable to find the python command. The current behavior, which leads to a "sh: python: command not found" error, suggests an inconsistency in the system's expectation of the python command, particularly on some Linux distributions where python3 is the correct command for Python 3.
Changes Made:
Updated the 'npm run serve' script to explicitly call the 'python3' command, ensuring compatibility with systems that expect the use of Python 3.
This update ensures a smoother transition, allowing the python command to point to Python 3 as distributions phase out Python 2.
=> Update 'npm run serve' Script to Explicitly Call 'python3'

js/widgets/jseditor.js
This pull request addresses the issue #3573  malfunctioning behavior of the help button in the JavaScript editor. The current issue causes the button to remain in a gold-colored state after clicking on reset code button, contrary to the expected behavior. Additionally, the functionality requires users to click twice to return to the help mode, which is not the intended behavior
https://github.com/sugarlabs/musicblocks/assets/88442916/d93935be-2812-4076-ba76-c3308433d39e
=> Fix: JavaScript Editor Help Button Color and Click Functionality Issues

js/blocks/BooleanBlocks.js
Fixes #3601 
This PR adds the less-than-or-equal-to and greater-than-or-equal-to Boolean blocks.
Less-than-or-equal-to :- 
Greater-than-or-equal-to :-
=> Added the less-than-or-equal-to and greater-than-or-equal-to boolean blocks

js/block.js
Updating fix #3551
Changing the limit to 10 in the number block and slightly shifting the text to the right to accommodate all 10 digits
Without shifting: 
Shifting:
=> Updating #3551 Limits number of digits to 12 in number block

js/README.md
fixes issue #3609 
Deprecated documentation removed as asked by @walterbender
=> Fix: Deprecated documentation removed #3609

documentation/greater_than_or_equal_to_block.svg, documentation/less_than_or_equal_to_block.svg, documentation/not_equal_to_block.svg
Fixes #3628 
This pull request addresses the rendering issue with the icons for greater than or equal to (≥), less than or equal to (≤), and not equal to (≠). The icons now render correctly without any distortion.
Added the svg files in the correct path
=> [FIXED] Rendering Issue with Greater Than Equal To, Less Than Equal To, and Not Equal To Icons

css/activities.css
Added the colour of msg close icon on hovering and transition 
Fixes:#3631
[screen-capture (1).webm](https://github.com/sugarlabs/musicblocks/assets/103755591/bb81ce31-4457-4cc3-9b3c-b6f5229a53ca)
=> Feat: added_colour_on_hovering_of_msgcloseIcon

js/blocks/BooleanBlocks.js
fixes #3633 
This pull request addresses the issue #3633 where the boolean blocks for less than or equal to (≤), greater than or equal to (≥), and not equal to (≠) were available in both beginner and advanced modes. The proposed solution restricts these blocks to the advanced mode only, enhancing the user experience and simplifying the interface for users in the beginner mode.
Updates relevant code sections to enforce the restriction.
Verified that boolean blocks for ≤, ≥, and ≠ are visible only in the advanced mode.
Checked that users in beginner mode do not have access to these blocks.
=> ≤,≥,≠ Boolean blocks available only in Advanced mode

index.html
This pull request addresses the need for clear communication regarding the intentional placement of the SVG image in the Japanese part of the preloader code in [Index.html](https://github.com/sugarlabs/musicblocks/blob/master/index.html) page line: _107_
This comment provides context for developers and ensures they understand the design choice behind this placement.
So that people don't raise unnecessary issues like #3645
=> Useful comment in index.html for develepors 

js/toolbar.js
when play button is clicked and if there is no start block then a message box popup, previously it did not hide when stop button is clicked , which is misleading cause confusion and potentially impede the user's ability to interact with the menu. 
Now this issue#3248 is fixed. message box hide when stop button clicked
=> warning box disappear when stop button is clicked, issue#3248 fixed

js/activity.js
Removed an extra if condition which was added for the resizing issue when the download toolbar used to appear
at the bottom of chrome.
Google Chrome has completely removed this feature and This feature can't be brought back even using chrome://flags/#download-bubble as it was an experimental flag which google further removed.
=> Removed not needed variable and condition

js/block.js, js/blocks.js
Fixes #3669 
I've implemented a restriction preventing users from dislodging the vspace block connected to the silence block within the note block, which solves the first corner case @pikurasa mentions in the ticket.
The other corner cases have been handled by 
1. A while loop that checks if a stack within the note block contains the silence block, if yes then it cant be dragged out.
2. By removing the piece of code that was returning the function that removed the silence block if the block inserted was a vspace block. This is as even if a user inserted a pitch block connected to a vspace block to the clamp even then the silence block would not be removed as the function would return.
=> Handles silence block corner cases

js/activity.js
Fixes: #3727
This PR makes the top-right buttons responsive to the height of aux menu
https://github.com/sugarlabs/musicblocks/assets/109718740/90ecf3e7-f4d4-44b6-8958-d92eac625c34
kindly review @walterbender sir.
=> make top-right corner buttons responsive to aux menu

js/blocks.js
A few corner cases will arise once vspace blocks that connecting to each other -
1. If a vspace block was connected to the vspace block connected to the silence block then the silence block would disappear.
2. If a pitch block with 2 or more vspace blocks attached below it would be placed inside the note clamp, the silence block would not disappear and could be dragged out of the note clamp.
Thus I have placed restrictions on both these corner cases. I am adding on to the fixes I made in #3718 .
=> Fixes new silence block corner cases 

js/palette.js
This pull request is in reference to the issue #3734 . 
Whenever scrollbar was used, the **setupGrabScroll()** function was being call which made the scroll bar go to the top and change the mouse pointer type to scroll.
This takes place in all widget palettes and makes it difficult to select something at the end.
Thanks,
Ritik
=> fixed scroll issues with widget palette

js/widgets/pitchdrummatrix.js
Ref https://github.com/sugarlabs/musicblocks/issues/2808
The Pitch Drum Matrix widget's white background doesn't match the window size before it is maximized, and it will change after the window is maximized and then minimized. 
**Before the change, the widget looks like this:**
https://github.com/sugarlabs/musicblocks/assets/76172789/bb1065c8-5f7a-4cd1-9775-add58adb8177
**After the change, it appears as follows:**
https://github.com/sugarlabs/musicblocks/assets/76172789/ec2b54b2-c91c-4417-b011-29258f8f4292
Furthermore, as more pitches and drums are added, creating music becomes challenging when the images of pitches and drums do not appear together.
**Here is how it looks with a large matrix before the change:**
https://github.com/sugarlabs/musicblocks/assets/76172789/67a64dd8-672a-47d5-b …
=> Pitch Drum Matrix: Enhancements to Fullscreen Mode

js/widgets/jseditor.js
"fixes #3766"
I removed the `setProperty()` and the scrolling in maximized mode of js editor  happend perfectly fine. 
Inorder to get the high contrast i changed the opacity of both background color and text color of `codeLines` element.
=> Fixed the scrolling issue in js editor in maximized mode

js/widgets/widgetWindows.js
This PR fixes issue #3808 . There were two Event Listeners being assigned to the maxmin button , "onclick" and "onmousedown". Only "onclick" listener is required and the presence of two Event Listeners caused this erratic behaviour.
=> Fixes #3808

js/blocks.js
fixes #3799
Errors were being displayed in the console due to a typo in the `blocks.js` file.
=> fix(js/blocks.js): fixing the dragloopcounter

js/widgets/temperament.js
Resolves #3823 .  
@walterbender and @pikurasa Plz review.
I have removed unnecessary code , But was necessary previously as to remove the dark color as we were filling dark color even if temperament was not playing,So I have added a condition that fill the color only if temperament is playing.
And added a timer logic that is the difference in the clicks is less than Singer.defaultBPMFactor * 1000 * duration which is the time delay for calling next note then we should not call the new playback(0) as to avoid collision.And if time difference is less than Singer.defaultBPMFactor * 1000 * duration then we have two conditions either start from where your music ended (This will happen if this.playing is true  as to enter inside this 
if (i <= pitchNumber && i >= 0 && that._playing && p < 2) { …
=> ResolvesTemperamentBugs

js/utils/musicutils.js
fixes #3859 
1) added "𝄾"  symbol for 1/8 and  "𝄿" for 1/16
=> fixed undefined in silence block

js/blocks/ExtrasBlocks.js
The hide block was hiding blocks, but not keeping them hidden. This was because it was referencing showBlocksAfterRun in logo.js instead of activity.js
Now the blocks stay hidden after execution stops. This is really useful for many games and interactive projects.
=> Fix Hide Block bug

js/activity.js
When prepping projects for loading, there is a check to see if a turtle is null, but not a check to see if the turtle is undefined. The latter case is triggering an error, which may or may not be causing the toolbar to disappear when loading a project from the Planet. In any case, it should be caught.
This patch checks for undefined as well as null. I assign a turtle ID of the length of the turtleList rather than Infinity in these situations.
=> check for undefined turtle

js/blocks/PitchBlocks.js, js/turtleactions/PitchActions.js
issue - https://github.com/sugarlabs/musicblocks/issues/3891
In this PR,  setSharp was invoked within pitchblock but hasn't been declared in pitchaction https://github.com/sugarlabs/musicblocks/pull/2454 
After fixing
https://github.com/sugarlabs/musicblocks/assets/89124765/c5f139fc-4509-40f8-b167-b15d440f5b97
=> setsharp pitch action

lib/sw.js, planet/index.html, planet/js/CollaborationSpace.js, planet/js/GlobalCard.js, planet/js/GlobalPlanet.js
Addresses: #3851 
This PR creates a `CollaborationSpace` that will be used to collaborate on a project.
This PR creates a space for the collaboration and changes the navbar as well ( as we will add copy link features in it ) and when the user clicks on exit, he gets back to global ( where he was before clicking on the collaborate )
https://github.com/sugarlabs/musicblocks/assets/109718740/dd893356-98c8-4a4f-848a-b2e2db701d4f
=> [3851] - Add Collaborate Space

js/activity.js
This PR fixes #3914 
-Added positioning of grids according to toggle of the hamburger menu(aux-menu)
-Changing the grid position by half of other elements for sync
-   Tested on -Chrome
-   ...
-   [x] I have tested these changes locally and they work as expected.
-   [ ] I have added/updated tests that prove the effectiveness of these changes.
-   [ ] I have updated the documentation to reflect these changes, if applicable.
-   [ ] I have followed the project's coding style guidelines.
-   [ ] I have addressed the code review feedback from the previous submission, if applicable.
Adding media for showing the fix-
[Screencast from 27-06-24 01:53:49 PM IST.webm](https://github.com/sugarlabs/musicblocks/assets/154296996/94053fc0-8406-4551-8dde-1c19b4d69b93)
=> fix:resolves grid position on hamburger opening(#3914)

js/activity.js, js/turtles.js
fixes #3909 
Now button size increases on hover
=> fix: added scale to buttons on hover (#3909)

js/activity.js
Description
Related Issue
This PR fixes #3933 
Changes Made
Change 1-Added the close icon functionality to the pie menu which appears on right click
...
Testing Performed
Tested feature close button on clicking the close icon .
Tested on browsers Chrome and Firefox.
...
Checklist
[x] I have tested these changes locally and they work as expected.
[x] I have followed the project's coding style guidelines.
[Screencast from 03-07-24 10:17:59 PM IST.webm](https://github.com/sugarlabs/musicblocks/assets/154296996/b9f27d08-0d6d-4369-8847-444b5a28918f)
=> Add close button to extended-menu pie menu (fixes #3933)

guide/guide.html
Issue #3939
Updated the old "Hyperscore" link to the new link in guide.html.
=> Update Hyperscore example link in guide.html

js/protoblocks.js
@walterbender @pikurasa 
Collapsed note block looks like...
This PR fixes that issue...
=> Fixes collapsed state of note block

js/widgets/jseditor.js
Fixed Issue with extra line number in Javascript Editor.
Before:
https://github.com/user-attachments/assets/401a94f9-150d-44ba-b8a8-8d4c945ef6d8
After: 
https://github.com/user-attachments/assets/83db3777-b320-4630-a2c0-0b9bf68df275
=> fixes issue with extra line number in JavaScript Editor

js/widgets/sampler.js
@walterbender I was going through sampler.js code and found this redundant code. I think we should remove this.
=>  fix: remove redundant code to improve codebase clarity

js/activity.js
- Context menu only opens up in the advanced mode.  
- Nothing happens when screen is right clicked in the begineer mode.
=> Fixes #3973 Right click menu only opens in the advanced mode

js/basicblocks.js
The original uses comments to indicate global and exported items, I replaced these with actual export statements.
also introduced a `setupFunctions` array to group all the setup function calls. The original code calls each setup function individually
`setupFunctions.forEach(setup => setup(activity));` to call all setup functions
exporting with actual export keyword will also be helpful for the React transition that musicblocks is undergoing (I hope the React transition is still on, as last merged PR was 6 months ago)
=> add export statements for BACKWARDCOMPATIBILIYDICT and initBasicProtoBlocks

js/turtle-singer.js
- Uses Object.keys().forEach() to simplify the loop for tur.endOfClampSignals 
- Object.assign() to restore multiple properties at once
- Removes unnecessary variable declarations
- The cents parameter now uses default parameter syntax
=> move all saved state into a single object

js/blocks/ToneBlocks.js
Now by this commit the "set default block" is working fine and poping out on canvas instead of that unknown block.
@walterbender @pikurasa 
https://github.com/user-attachments/assets/f442dbc8-cce3-48f8-bb93-39fa2c36099e
=> FIXES ISSUE #4000 Regression: 'Set Default Instrument' Block Converts to 'Unknown' Block 

guide/README.md
This pull request improves the Music Blocks Programming Guide by adding more "RUN LIVE" links throughout the document, particularly in sections with step-by-step screenshots. These additions aim to:
* Increase Interactivity: Provide new users with more opportunities to experiment with Palette buttons and other features 
directly from the guide, similar to the Turtle Blocks guide's approach.
* Enhance User Experience: Enable users to follow along more easily and tinker with examples as they read, thereby improving 
their learning experience.
Key Changes:
* Added "RUN LIVE" links in sections where screenshots and descriptions are provided.
* Ensured that all new links are functional and point to the correct interactive examples.
Commit Messages and Contribution Guidelines:
* Each commit is …
=> Add More Frequent "RUN LIVE" Links to Music Blocks Programming Guide

js/turtleactions/DrumActions.js
- More efficient object iteration using `Object.entries()`
- Reduced comparisons per iteration
- Immediate return on match
=> Streamline Drumname for early return of drum post http match, use object lookup

js/piemenus.js, js/utils/musicutils.js
by the changes the names of the temperaments are updated and also the pie menu for the temperament selection opens well as mentioned in the issue https://github.com/sugarlabs/musicblocks/issues/3921 by @pikurasa @walterbender
Before : 
After :
=> FIXES ISSUE #3921 Reexamine our default temperament list

js/widgets/sampler.js
=> fix: display file name after upload in sampler

js/block.js
The code was using an undefined `base64Encode` function, causing an error when opening the file on VS Code.
Removed the unnecessary `base64Encode` function call and directly used the built-in `window.btoa()` method for Base64 encoding.
Also fixed various EsLint errors. Most were solved by simply using double quotes.
I also removed unused variable names being declared.
=> fix all lint + Base64Encode errors

css/activities.css, js/activity.js
Description:
This PR addresses an issue where hovering over options in the search box replaces the search query with the block's name, even if the option hasn’t been selected yet. This unintended behavior disrupts the user’s search input and creates a frustrating experience.
The fix ensures that the search query remains intact until an option is explicitly selected. It refines the search box functionality for smoother user interaction and prevents unwanted input replacement while browsing search results.
Changes:
Adjusted the focus event behavior in the search function to prevent the hover action from replacing the input field prematurely.
Screen Recording:
https://github.com/user-attachments/assets/56e77cfb-9cb3-4d2d-a415-46bc249ae9ed
Fixes:
Closes #4024 
Additional Notes:
Tested …
=> Fix search box hover behavior replacing input text

js/widgets/temperament.js
after the addition of some new temperament the define frequency block used in the define temperament block uses the division approach to calculate the frequency instead as per the requirement we have to use the exponential of 2 format for more understanding.
=> FIXES ISSUE #4018 More default EDOs for temperament

js/turtles.js
Like the title says, there were linting errors throughout the file. This PR fixes them. 
Also `base64encode` function does not seem to exist, 
so I added a `/* eslint-disable no-undef */` for the meantime.
=> fix all eslint errors along with base64encode error

js/toolbar.js
This PR simplifies the `renderLanguageSelectIcon` method in the Toolbar class to make it more concise and maintainabl e
- The current implementation has repetitive code for each language, making it harder to maintain and add new languages
- Also fixed some of the ESLint warnings in the file
- It works
=> fix renderLanguageSelectIcon logic

js/utils/musicutils.js
after these changes the scalar step (+/-) block stepping up and down pitch perfectly for the temperaments other than Equal 12EDO and Custom
before :
[temperament-test-2024-09-23_10.51.50 (2).zip](https://github.com/user-attachments/files/17299964/temperament-test-2024-09-23_10.51.50.2.zip)
after : 
https://github.com/user-attachments/assets/a6b7241b-fbcc-4bb4-8e27-acbb4da92e3f
=> FIXES ISSUE #4012 Scalar Step doesn't work for default temperaments (other than 12EDO) 

js/activity.js
- remove old deprecated `var`
- implement forEach for iterating over values
=> refactor: use better mapping logic in _setupBlocksContainerEvents 

js/piemenus.js
fixes #4038 By this commit collapsing DOUBLE SHARP and DOUBLE FLAT notes no longer shows 'undefined'.
Video before fix:
https://github.com/user-attachments/assets/7e140174-634e-4018-bd6d-509e7e7ca015
Video after fix:
https://github.com/user-attachments/assets/212314d0-31ec-42c0-8ba8-541e5354e27d
=> Fixes #4038 Issue with Note Block collapsing

js/block.js
**Fixes #3883**
In browsers like Chrome and Safari, when attempting to load the same image consecutively, the browser does not re-upload the exact same file. This occurs because the input field (with id `myOpenAll`) is reused for multiple media elements. Consequently, the browser considers re-uploading the already present image on the input field redundant and does not open it.
To address this issue, after successfully attaching the file to the media/avatar element, the file is detached from the original input field. After detaching the file, there is no image currently on the input field. As a result, when the same image is chosen again, it is re-uploaded to the input field, thus resolving the issue.
=> Allowed rechoosing the same image for avatar in succession

js/activity.js, js/piemenus.js
Fix: Close Circular Menu (Wheel) on Click Outside
Issue Addressed: #4047 
Changes Made:
1. Added an event listener to detect clicks outside the circular menu (wheel).
2.  When a click outside the menu is detected, the menu is now closed, improving the user experience and consistency with standard UI behavior.
How to test:
1. Right-click on any block to open the circular menu (wheel).
2. Click anywhere outside the menu (on the page).
3. The menu should close automatically as expected.
Screenshots :
Right click on any block: 
When we click anywhere on the page: 
it will be closed
=> Fixes issue: #4047 - circle closing when click on anywhere on the page

css/activities.css, js/palette.js
Issue: When dragging a large block out of the palette (especially in advanced mode with longer palettes), the palette would become "sticky," retaining its position on the last pulled block. This behavior was caused by the use of float: left, which created inconsistencies in the layout, especially when the palette body height was affected by larger blocks.
Fixes : #3863 
Solution: Replaced float: left with display: flex and flex-direction: row for both tables in the palette component. This adjustment maintains consistent positioning and layout for both standard and advanced blocks, ensuring the palette body does not shift unexpectedly, even with larger elements.
Testing: Verified that the palette behaves consistently across different block sizes and that closing the palette fully resets …
=> Fix Palette Sticky Positioning After Dragging Large Block 

js/activity.js
#4053 
When resizing the window, the five buttons at the bottom of the page disappear and don't reappear when maximizing the screen back to its original size.
The button container's display property was being set to 'none' if a previous container existed, even though that container was immediately removed. This caused visibility issues during window resize operations.
Modified the button container creation to always display the new container:
// Before
ButtonHolder.style.display = removeButtonContainer ? "none" : "block";
// After
ButtonHolder.style.display = "block";
##Testing Completed
Verified buttons remain visible during window resizing
Tested button functionality before and after resize
[Screencast from 14-11-24 10:40:48 AM …
=> Fixes issue (#4053): maintain button visibility on window resize

js/piemenus.js
to enchance the viewer's experience and to view all the chord name properly 
Before:
After:
=> Increasing the size of chord pie menu

js/js-export/API/PitchBlocksAPI.js, js/js-export/API/RhythmBlocksAPI.js, js/js-export/API/ToneBlocksAPI.js
- Added detailed JSDoc documentation to all methods in PitchBlocksAPI class
- Added detailed JSDoc documentation to all methods in RhythmBlocksAPI class
- Every method now includes:
- A clear description of its purpose
- `@param` tags with types and descriptions
- `@returns` tags with types and descriptions
=> Fix #2630: Add jsdoc style documentation

js/blocks/MeterBlocks.js, js/js-export/export.js, js/notation.js, js/utils/utils.js
Changes Made-
Added logic to handle non-negative pickup values and support "faux pickups" like 1/3. Ensured notationPickup is called after setting the pickup value.
Validated the pickup value before passing it to MeterActions.setPickup to prevent errors.
Added input validation for pickup values in flow, ensuring only valid values are processed.
=> FIX #2645 Better Faux Pickup Support

js/piemenus.js
fixing issue #4070 
Now the pitch piemenu remembers the last selected accidental value 
custom pitch selected  ;
the wheel represents the same value as selected ;
=> FIXES #4070 The Pitch piemenu do not remember the last selected accidental value

js/piemenus.js
while deleting any block from the stack now the user will get a prompt notification informing more about how to restore the deleted block as before there is no such message.
=> Created a prompt notification for deleted blocks 

index.html, js/turtles.js
As per the issue #4079 i refactor the confirm button for clear option  to be a model dialog box. 
It is easier to see and take action on then a stand-along confirm button. 
Functionality remains same and it now looks like this :
=> refactor confirm button on clear -  #4079

js/piemenus.js
As per the issue #4085 i changes it like that
As like other options  - **New project, clean button** user can click the cancel button as well as outside of the piemenu.
User selects the grid from piemenu. After that they can click either the cross "x" button Or outside of the piemenu to close the piemenu.  It enhance the experiences of using Grid menu.
https://github.com/user-attachments/assets/8ad72a22-44e0-441f-84bb-5d8417aef779
=> Closing of piemenu for Grid button added outside click option

js/activity.js, js/palette.js, js/toolbar.js
This PR improves the user experience when switching between beginner and advanced modes without requiring a page refresh. Previously, changing modes required reloading the page.
Key Changes:
- Updated the star toggle icon to dynamically reflect the current mode.
- Adjusted advanced icons to update based on mode without a page reload.
- The palette regenerates after switching the mode.
- Save menu and record button also update according to the mode.
=> Fixes issue #2053 Updates the UI on switching mode without page refresh

dockerfile
This PR addresses issue #4091 :- 
1. Introduce a non-root user named appuser in both stages of the Dockerfile.
2. Use USER appuser in the final stage to ensure the application runs securely.
The image is running smoothly and it is thoroughly checked.
this closes #4091
=> Issue#4091 non root user added in dockerfile

dockerfile
In this PR :- The Dockerfile uses a lightweight python:3.9-slim image to minimize size and employs multi-stage builds for efficiency. 
This closes #4099
=> Issue#4099 Docker image optimized

js/activity.js, js/piemenus.js
Closes #4094 
Adds an optional timeout parameter to the textMsg method to improve user experience when dismissing notifications.
- Modified textMsg method to accept custom timeout duration
- Defaults to existing timeout if no duration specified
- Allows more flexible message display
- Manually tested message dismissal
- No breaking changes introduced
=> Issue #4094: Add Optional Timeout to Message Dismissal

.github/workflows/node.js.yml
This PR:- a Post-run cleanup step is added, which removes the ./build directory to ensure a clean environment, especially useful for self-hosted runners. This cleanup step is executed with if: always(), ensuring it runs regardless of whether the previous steps succeed or fail, preventing the accumulation of unnecessary files.
closes #4108
=> Issue #4108 post Build clean up in CI added

.github/workflows/node.js.yml
This PR :- The updated GitHub Actions workflow installs Node.js dependencies, builds the source code, and runs tests across the newer LTS versions of Node.js (18.x and 20.x), replacing the outdated 12.x and 14.x versions. The workflow includes steps for checking out the code, setting up the appropriate Node.js version, running npm ci to install dependencies, and building the project.
closes #4110
=> Issue #4110 Newer node version 18x and 20x added in smoke test to give best compatibility

js/activity.js
resolve issue #4115 
now if user restore item from trash it shows popup message that items restored...if there are nothing in trash still user want to restore it show popup that nothing in trash to restore
https://github.com/user-attachments/assets/bee25d21-fde0-4f58-8459-5572ea937357
=> popup msg for restore items

.github/workflows/security_scan.yml
This PR :- introduces an automated security check by integrating npm audit into the CI/CD pipeline. The enhancement ensures that installed npm packages are scanned for vulnerabilities, providing detailed reports on critical, high, and moderate issues. The pipeline is configured to fail if vulnerabilities are detected, enforcing secure code practices. For flexibility, a SKIP_AUDIT_FAILURE environment variable allows the pipeline to continue if needed, enabling quick iterations while still flagging security concerns. This implementation aligns with best practices, improves security posture, and reduces the risk of deploying code with known vulnerabilities.
closes #4119
=> Issue #4119 Security Check Added

js/widgets/musickeyboard.js
Issue #4061 
Previously adding a new 'Pitch' Note to the piano roll disabled the keyboard. Their were some issues with assigning values to undefined objects (this.layout). This fix resolve this issue by checking proper boundary values. 
Although there is another issue related to it. On clicking the 'Add Pitch' button, intead of adding a last Note (matching Octave and pitch) it is adding many notes together. These notes are in proper order but still it is not the intended behavior. I tried solving this problem but I need assist on doing so. 
@walterbender Sir, please check this PR, Thank You.
=> Fix: Play piano after adding a new note

js/utils/__tests__/mathutils.test.js, js/utils/mathutils.js, package.json
This creates the edge test cases for every function that lies in mathutils.js in /utils/__tests__ which will be the main test folder for the tests of the utils directory.
=> Adding tests for mathutils 

js/utils/__tests__/munsell.test.js, js/utils/munsell.js
Issue https://github.com/sugarlabs/musicblocks/issues/4124
I am creating a new PR. The package-lock-json file somehow got changed, i dont know how. But this should work. @walterbender 
This PR addresses the need of a jest testing file for munsell.js
It validates the functionality of four core functions from the Munsell module: interpColor, getMunsellColor, getcolor, and searchColors.
=> Made jest file for munsell.js

js/toolbar.js
This PR addresses issue #4135 by adding a notification feature that triggers when horizontal scrolling is enabled or disabled. The notification will appear on the page when the user toggles horizontal scrolling and will remain visible until manually closed.
A notification is triggered when horizontal scrolling is enabled or disabled.
The notification provides feedback to the user, with distinct messages for enabling and disabling horizontal scrolling.
The notification appears at the bottom of the page and remains visible until the user interacts with it.
=> [Enhancement] Add Notification for toggling Horizontal Scroll

js/activity.js, js/turtles.js
Resolve issue #4133 
Previously the confirmation don't appear for advance mode shortcut clear option. But now the confirmation box appears for both the cases clean button in canvas as well as shortcut option in advance mode.
https://github.com/user-attachments/assets/1f9aca00-0236-4af9-9249-d5dca31dd3c5
=> adding clear confirmation for both cases in advance mode

jest.config.js, jest.setup.js
This enhances the setup of tests we are creating and running on repo
=> Creating Jest config and setup file

js/activity.js
Resolves issue #4135
For PR #4138
Now Musicblocks has notification for enabling or disabling horizontal scrolling
As the PR #4138 has unwanted changes so I updated it through this PR
https://github.com/user-attachments/assets/6fed2c18-5067-44db-ac4c-5aecb653f375
=> added notification for horizontal scrolling

jest.setup.js
=> Resolving the test error 

js/utils/__tests__/musicutils.test.js, js/utils/musicutils.js
This pull request introduces unit tests for the functions in the musicutils.js file, specifically covering functionality from `getOscillatorTypes` to `base64Encoded`. 
- Added unit tests
The remaining tests for other functions in the project will be handled by **Aman Singh** through their GitHub contributions.
=> test:added tests to musicutils.js

js/activity.js
Resolve #4152 
In Musicblocks when we try to load an existing project by clicking "Load project from file" from our system an unwanted clear confirmation happens because the doLoad() function internally called the _allClear() function so that due to _allClear() the unwanted confirmation happened. But now it is removed.
here the doLoad() function called _allClear() function by passing true argument. So that internally canvas is going to clear. But we don't want that while loading an existing project because we are sure about to do it. 
So I pass an extra default argument which determine when the confirmation will skip. When the parameter is true the confirmation is skipped otherwise not.
But the other calling of _allClear() it has no such parameter so that it will not effect those calling …
=> removed clear confirmation during load project

jest.config.js, jest.setup.js, package-lock.json, package.json
addresses: #4124 
Issues: https://github.com/sugarlabs/musicblocks/issues/4145#issuecomment-2543315424
In this PR I have removed the configurations that we don't need for now and added `jest` as `devDependency` to streamline the workflow of adding tests in MB.
After this, tests are working properly without throwing error or creating extra files.
=> fix: add `jest` dependency and remove extra configs from `jest.config.js`

js/utils/__tests__/utils.test.js
This Pr Covers test for utils.js...
Functions Covered by the Test(This PR):
**toTitleCase:** Tests converting the first character of a string to uppercase and handling non-string input.
**fileExt:** Tests extracting the file extension from various filenames, including those without extensions or null input.
**fileBasename:** Tests retrieving the basename of a file path (without the extension) and handling filenames without extensions.
**last**: Tests returning the last element of an array or null for empty arrays.
**safeSVG:** Tests escaping certain HTML entities in strings and returns non-string inputs as-is.
**toFixed2:** Tests formatting numbers to two decimal places when needed, and returning non-number inputs unchanged.
**mixedNumber:** Tests converting floating-point numbers to …
=> Add: Test for utils.js

js/palette.js
* Fixed issue where the palette dropdown switched unintentionally when hovering over
other tabs.
* Dropdown now locks to the selected palette upon click and remains active until the
* user explicitly changes it or closes the dropdown.
https://github.com/user-attachments/assets/df4f1880-ac6f-432f-a30b-ed49239d9be4
=> #4154 issue: Fixed palette dropdown to prevent accidental switching

js/activity.js
Initially, blocks would get stuck when Zooming In/Out.
**Key Changes:**
- Added immediate canvas refresh after block scale changes
- Added bounds checking to ensure proper block positioning after resize
=> Fixes #3847 Bug Inconsistent zoom behavior 

js/toolbar.js
if we enable horizontal scrolling by helpfulwheel the notification timeout is 3 seconds but if we enable it through button in navbar it has no such timeout.
https://github.com/user-attachments/assets/aea08fcf-9ec5-40b7-8cc5-11ddde992064
I think both should be same. 
removing this part from toolbar.js because notification is already handled by this function and it is same for both cases (helpfulwheel and buttons ). 
So, we don't need those extra lines.
=> same msg timeout for horizontal scroll

js/utils/synthutils.js, js/widgets/sampler.js
@walterbender Can you please review it.
=> feat: implement playBack stop functionality in sampler

css/activities.css, js/activity.js
Resolve issue #4163 
Now the search bar input text in advance mode not replaced by option search bar.
https://github.com/user-attachments/assets/0157a9a4-d9ac-48cf-ac10-a89b14d17303
=> Search input text hovering issue in advance mode

js/piemenus.js
In the piemenu(for grid) there are different svg for different grid. But the last option is set to "Blank" and don't have corresponding svg. The first option is also set to "Blank" and have its corresponding svg.
I think it should be removed so that it looks nice.
Before
After
=> Remove extra blank option from grid piemenu

js/logo.js
this resolves the issue #4171 now the pen block takes its individual arg and do not depends on last pen arg. when placed in side the note block.
pen block inside the note block :
pen block outside the note block :
=> FIXES #4171 pen args mismatched inside note blocks

js/block.js
Closes #4112.
* Introduced the txtMsg with a time out when blocks are deleted using drag and drop.
* Manually tested message arrival and it's auto time out.
* No breaking changes introduced.
=> Fix: Add Notification When Dragging Blocks to Trash (#4112)

gulpfile.js, package-lock.json, package.json
fixes: #4156 
This PR solves the issues of deprecated dependencies and the old version `package-lock.json`.
@walterbender I've raised this draft to fix deps. related issues. Some issues require manual installation and testing so I'be updating those in this draft itself. Please feel free to ask questions if something feels unclear.
=> deps: fix the audit to change deps to available fixes

js/widgets/musickeyboard.js
Issue : https://github.com/sugarlabs/musicblocks/issues/4180
This PR fixes the issue of piano keys getting stuck in ON state and never turning back OFF. 
I also removed text selection in piano roll because texts like note name and octave gets selected and it can be annoying. 
@walterbender Sir please check this PR. Any kind of feeback is welcome. 
[fix.webm](https://github.com/user-attachments/assets/86824306-31ef-4bd7-a34d-f08d2ee5d97c)
=> Piano Keys gets stuck 

jest.config.js, js/utils/__tests__/musicutils.test.js, js/utils/__tests__/platformstyle.test.js
adding unit test for the platformstyle.js and also resolving the coflicts with the other dependencies.  #4124
=> test for the platformstyle.js

js/activity.js
Resolve #4170 
Removed unnecessary clear confirmation after loading of new project
https://github.com/user-attachments/assets/1bd62e08-f6ad-40b6-a1cf-d60747e56624
=> remove clear confirmation on loading new project

js/activity.js
- **Root cause**: The issue is that when we use the blocks set x, y = (0,0) then the mouse/turtle is supposed to be at the origin on the graph. but when we resize the window then we hit play the mouse or turtle is on the center of the screen but it is supposed to be on the center of the graph in the background.
- **Solution**: We should also update the graph's position to match 0,0 on the resized screen. As suggested, we are doing this now when the play-button is pressed.
I simply add `this._onResize();` to the `play-button` functionality. As described it refreshes the grid too.
**NOTE**: I tested and confirmed that this issue isn't just on the cartesian grid but also other forms of grid. 
Here is a video showing in various scenarios how the issue is now fixed. The video contains both the …
=> add onResize refresh to play-button (Fixes #3900)

js/activity.js
resolve #4202 
The helpful search option is now only visible in advance mode
https://github.com/user-attachments/assets/dd4837cf-0a88-4e21-853c-1d5768afb94f
=> helpful Search only visible in advance mode

js/piemenus.js
Before:
[before.webm](https://github.com/user-attachments/assets/88c0fe46-e0cd-436d-9f57-b51269b0d5e1)
After:
[after.webm](https://github.com/user-attachments/assets/8d9fe12f-5762-4fc5-9187-9da7a233b6d6)
@walterbender Can you please review this.
=> fix: pitch octave limit to a valid range in pie menu

js/js-export/API/DrumBlocksAPI.js, js/js-export/API/RhythmBlocksAPI.js, js/js-export/API/__tests__/DrumBlocksAPI.test.js, js/js-export/API/__tests__/RhythmBlocksAPI.test.js
This pull request addresses issue #4200 by adding tests for the following files:
- **RhythmBlocksAPI**: V
- **DrumBlocksAPI**:
=> Add Tests for RhythmBlocksAPI and DrumBlocksAPI in /js/js-exports/API (#4200)

js/widgets/musickeyboard.js
This fix resolves an issue where newly added 'pitch' notes in the Music Keyboard Widget did not work with MIDI playback until the keyboard was restarted. While notes through virtual keyboard were clickable, they failed to  play with MIDI initially.
1.Replaced the simpler pitchLabels array with a detailed version including sharps
2.Updated the logic to ensure new pitches don’t duplicate existing ones in the layout.
3.Ensured getElement mappings are updated immediately for new notes:
Verified that new pitches are functional immediately via MIDI without requiring a widget restart.
https://github.com/user-attachments/assets/55332aac-dd60-423b-891f-dbb68dd2082a
Fixes #4149 - Bug in MIDI
=> Fix: Corrected MIDI pitch note addition bug

js/js-export/API/GraphicsBlocksAPI.js, js/js-export/API/OrnamentBlocksAPI.js, js/js-export/API/VolumeBlocksAPI.js, js/js-export/API/__tests__/GraphicsBlocksAPI.test.js, js/js-export/API/__tests__/OrnamentBlocksAPI.test.js, js/js-export/API/__tests__/VolumeBlocksAPI.test.js
This pull request addresses issue #4200 for including test files.
The test file for synthutils.js has been added through this pull request. It addresses all the functions present in the synthutils.js file. 
[
](url)
=> Add test files for GraphicBlocksAPI, VolumeBlocksAPI, OrnamentBlocksAPI in /js/js-exports/API #4200

js/activity.js, js/blocks.js
#4217 
- Modified `doContextMenus` event handler to check if right-click intersects with block coordinates
- Added check to prevent helpfulWheel from appearing when blocks are clicked
- Improves menu behavior by ensuring only appropriate context menus appear
**Before fix:**
[Screencast from 02-01-25 12:03:14 AM IST.webm](https://github.com/user-attachments/assets/6e29de44-c207-462c-abbf-054d2d31870a)
**After fix:**
[Screencast from 02-01-25 12:40:36 AM IST.webm](https://github.com/user-attachments/assets/3dafba66-fb10-4732-82e8-f7f6eeec58c3)
=> fix: prevent helpfulWheel from appearing on block right-click

js/activity.js, js/blocks/ExtrasBlocks.js, js/blocks/WidgetBlocks.js, js/planetInterface.js, js/widgets/phrasemaker.js
https://github.com/sugarlabs/musicblocks/issues/3842
I was able to figure out how we can add print blocks to the block stack. But addition of a "true" print block in the phase maker widget and detecting it in the matrix is challenging. I spent almost 2 days on this problem but no results were produced. 
Hence I am making it a draft PR for the interested one. They can  continue my work and also I am ready to collab. 
Things we can focus on :-
1. Modifying print block code. Orginally the phase maker only identifies notes and instruments like drum. No such implementation 
for other blocks.
2. Removal of keyboard shorcuts while typing in the cell. 
3. Here I have used an array to store lyrics. Is there any better option ? 
@walterbender @pikurasa Sir please check this PR. …
=> Addition of lyrics through phase maker

js/activity.js
This is a fix to issue #4050 
The piemenu now closes whenever you click anywhere in the canvas as well as on the cross icon.
=> Add click event listener to close helpful wheel when clicking outside

README.md
When I was following the `README.md` file for installing musicblocks locally and running a local server, I was a bit confused about whether I should run the Python command followed by the npm command, or just the Python command. It was easy to figure out after running both that they served the same purpose, but I think the instructions could be more explicit to avoid this confusion.
=> Clarify Instructions for Running Local Server in README.md

js/widgets/phrasemaker.js
While working on Phrase Maker I found this piece of code : 
It was suppose to highlight cells on hovering but did not work. After using addEventListener it is working fine.
@walterbender  Please check this PR.
[fixed.webm](https://github.com/user-attachments/assets/776b82c8-3203-4724-9cca-5ccb55d3cfde)
=> highlights fix

js/turtleactions/DictActions.js, js/turtleactions/DrumActions.js, js/turtleactions/MeterActions.js, js/turtleactions/OrnamentActions.js, js/turtleactions/PitchActions.js, js/turtleactions/ToneActions.js, js/turtleactions/VolumeActions.js
Resolves the Module Exports undefined error of the console for the remaining tests files added 
after these changes the error is not there in the web console 
@walterbender please review this
=> Resolves the Module Exports undefined error of the console 

lib/materialize-iso.css
This PR closes #4121 
In advance mode the auxiliary menu items was breaking into next line.
After changes:
https://github.com/user-attachments/assets/4d439837-09c9-4d77-8f59-359f2defb97b
=> Made the Auxillary menu responsive

js/widgets/arpeggio.js, js/widgets/meterwidget.js, js/widgets/modewidget.js, js/widgets/musickeyboard.js, js/widgets/phrasemaker.js, js/widgets/pitchdrummatrix.js, js/widgets/pitchslider.js, js/widgets/pitchstaircase.js, js/widgets/rhythmruler.js, js/widgets/sampler.js, js/widgets/temperament.js, js/widgets/tempo.js, js/widgets/timbre.js
This PR resolves issue #4255 by introducing a notification timeout feature. With this enhancement, notifications automatically disappear after a set duration, eliminating the need for manual dismissal. This improvement ensures a smoother and more user-friendly experience.
Introduced a timeout feature that automatically hides notifications after a specified duration of 3 seconds, building on the functionality initiated in PR #4162. This enhancement ensures notifications dismiss themselves seamlessly, eliminating the need for manual user intervention while maintaining the integrity of the codebase.
https://github.com/user-attachments/assets/8a3bebd1-215e-47e2-b705-516cf1e1122f
=> Added Notification timeout to widgets

js/activity.js
Earlier on clicking "Cancel" in the prompt saved the video. With this PR, it won't save the recorded video if "Cancel" is clicked. 
@walterbender Please check this PR.
=> record cancel works

css/activities.css, js/activity.js
The search bar's width was overly extended, making it appear disproportionate compared to other UI elements. Its color didn't align well with the sidebar, leading to a slight mismatch in the visual theme of the interface.
After:
The search bar's width has been adjusted to create a balanced and proportional layout. Its color now matches the sidebar, ensuring a cohesive and aesthetically pleasing design that enhances the overall user experience.
=> Improved Search Bar Design for Better UI Consistency

js/piemenus.js
By this the size issue of set pitch preview resolve
After:
Before:
=> Increasing size of Set Pitch preview

js/utils/utils.js
@walterbender as you told, I have enhanced the _() method for better translations.
It's a pretty big change in the functionality.
Earlier, _() method didn't recogonize "Search" as "search" and wouldn't give translated text since translation for "Search" was not given but "search" was.
=> enhancement: utils.JS Translation Method

js/turtledefs.js
This pull request repositions the guide link within the help widget to enhance usability for students by directing them to the [guide.html](https://musicblocks.sugarlabs.org/guide/guide.html) file for study purposes.
- Moved the guide link in the help widget to the 3rd position (immediately after the 'Meet Mr. Mouse' section). Previously, it was located at the end of the menu.
- Improved code readability by rearranging certain sections.
https://github.com/user-attachments/assets/4fa76192-5dae-415b-8e6c-a4576416deb2
=> Reposition guide within help widget

js/activity.js
Fixes #4275 
This pull request fixes an issue where the helpfulSearchDiv widget does not hide consistently when the context menu is triggered on the canvas. This ensures a cleaner UI and a better user experience.
Added a check while opening do context menu to ensure if the helpfulSearchWidget is on, it closes before opening the menu, the method being already defined as _hideHelpfulSearchDiv
###Screenshots
[Screencast from 15-01-25 03:05:23 PM IST.webm](https://github.com/user-attachments/assets/7e78f6b0-7448-4fc8-bbe8-dc91236bbcd4)
special thanks @haroon10725 and @walterbender for pointing out the bug
=> Fix: Ensure helpfulSearchDiv hides consistently on context menu

css/activities.css, js/widgets/help.js
Adding page count in Take A Tour section for better user experience. Previously there was no idea about how long the basic tutorial of MB will take place. But if we add a page count so that user can get a idea about the tutorial.
=> Add page count in Take A Tour section 

css/activities.css, index.html, js/activity.js
resolves #4190 
I have created a new Restore option in Musicblocks **( View Trash )**. From here we can see the list of all trashed items. By selecting item from the list the specific item will be restored. We don't need to restore item multiple time to restore the specific item from trash. 
https://github.com/user-attachments/assets/ec0a5d0b-0868-469d-98be-0d724cc3d029
=> Crearting 'View Trash' and more restore option in Musicblocks

index.html
<h1>Loading text message function runs in the background</h1>
@walterbender I noticed that the loading messages continued to change even after the loading screen was dismissed. This PR addresses the issue, ensuring smoother behavior and making Music Blocks slightly more efficient.
https://github.com/user-attachments/assets/31110712-2521-48d3-a7cc-a6de83a79902
=> Stop loading text in background

js/blockfactory.js
Completed the given Todo:
`
// TODO: make this an array
this._expandX = w;
this._expandY = h;
this._expandX2 = w2;
this._expandY2 = h2;
`
The contents are now inside an array
=> todo: apply array destructuring

package-lock.json, package.json
This PR removes the `lodash.template` dependency and `node-static` .
- Removed `lodash.template` from `package.json`.
- Removed `node-static` from `package.json`. We use http-server so it doesn't break everything.
- Verified that `gulp-util` is not directly used in the project. ( has lodash.template as dependencies ).
- [Command Injection in lodash.template](https://github.com/advisories/GHSA-35jh-r3h4-6jhm)
=> Update Dependencies 

js/SaveInterface.js, js/activity.js
fixes: #4286 
https://github.com/user-attachments/assets/6a8de70f-f6be-4d80-8c6d-f6233d754f92
now it only asks the user for the filename once, and that's the final one.
=> Fix: LilyPond FileName issue

js/loader.js
fixes #4292 
fix: resolve docById undefined error by ensuring utils.js loads before activity.js
The error "ReferenceError: docById is not defined" was occurring in activity.js
because it was trying to use docById before utils.js was fully loaded. Fixed
this race condition by explicitly ordering module dependencies in RequireJS
to ensure utils.js loads before activity.js.
- Modified loader.js to load utils/utils before activity/activity
- Maintains existing folder structure and RequireJS paths configuration
- No changes to function definitions required
=> fix: resolve docById undefined error 

index.html, js/SaveInterface.js, js/activity.js, js/toolbar.js
Allowing user to export the project block artwork as a PNG file too 
**new link for downloading project block artwork in png format 
**downloading the Block artwork in png 
https://github.com/user-attachments/assets/a7d9b39f-25b8-4ea1-9fda-b3b46fb14b62
=> Exporting Blocks artwork in PNG

js/block.js
resolves #3849 
In this issue mentioned that the delete icon pop-up when we collapse or expand a block but the collapse and expand works properly. Only issue that the trash icon pop-up when expanding or collapsing a block. 
In this PR, the trash icon not appears when the block is collapsed or expanded and only pop-up when we perform other interaction with block.
https://github.com/user-attachments/assets/7d6a2d1b-531e-4ea7-97a9-4460751afd6d
=> Hide trash icon when collapsing or expanding a block

js/activity.js
fixes #4300
This PR adds a defensive check in the `_onResize` method to ensure `this.stage` is properly initialized before executing resize operations. This prevents potential errors during the application's initialization phase.
- Added initialization check at the start of `_onResize` method
- Added early return if stage is not initialized
- Maintains existing resize functionality when stage is ready
The `_onResize` method would attempt to access `this.stage` properties before initialization was complete.
Method is only called when the stage is available
- Verified application loads without errors
- Confirmed resize functionality works as expected after initialization
- Tested resize behavior across different browsers
=> fix: Add stage initialization check in _onResize

js/widgets/musickeyboard.js
Earlier the music keyboard was not following BPM. Now the widget is following BPM.
=> music keyboard fix

js/toolbar.js
Currently the theme changes without giving a confirmation and refresh the browser.
I have added a confirmation message for theme change,
vedio:
https://github.com/user-attachments/assets/837c8eeb-7cdf-4ba4-b6e7-c267442cc11e
on clicking the text message the browser refresh and new theme is applied.
@walterbender we have the same workflow for changing the language, so I thought we should also have that kind of workflow for changing the theme.
Please review.
=> Confirmation for changing theme

js/activity.js, js/planetInterface.js, planet/index.html, planet/js/Planet.js
Earlier the Dark mode of the main page is not synced with the planet page dark mode after these changes 
the dark mode of the planet is automatically tiggered when there is change in the theme of the main page therfore creating a sync of theme between two different pages. 
before:
https://github.com/user-attachments/assets/d10c618b-4418-430b-9160-b8e83695776d
after :
https://github.com/user-attachments/assets/cd6f5f80-456f-4b2f-9263-ae4bd35c5561
=> Syncing dark mode between planet page and main page

js/block.js
Resolve #3835 
Before while dragging the block, when hover another icon, the trash icon disappears.
Anyway if the block is dropped in the same place where the trash icon was there, the functionality of delete block works, hence the block gets deleted.
Before : 
https://github.com/user-attachments/assets/39b7fff6-adc0-43dd-899e-05e1405a6dcd
After : The trash icon remains visible even if hover other icon while dragging the block.
https://github.com/user-attachments/assets/b7971928-dcf7-4140-801e-de39d16d8dc2
=> Show trash icon when dragging a block and hovering over another icon

planet/index.html, planet/js/Planet.js
@walterbender @pikurasa as we discussed not the toggle button is not there in the planet page and now there is only one way for the user to switch between the themes that is the main page dark mode tooge button
After:
=> Removing the toggle dark mode button from the Planet page

css/activities.css, css/darkmode.css
@walterbender Sir, there might be more dialogue boxes whose style does not follow the usual theme of MB. I have added light and dark modes for the "Lilypond save box." Please review this PR. If there are any other such boxes I can update in this PR itself.
=> dialogue box UI update

README.md, po/README.md
An overview and some "under the hood" notes.
=> update the documentation for internationalization

js/__tests__/base64Utils.test.js, js/base64Utils.js
@walterbender i created jest test suite for 
base64Utils.js
=> test for base64Utils.js

js/piemenus.js, js/turtles.js
Resolves #4346 
Now the last selected grid is re-applied again when expanding after collapse. The grid which is selected before collapse is re-applied after expanded it can be changed by selected other grid option from piemenu.
https://github.com/user-attachments/assets/519fe95b-bb0d-4bd6-aa16-e75dd46c95e6
=> Last selected Grid is re-applied after expanding from collapse state

js/__tests__/macros.test.js, js/macros.js
@walterbender i had added the test for the js/macros.js and it works absolutely fine.
=> jest test suite for js/macros.js 

lib/materialize-iso.css
This PR fixes issue #4351 and includes several changes to the `lib/materialize-iso.css` file, primarily focusing on adjusting the font sizes and widths of icons within navigation elements.
Font size adjustments:
* Increased the font size of `.materialize-iso nav .aux i.material-icons` from `32px` to `48px`.
* Changed the font size of `.materialize-iso nav .main i.material-icons` and `.materialize-iso nav .aux i.material-icons` from fixed pixel values to viewport width units (`5.3vw`).
* Updated the font size of `.materialize-iso nav .main i.material-icons` and `.materialize-iso nav .aux i.material-icons` to `7.5vw` and adjusted the margin values accordingly.
Width adjustments:
* Removed the width properties from `.materialize-iso nav .main i.material-icons` and `.materialize-iso nav .aux …
=> Bug Fix: Made ToolBar Icons Responsive

js/activity.js, js/pastebox.js
We have a regression when pasting JSON project code to the canvas. The div appears when you type Ctrl-V, but when you hit Enter, the project is run rather than the pasted code being loaded.
The solution: if paste div is open, paste contents when Enter is typed.
=> Paste regression fix

js/activity.js
fixes: #4342 
I still have a few changes left to improve block rendering. I'm open to suggestions for further improvements. Let me know if you have any!
https://github.com/user-attachments/assets/73aad076-c3e4-4c5d-b399-49cba5c51feb
=> Adding Responsiveness In Blocks

js/utils/synthutils.js
Earlier no prompt was given to save the WAV file with a name. In this PR, when recording is finished it will prompt the user to input the file name. 
@walterbender Sir please review this PR.
https://github.com/user-attachments/assets/8b402798-4851-4ff1-87b4-fac59baf11b3
=> Save As WAV, input file name

css/activities.css, css/themes.css
Previously #4333  In this PR, the dark mode in search, helpful search, search results implemented. But after "Generalised Dark Mode into General Theme #4348" this PR MB has moved "darkmode.css" to "themes.css". 
So that, in light mode, helpful search and search results looks like dark mode.
Before : 
After this change properly dark mode and light mode has applied. 
Now :
=> Fix dark mode issue of helpful Search and search results in light mode

css/activities.css, css/themes.css, index.html
This PR resolves #4381
Earlier background color in collapsed view remained white after switching dark mode. 
Now it changes to dark color.
[background-view.webm](https://github.com/user-attachments/assets/33b80b5c-a120-4698-b25b-a608284f7361)
=> Change collapsed view background color in dark mode.

js/__tests__/abc.test.js, js/abc.js
Tests for abc.js have been implemented. 
@walterbender Please check this PR.
=> Tests for abc.js

css/activities.css, css/themes.css, js/turtles.js
This pr fixes two bugs:
1. The set pitch preview section was not updating when switching to dark mode.
2. The grid button was disappearing when clicking the expand or collapse button.
Before:-
After:-
=> Fix Dark Mode setPitch preview Bg and Grid Button Visibility Bug

js/__tests__/rubrics.test.js, js/turtleactions/__tests__/MeterActions.test.js
@walterbender after the updates in turtles.js some of the test cases for the rubrics.js and MeterActions.js are failing due to the lack of proper mocking turtles function in the test suite this PR resolves all the error with the test suite and now each and every test is running fine.
=> resolving all the test case error with rubrics.js and MeterActions.js 

js/widgets/phrasemaker.js
@walterbender I almost forgot about the lyrics row icon. There was a pen icon in the images directory; I used that here. Please share your thoughts on this.
=> pen icon for lyrics row

index.html, planet/index.html
This PR resolves issue #4413 and includes changes to improve the loading performance of web pages by preloading fonts.
On slower connections, the material-icons.woff2 font would be loaded later, so the font is preloaded, and is then fetched from disk cache now.
Before
https://github.com/user-attachments/assets/eefd0823-e2ca-4763-bb15-58969bfa5f61
After
https://github.com/user-attachments/assets/06e12336-4f16-4a66-beee-9f8b51083ccc
Performance improvements:
* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R72): Added a `link` tag to preload the `material-icons.woff2` font.
* [`planet/index.html`](diffhunk://#diff-b11db06ff6c4f10ede00643f1201e7316a3258fc569f75b3f9d3bd51004517dfR11): Added a `link` tag to preload the `material-icons.woff2` …
=> Fix: Preloading Fallback Font for slower connections

.github/workflows/pr-jest-tests.yml
@walterbender I had created a github workflow for running jest test suites whenever a PR is raised please review this 
also this workflow creates a comment on the PR about the test result with the log of failed test suites 
which the author need to take note of after raising a PR.
=> Workflow for the running tests 

js/turtleactions/__tests__/VolumeActions.test.js
@walterbender After changes in the VolumeActions.js there is failure of some of the tests in the test suite which are resolved and also add some more edge test cases to maximise the code coverage please review this.
=> Resolves all the errors with VolumeActions.test.js

po/ayc.po, po/he.po, po/quz.po, po/te.po
Fixed errors in PO files:
- ayc.po (Line 4838): Removed extra quote in msgstr.
- quz.po (Line 3995): Fixed empty msgstr with spaces.
- te.po (Line 2219): Corrected misplaced quotes.
- he.po (Line 153): Removed extra quote in msgstr.
I found this internationalization project mentioned in GSOC Ideas really interesting. While looking into it, I wrote a Python script to convert PO files into JSON, which I think will be useful for moving from webL10n.js to i18next.
I feel this PR is the first step—fixing PO file errors so the conversion works smoothly. Really excited to work on the full i18n setup and make localization better! Would love to hear any feedback or suggestions.
=> Fix PO File Errors

.github/workflows/pr-jest-tests.yml
@chimosky @walterbender the changes here made the worflow to run on PR instead of the upstream master 
as even after resolving the test errors we are getting the comment with the failure of that test 
please review this !!
=> Workflow to run test on PR instead the upstream master 

guide/README.md, js/widgets/sampler.js
https://github.com/user-attachments/assets/07a41a72-c5b7-415b-908b-851cca8d6110
@walterbender I have been working on the drag-and-drop functionality to upload samples, it's not complete but ready for testing.
Please test and let me know what do you think.
=> Drag and drop to upload samples

dist/css/keyboard.css, js/widgets/musickeyboard.js
https://github.com/user-attachments/assets/e3acf978-88cb-44dd-9cd5-1ba18c3d738b
@pikurasa I found that while using the metronome, it records the last rest note also. So when you switch it ON again next time, it adds the previous rest duration. In this PR, a rest note is not added when you start playing the piano after switching the metronome ON. Please watch the video.
But imagine a case where a user wants to add rest before starting. The user can turn ON the metronome, he will wait for the right time, and then start playing the piano. Currently, there is no implementation for this. Do you think this would make sense?
=> piano metronome fix

js/widgets/sampler.js
@walterbender Can you please review this.
=> refactor: remove extra code and fix formatting

documentation/README.md
This PR updates the documentation to include details on toggling fullscreen mode and changing themes.
=> add full screen and theme in documentation

js/toolbar.js
This PR resolves issue https://github.com/sugarlabs/musicblocks/issues/4420 where the save menu was not functioning after mode changes. It will only work if you refresh the page with that mode.
For ex: if you are in beginner mode, and the page loads, only the beginner mode save menu would work and not the advanced menu.
Similarly, if you are in advanced mode, and the page loads, only the advanced mode save menu would work and not the beginner menu.
Probable cause was not handling rendering of save icons on mode switch.
Note: This issue is also addressed in PR https://github.com/sugarlabs/musicblocks/pull/4401
Before
https://github.com/user-attachments/assets/55ff9765-2b2c-49ed-97f6-60fb642c3b74
After
https://github.com/user-attachments/assets/d71b7dcd-1f82-41da-8c32-56056e0bd607
=> Fix: Fixed the save menu not working after mode change

js/turtles.js
Resolves #4399 
Last selected grid is re-applied after collapse for both cases - 1. From Collapse/Expand Button 2. From advance mode helpfulwheel.
```this.expand``` and  ```this._expandButton.onclick``` have the same logic. So I removed the expand logic from onclick handler and call ```this.expand()``` inside it.
https://github.com/user-attachments/assets/ae5c997a-49aa-492d-a8fa-887758722889
=> Last selected grid is re-applied after expand from helpfulwheel in advance mode

cypress.config.js, cypress/e2e/main.cy.js, cypress/fixtures/example.json, cypress/support/commands.js, cypress/support/e2e.js, package-lock.json, package.json
Introduces Cypress end-to-end testing framework to Music Blocks
- Added comprehensive Cypress test suite
- Covered key application functionalities:
- Application loading
- Audio controls
- UI element interactions
- File operations
- Added tests for:
- Loading sequence
- Play/stop buttons
- Toolbar interactions
- File management
- User interface elements
- Expand test coverage
[Screencast from 07-02-25 06:36:11 PM IST.webm](https://github.com/user-attachments/assets/af5f0f59-2c9e-4880-a6a7-b79c519b6e2e)
=> Implement Cypress testing for Music Blocks

js/js-export/__tests__/interface.test.js, js/js-export/interface.js
This pull request adds the following test for js/js-export/interface.js.
The test file for the above mentioned files have been added through this pull request. It addresses all the functions present in the those file.
=> test suite for js/js-export/interface.js

js/js-export/__tests__/constraints.test.js, js/js-export/constraints.js
@walterbender i had created a test suite for js/js-export/constraints.js please review this.
=> test suite for js/js-export/constraints.js 

js/activity.js
This feature was suggested by @pikurasa  in #4345 
Vedio:
https://github.com/user-attachments/assets/9f8390f0-6868-4cbf-a5b8-cc49ff7e5be1
=> Feat: Open sampler widget on sound sample drop

js/turtles.js
This PR resolves https://github.com/sugarlabs/musicblocks/issues/4455
Now using the collapse button does not hide blocks.
The issue started occurring after https://github.com/sugarlabs/musicblocks/pull/4347
After fix-
[collapse-fix-demo.webm](https://github.com/user-attachments/assets/37f023b7-a036-49d1-a05a-3a4973c34b4b)
=> fixes the issue of blocks being hidden in canvas

js/__tests__/SaveInterface.test.js, js/__tests__/midi.test.js, js/activity.js, js/midi.js
@walterbender I have made tests for midi file. I brought `getClosestStandardNoteValue` to midi.js as it is solely used by it. This will improve maintenance and make it easier to write test cases.
Please review this PR.
=> test suite for js/midi

js/turtle-singer.js
Due to the recent changes in `setMasterVolume`, the playback was not working.  `setMasterVolume` now accounts `blk` which is only for blocks and hence widgets failed to use this function. 
This PR solves this issue. 
@walterbender, please review this PR.
=> Play widget

js/turtle-singer.js, js/turtleactions/VolumeActions.js, js/utils/__tests__/synthutils.test.js, js/utils/synthutils.js
Resolves #4474. 
1. Added new tests in synthutils.test.js
2. Added checks in setSynthVolume function.
3. Made some cleanups and moved setVolume of SetMasterVolume function(in Synthutils.js) in the "no connections" code, as setVolume should be triggered only in the no-connections condition.
@walterbender  please review.
=> add: added new tests in synthutils

js/activity.js, js/piemenus.js
This PR resolves the following issues:
1.  Fixes Duplicate Multiple Blocks Issue ([#4434](https://github.com/sugarlabs/musicblocks/issues/4434))
2.   Added "Delete" and "Duplicate Multiple Blocks" buttons to the Helpful Wheel.  
3.    Removed the previous "Delete Multiple Blocks" option from the right-click menu, as it's now accessible via the Helpful 
Wheel.
4. The Helpful Wheel now closes when the "Select" button is clicked.
[copy_select_bug_fix.webm](https://github.com/user-attachments/assets/b7e45b5d-cebe-4504-bd86-1dafc797af4e)
=> Fix Duplicate Multiple Blocks Issue & Enhance Helpful Wheel

README.md, index.html, index.js, package-lock.json, package.json
fixes: #4305 
This PR fixes the slow loading of Music Blocks. 
(Draft)
This PR will contain comparatively bigger changes. So I'll keep on adding commits here to describe what they do.
Total loading time - `~ 16.0 seconds`
cc @walterbender @pikurasa 
82bf4ca7460365be83c96b288d20274e3b9a5088 formats the index.html file as it was not formatted properly.
4ffa1342628812d82c1cb13c02a054b3fc362533 add header links in optimized order to efficient loading
10723b39c305f9df758c4854f30ba7cf1e555e17 fixes the `render-blocking` issue and bring the `cumulative-layout-shift` score from `0.20` to `0.07`
5084cf7dd7e35209d21744e912e39d62015f64f1 implements `http-server` replacing the `SimpleHTTPServer`. Upgrades `HTTP` from `1.0` to `1.1` with `Keep-Alive` enabled
e6ad80f4a9a0339b68effe114f61a606dab2dbd8 …
=> [Performane] : Fix slow loading of Music Blocks on all the browsers

index.html
Resolves the issue #4483 @walterbender please review this now its working absolutely fine
=> Resolves conflict in index.html

README.md
This PR adds the required license header to the test guide, ensuring consistency across all test files.
=> Add License Header to top-level README.md file

js/base64Utils.js, js/utils/__tests__/tonemock.js, planet/js/main.js
This PR adds AGPL-3.0 license headers to files that were missing them. The changes ensure compliance with the project's licensing requirements while preserving the integrity of the existing codebase.
- Added AGPL-3.0 license headers to files that were missing them in js/ and planet/ dirs
- Preserved existing content, including comments, in all files.
- Used Git history to determine the original author and creation year for each file.
=> Add AGPL-3.0 License Headers to Missing Files

js/widgets/jseditor.js
Closes [#4497](https://github.com/sugarlabs/musicblocks/issues/4497)  
- Implemented a draggable divider in the JavaScript editor.  
- Allows users to resize the JS editor pane dynamically for better usability.  
- Ensured smooth interaction and responsiveness.  
1. Open the **Auxiliary Menu**.  
2. Switch to **Advanced Mode**.  
3. Click on **JavaScript Editor**.  
4. Drag the divider to resize the editor and verify smooth resizing behavior.  
- Enhances UX by providing better control over editor space.  
- Tested for responsiveness and smooth interaction.
=> Implement draggable divider for resizing editor and console areas

index.html
This is a draft PR regarding fixing the issue of the play-only-mode not rendering even when the trigger point is reached. This PR is related to fixing #4493.
=> Adding Meta tag for ensuring transition of Play-Only-Mode

lilypond/README.md
The url for both Linux and Windows now point to correct page.
Fixes: #4394
=> Change the download url for lilypond for linux and windows to point correct page

js/blocks/__tests__/BooleanBlocks.test.js
This PR adds license header to `BooleanBlocks.test.js`.
#4478
=> Add License Header

.github/ISSUE_TEMPLATE/DMP_2024.yml
This PR updates our DMP file to its upstream (https://github.com/Code4GovTech/C4GT/blob/main/.github/ISSUE_TEMPLATE/DMP_2024.yml)
I have kept "2024" in the filename as it seems that the upstream has purposely kept that same name (there's a commit that reverts the name from "2025" to "2024").
=> Update DMP template from its source

css/activities.css, css/themes.css, index.html, js/activity.js, js/toolbar.js
Shifting style properties of renderClearConformation to an external CSS file. Also, the clear canvas dialogue box was rendered again if it already existed. This PR has fixed this issue.
=> internal to external css

.github/workflows/node.js.yml
Updated the smoke test workflow to use the newer versions of Github Actions:
- Changed actions/checkout from v2 to v3
- Changed actions/setup-node from v1 to v3
This update improves performance, security, and compatibility with the latest Github Actions features.
Closes #4531
=> Replaced actions/checkout@v2 and actions/setup-node@v1 with v3

.github/workflows/linter.yml
@walterbender I refactored the ESLint worflow with following changes
1. Updated Node.js version to 20.x
2. Fixed retrieval of changed JavaScript files using ```git diff --name-only -- '*.js' ```
3. Refactored ESLint execution to use xargs for better performance.
Please review this and request if any further changes are required.
=> Refactoring ESLint workflow for accuracy and stability

css/activities.css, css/themes.css
This PR addresses the resurface of issue https://github.com/sugarlabs/musicblocks/issues/4381
It occurred after https://github.com/sugarlabs/musicblocks/commit/f3df4cad7a1fc3b42b5da06853eaf8708fd87995. 
After changes, The Canvas Background color changes in Dark mode as expected.
Before changes- 
After changes-
=> [Fix] Dark mode Canvas background color in collapsed-view

js/blocks/SensorsBlocks.js, js/blocks/__tests__/SensorsBlocks.test.js
I have added tests to js/blocks/SensorsBlocks.js file 
can you plzz review it @walterbender
=> added test to SensorsBlocks.js

package.json
This PR removes the unused Volo configuration from the codebase.  
- Searched for `require('domReady')` or `define(['domReady'], function(...) { ... })`but found no occurrences.
- Searched for `require('webL10n')` or `define(['webL10n'], function(...) { ... })`but found no occurrences.
- Used VS Code's Global Search to check for any references to Volo in the codebase but found none.  
- Confirmed that Volo is not listed in `dependencies` or `devDependencies`. 
```js
npm install
npm run dev
```
=> Remove Unused Volo Configuration

js/activity.js
- The updated code checks if activity.statsWindow is already open before creating a new one.
- If the window exists (activity.statsWindow) and is open (activity.statsWindow.isOpen), it does nothing.
- If it's not open, a new StatsWindow instance is created.
Fixes #4557
=> Solved Multiple StatsWindow instances created when clicking the "Display statistics" button repeatedly

js/README.md
Updated README to reference the correct file (toolbar.js instead of toolbox.js) in the instructions for adding a new language.
=> fix: correct filename from toolbox.js to toolbar.js in README

js/widgets/temperament.js
@walterbender  In PR #4551, the functionality works fine in table mode. However, in circular mode, it throws an error because docById("pitchNumber_" + i); is only loaded in table mode and not in circular mode
=> Ensure nodes play properly in circular mode.

js/activity.js
Hii @walterbender ,
This PR solves the console error issue #4441 due to unwanted keyboard shortcut "alt+d".
could you please review it. 
Thank you
=> solves console error due to keyboard shortcut ALT+D

js/__tests__/toolbar.test.js, js/toolbar.js
I made some changes in toolbar.js that do not create any bugs (at least based on my testing). 
renderNewProjectConfirmation() was exposed outside, so whenever toolbar.js was loaded, it would run.
@walterbender, Please review this PR at your convenience.
=> jest test for toolbar.js

.github/workflows/node.js.yml
@walterbender as suggested in this https://github.com/actions/runner-images/issues/11101 we need to change the image label to ubuntu-latest for perfect working of the Smoke Test (which fails in last PR merge) please review this !!
=> Resolves failure of smoke test 

po/ayc.po, po/gn.po, po/ja.po, po/ko.po, po/pt.po, po/quz.po, po/th.po, po/zh_CN.po, po/zh_TW.po
This PR updates the translations for **"JavaScript Editor"** in all supported languages listed in the language selection dropdown.
No changes were made to `localisation.ini`. Let me know if it needs to be regenerated or if it is handled automatically.  
Additionally, I noticed that some `.po` files contain empty translation fields, which seems to be a separate issue. I will open a new issue for that.
Resolves #3698 – Rename the button from **"Toggle JavaScript Editor"** to **"JavaScript Editor"** for all supported languages.
=>  Translate 'JavaScript Editor' for all supported languages

js/widgets/pitchstaircase.js
issue : https://github.com/sugarlabs/musicblocks/issues/4461
Repeated calls to document. getElementsByClassName , document.querySelectorAll, etc., without caching the results.
Many event listeners are added without being removed when components are destroyed.
=> [Optimization] Optimize  DOM - improve the performance

guide/README.md
This PR adds documentation for the frequency display feature implemented  #4615.
=> Add documentation for frequency display in Sampler widget

docker-compose.yml, dockerfile, js/collaboration/collaboration.js, nginx.conf
@chimosky I have commented out the previous code for now (to keep it just in case I need it later) but once I get your input on these new configurations, I'll clean things up.
=> use nginx to proxy browser request to collaboration-server service.

lib/README.md
This PR documents the purpose of `.min.js` files and provides a comprehensive table linking commonly used minified JavaScript libraries to their upstream (non-minified) source repositories for reference and development use.
- Added a brief explanation of what `.min.js` files are and their usage in production.
- Created a structured table mapping JavaScript files to their corresponding upstream GitHub repositories.
- Noted version differences where applicable and flagged unmaintained libraries or missing upstream links.
cc: @walterbender
=> Add upstream source mapping for minified JS libraries

index.html
- Add `lang="en`" attribute to the `<html>` tag
- Improve accessibility for screen readers
- Enhance SEO by specifying the document language
- Help search engines better interpret content language
_Reference:_ https://www.w3.org/International/questions/qa-lang-why
=> Add lang="en" attribute to index.html

index.html
- Updated `<amp-img>` tag in `index.html` to include proper `alt`  attributes.
- Improves accessibility (screen reader support)
- Enhances semantic HTML for better UX
Self-initiated contribution while exploring MusicBlocks as part of the Code4GovTech 2025 program.
=> Improved accessibility: added alt and title to logo image

js/widgets/musickeyboard.js
I have now implemented a method for playing chords on the music keyboard. It will recognize notes as a chord if they are played simultaneously, as the grid arrangement only allows for equal start and end times. If the start times are unequal, it will interpret them as single notes.
As promised, the metronome will now stop if the play button is clicked, so they don't play together.
@pikurasa Please test this PR at your convenience.
[playChord.webm](https://github.com/user-attachments/assets/ed23d665-9683-48f5-834a-cdf196f77d2f)
=> play chord in music keyboard

js/utils/musicutils.js
@walterbender @pikurasa . This PR fixes the 31 EDO bug. Please review it.
@omsuneri  As I remember, you had asked me to tag you once I fixed this issue.
I initially thought this would be an easy fix, but it turned out to be a bit tricky. Here's an explanation of what I did, the changes involved, and the reasoning behind them.
**Explanation, Changes, and Reasoning**
The key to getting those 31 circular nodes right lies in the intervals array (under the equal31 key in the TEMPERAMENT object). It needs to contain 32 entries — since there are 31 equal divisions of the octave, there must be 32 boundaries between them. These entries must also be unique in both name and value; otherwise, we wouldn't be able to see exactly 31 nodes arranged in a circular fashion.
To populate these values …
=> Fixed 31EDO bug and cleaned up a bit of code

cypress/e2e/main.cy.js
fixes: #4489
This PR fixes the tests related to the toolbar and the planet.
@walterbender Please have a look.
=> test: fix the test of toolabar and the planet

js/__tests__/palette.test.js
- Remove debug console.log statements from palette.test.js
- Improves test output clarity by removing noise
- Follows best practices for test file cleanliness
=> test: remove unnecessary console.log statements from palette tests

guide/README.md
I have taken a simple and direct approach following the issue requirements:
1. Added examples of G♯ Major, D♯ Major, and F♭ Major scales showing where double-sharps/flats occur
2. Included the reference to Bartók's Mikrokosmos No. 136 as suggested
3. Added brief explanations of why these notation choices are necessary
Fixes #3855
=> Add musical examples of double-sharp and double-flat usage (#3855)

js/activity.js
Description
This PR addresses a UI issue in the Music Blocks toolbox where:
Clicking on the search bar causes the first menu item (like "Flow", "Action") to disappear.
Fixes Implemented
Prevent menu items from hiding when the search bar is focused.
before 
https://github.com/user-attachments/assets/865e150d-ab18-41e8-9cd4-a671e63b2b7a
after 
https://github.com/user-attachments/assets/f8913041-8bc5-48db-8cc1-fce3bbb810dc
=> Fix Menu & Search Bar Interaction Bug in Music Block

js/palette.js
This PR resolves issue #4718  by introducing an **outside click handler** for the palette menu. With this enhancement, the palette now automatically closes when the user clicks anywhere outside of it, ensuring a more intuitive and streamlined user experience.
---
- Implemented a `click` event listener on `document` after the palette menu is shown.
- The listener checks if the click occurred outside the `menuContainer`.
- If true, it calls the existing `hideMenu()` method.
- The listener is automatically removed after the first invocation to prevent memory leaks.
- Introduced `this._outsideClickListener` in the `Palette` class constructor to store and manage the listener properly.
- Ensured multiple openings of the menu don’t register duplicate listeners.
--- …
=> Close Palette Menu on Outside Click

planet/js/Planet.js, planet/js/ProjectStorage.js
Two issues were breaking the planet:
(1) a typo introduced to PlanetStorage was preventing the planet from loading at all has been fixed;
(2) the "toolbar disappears" issue seems to be due to a local storage issue that occasionally prevents the Local Planet from being defined. The root cause is not fixed but the error breaking the toolbar should be fixed.
=> Local planet

js/activity.js, js/blocks/WidgetBlocks.js, js/widgets/aidebugger.js
@pikurasa @walterbender this is the widget implementation code in music blocks 
please review !!
=> AI-powered Debugger widget 

js/widgets/aidebugger.js
@walterbender please review this replaces the old icon for the export chat with the new download icon
=> fix: changing icon from `export-button.svg` to `download.svg` in debugger 

js/widgets/reflection.js
@walterbender I have changed the programming mentor name to 'Alan Kay'. Also added a refresh button.
Please review this.
[main.webm](https://github.com/user-attachments/assets/00b29ef4-5af6-475b-b3af-ada0c5a783c5)
=> Update mentor name to Alan and reload functionality added
